### ISSUE TITLE
Hostname needs to be countable for metrics monitoring

### ISSUE THREAD

**Issue by tehlers320** [aws/amazon-ecs-agent#606] opened 2016-11-21 17:43 UTC
ECS needs the ability to name instances and name the instances with a human readable name and increment the value as more containers start. It would also need to take the number of an instance that goes down.
$appname0001
$appname0002
$appname0003

Users of graphite/influxdb will end up with millions of tags/graphite trees without this feature.

**Comment by CpuID** [comment] 2016-11-21 19:52
I would argue requiring numbering is a backwards step, as it requires a central coordinator to auto increment the instance name/s. Plus, duplicating logic that exists in the form of EC2 instance IDs right now feels like reinventing the wheel?

I would think the right approach with graphite/influxdb is a cleanup batch process that checks what EC2 instances remain online, and cleans up old trees after X period of retention once they no longer exist.

**Comment by CpuID** [comment] 2016-11-21 20:05
@tehlers320 thats very valid. Would it be possible to have said batch process perform a form of roll-up instead, rolling the metrics into non-host-specific trees...? I haven't actually done that myself, but I suspect if it's just a matter of aggregating time series data, there would be some way to do it?

Just a side note, I am probably about to have a similar issue to assess :) Brainstorming ways I would likely solve it.

**Comment by tehlers320** [comment] 2016-11-21 20:13
In graphite this would be a horrible process. You would need to use whisper-merge.py to roll the metrics into another tree. Influx might be a little more elegant but i'm not sure.

**Comment by samuelkarp** [comment] 2016-12-11 21:51
@tehlers320 Thanks for opening this and @CpuID thanks for sharing your thoughts too! I'm going to close this as a duplicate of https://github.com/aws/amazon-ecs-agent/issues/451, since this is pretty related to that.

**Closed by samuelkarp** 2016-12-11 21:51 UTC
