### ISSUE TITLE
Logentries docker driver

### ISSUE THREAD

**Issue by AbelGuti** [aws/amazon-ecs-agent#1059] opened 2017-11-08 20:37 UTC
I saw that some days ago the logentries driver configuration was included into readme.
https://github.com/aws/amazon-ecs-agent/pull/909/files
So I wondering if it is available now in the new docker agent version (1.15.0)  and if it is how I can implement it because i cant configure this driver manually when Im creating a task definition in the aws console.

**Comment by adnxn** [comment] 2017-11-09 06:46
hi @AbelGuti, you're right, currently we don't have the logentries driver as an option through the aws console.

you can still use the Logentries driver by registering a task [using the cli](http://docs.aws.amazon.com/cli/latest/reference/ecs/register-task-definition.html). First add `logentries` as a `ECS_AVAILABLE_LOGGING_DRIVERS` in the ecs config file, then include the `logConfiguration` in your task definition as follows:
```
"containerDefinitions": [
        {
          ...
          "logConfiguration": {
                "logDriver": "logentries",
                "options": {
                    "logentries-token": "$TOKEN_PROVIDED_BY_LOGENTRIES"
                 }
           }
  ]
```

**Comment by stefansedich** [comment] 2017-11-15 17:51
This is working for me however looks like the 'line-only' option has not been released yet (I see it in master but has not made it to a release yet) making the resulting logs pretty useless for me.

**Comment by adnxn** [comment] 2017-11-17 18:39
There is also a `Configure via JSON` button in "Create a Task Definition" for the ECS console, and you're able to add `logConfiguration` details there as you would with the cli.

The fix for the console is on our roadmap and I'm closing this issue for now since the problem is not in agent codebase. Feel free to open a new issue if you run into problems using the Logentries driver in the future. Thanks =]

**Closed by adnxn** 2017-11-17 18:39 UTC

**Comment by eldos-dl** [comment] 2018-04-25 08:27
Do we need to add any custom attribute to the container instance for this to work?

**Comment by dserodio** [comment] 2018-11-09 13:32
Does anyone know if the `line-only` option is available in ECS, and if so, in which version?
