### ISSUE TITLE
IAM role not applied to ecs container after deploy

### ISSUE THREAD

**Issue by billcrook** [aws/amazon-ecs-agent#1146] opened 2017-12-18 23:05 UTC
### Summary
Containers configured with a custom IAM role are not assuming the role after a new task definition is deployed.

### Description
I have a task definition which configures a custom IAM role. I find that the role is not applied after a new task definition version is deployed. I should note that the both the old and new versions of the task definition have the role applied. The role is applied and functions correctly after I bounce the ecs agent.

### Expected Behavior
The container should always have the configured role applied to it at all times.

### Observed Behavior
After a deploy, the container cannot access AWS resources as allowed in the IAM role. I see errors from the ECS agent in the log. See below for the ECS log output.

After I restart the ecs agent, the role is applied to the recently deployed container.

### Environment Details
Amazon linux: ami-fad25980
ECS agent: 1.16.0
docker: 17.06.2-ce, build 3dfb8343b139d6342acfd9975d7f1068b5b1c3d3

### Supporting Log Snippets
`Error when retrieving credentials from container-role: Error retrieving metadata: Received error when attempting to retrieve ECS metadata: HTTPConnectionPool(host='169.254.170.2', port=80): Max retries exceeded with url: /v2/credentials/7f147da7-f2d9-4bad-a297-e1e085b4a2f5 (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f6d1f4d79b0>, 'Connection to 169.254.170.2 timed out. (connect timeout=2)'))`

**Comment by jahkeup** [comment] 2017-12-20 00:19
@billcrook that appears to be a bug. I suspect this is a deeply rooted issue and I'd like to take a closer look at the Agent's logs to confirm and track down the issue. Can you run the [ECS logs collector](https://github.com/awslabs/ecs-logs-collector) and email the resulting file to me at jakeev at amazon.com?

**Comment by jahkeup** [comment] 2017-12-20 00:29
@billcrook a few questions in addition to the above:

* How often does this behavior surface?
* Does the Task come up at any point after it fails without restarting Agent?
* Can you reliably reproduce this today?

**Comment by billcrook** [comment] 2017-12-20 00:35
> How often does this behavior surface?
After deployments of new task definitions. We only have a few containers with the task role defined which is where we have seen the issue.

> Does the Task come up at any point after it fails without restarting Agent?
Yes, the containers is running fine, it just can't access any AWS resources in the policy of the task role. For example, kms keys, s3 buckets, etc... After bouncing the ecs agent, the role is applied and the container then has access. I don't have to restart the affected containers, bouncing the ecs agent allows them to function.

> Can you reliably reproduce this today?
We saw it many times as recently as yesterday. We had to roll back to instance profiles on the ECS node for now - we don't want to automate bouncing ECS agent. It reminds me too much of rebooting things like weblogic in the past 😛 

I will try and generate ECS logs.

**Comment by billcrook** [comment] 2017-12-20 01:30
ECS logs sent to your email. This looks relevant:
`collect/system/ecs-init/ecs-init.log:2017-12-15T14:53:24Z [ERROR] Error performing action 'delete' for credentials proxy endpoint route: exit status 1; raw output: iptables: No chain/target/match by that name.`

**Comment by jahkeup** [comment] 2017-12-20 22:03
Thank you for sending along the logs @billcrook!

I've given the logs a read through and I saw the error you called out. It's strange that the iptables rules were missing when `ecs-init` tried to clean up the rules that it should have inserted. If the rules are missing that's definitely an issue and will prevent the Tasks from getting their credentials.

* Is the instance running any additional tools that may have modified the iptables chains after starting the Agent?

  A few iptables rules are inserted when starting up the ECS Agent (during `start ecs` using ecs-init) and are needed to allow Tasks to reach the credentials endpoint. If these are missing when your Task starts the Task would fail as observed as the request would never reach the credentials endpoint.

* Have any Tasks had problems on this particular instance since the last time the Agent was restarted on the 15th?

I noticed that the logs provided were collected while the Agent was running in the default INFO log level. At this log level, there may be some debugging messages omitted that may prove helpful. If you are able to reproduce this issue again, can you run the Agent in DEBUG log level and run Tasks until one cannot fetch credentials? The ECS Log Collector has a flag to [configure Docker and the ECS Agent in debug mode](https://github.com/awslabs/ecs-logs-collector#example-output-in-debug-mode) (eg: `bash ecs-log-collector.sh --mode debug-only`) and __will restart both Docker and ECS Agent__ to apply the flags. Once you see the application error fetching credentials can you run the log collector to collect logs and send those along? This will help us narrow down why the credentials aren't being retrieved properly.

Thanks!

**Comment by billcrook** [comment] 2017-12-21 04:36
> Is the instance running any additional tools that may have modified the iptables chains after starting the Agent?

No. I will send you the user-data so you have a full picture.

> Have any Tasks had problems on this particular instance since the last time the Agent was restarted on the 15th?

We reverted to instance profiles, so no.

I will try to find some time to reproduce with debug log level, but it probably won't be until 2018.

**Comment by aaithal** [comment] 2018-01-26 00:58
Hi @billcrook, 

Have you had time to get back to this? If you're able to repro this, we'd really appreciate it if you could send logs and the userdata to aithal at amazon dot com.

Thanks,
Anirudh

**Comment by aaithal** [comment] 2018-02-07 17:12
Hi @billcrook, we're closing this issue for now. Please let us know when you have the information we asked for and we can reopen this issue. Thanks!

**Closed by aaithal** 2018-02-07 17:12 UTC
Labels: more info needed

**Comment by sunil-freshworks** [comment] 2019-09-19 05:25
This could also happen if you accidentally stop the docker service or the ecs service. 
You can check the status of these services and restart them accordingly to get rid of this issue.
