### ISSUE TITLE
Unable to specify new clusters via ECS_CLUSTER env variable

### ISSUE THREAD

**Issue by mmontagna** [aws/amazon-ecs-agent#750] opened 2017-04-04 20:41 UTC
I've run into a bit of a strange situation. I am running the ECS agent via the provided docker image and trying to specify the ECS_CLUSTER by name eg 

```
/usr/bin/docker run  \
    --detach=false \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    --volume=/var/log/ecs:/log \
    --volume=/var/lib/ecs/data:/data \
    --net=host \
    --env-file=/etc/ecs/ecs.config \
    --env=AWS_DEFAULT_REGION=us-east-1 \
    --env=ECS_CLUSTER=My-New-Cluster\
    --env=ECS_LOGFILE=/log/ecs-agent.log \
    --env=ECS_DATADIR=/data/ \
    --env=ECS_ENABLE_TASK_IAM_ROLE=true \
    --env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true \
    --env=ECS_AVAILABLE_LOGGING_DRIVERS='["json-file","syslog"]' \
    amazon/amazon-ecs-agent:latest
```

The cluster definitely exists, but this results in the agent spitting out the following error:
```
2017-04-04T20:25:28Z [INFO] Registering Instance with ECS
2017-04-04T20:25:28Z [ERROR] Could not register: ClientException: Cluster not found.
	status code: 400, request id: d80a1710-1974-11e7-8d25-f5b6f8f756fa
```

If I specify one of the clusters I created months ago the agent connects without issue, from
the same instance/config.

Now the interesting part is that if I specify the new cluster by it's full ARN then the agent connects no problem:

```
/usr/bin/docker run  \
    --detach=false \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    --volume=/var/log/ecs:/log \
    --volume=/var/lib/ecs/data:/data \
    --net=host \
    --env-file=/etc/ecs/ecs.config \
    --env=AWS_DEFAULT_REGION=us-east-1 \
    --env=ECS_CLUSTER=arn:aws:ecs:us-east-1:12345678:cluster/My-New-Cluster \
    --env=ECS_LOGFILE=/log/ecs-agent.log \
    --env=ECS_DATADIR=/data/ \
    --env=ECS_ENABLE_TASK_IAM_ROLE=true \
    --env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true \
    --env=ECS_AVAILABLE_LOGGING_DRIVERS='["json-file","syslog"]' \
    amazon/amazon-ecs-agent:latest
```

Is this the intended behavior? It is confusing because it is inconsistent.

**Comment by mmontagna** [comment] 2017-04-05 00:43
Sent you an email with that info, thanks!

**Comment by richardpen** [comment] 2017-04-07 19:53
@mmontagna Thanks for sending this information. After looking at the logs, looks like the error `status code: 400, request id: d80a1710-1974-11e7-8d25-f5b6f8f756fa` was caused by a misspelling of the cluster name, in which the request was looking for cluster `cananda` while you only have cluster `canada` in us-east-1. Please let me know if you still experience this problem?

 Thanks,
 Richard

**Comment by richardpen** [comment] 2017-04-10 20:10
@mmontagna I'm closing this for now, feel free to reopen it if you still have this problem.

**Closed by richardpen** 2017-04-10 20:10 UTC
