### ISSUE TITLE
docker daemon default setting for IPC mode is not used by containers launched via ECS when IPC is not specified

### ISSUE THREAD

**Issue by dhruvmukherjee** [aws/amazon-ecs-agent#2955] opened 2021-07-15 18:06 UTC
### Description

According to the [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_definition_ipcmode),  it can be understood that while not specifying any value for IPC mode, then the IPC resource namespace sharing depends on the Docker daemon setting on the container instance.

I set the `default-ipc-mode` option for the docker daemon inside the file /etc/docker/daemon.json as follows :-

```
{
  "default-ipc-mode": "private"
}
```

And restarted the docker daemon as - `sudo systemctl restart docker`

Now I created a sample task definition like below -

```
{
  "ipcMode": null,
  "containerDefinitions": [
    {
      "linuxParameters": {
        "sharedMemorySize": 128
      },
      "cpu": 0,
      "memoryReservation": 128,
      "image": "nginx",
      "essential": true,
      "name": "ipc-test"
    }
  ],
  "compatibilities": [
    "EXTERNAL",
    "EC2"
  ],
  "requiresCompatibilities": [
    "EC2"
  ]
}
```

When I started the task, and checked the IPC mode used for the container by inspecting it, I observed the IpcMode was set as `shareable` instead of `private`

Later I tried to start a container manually inside the host as -

`$docker container start nginx`

And noticed the IpcMode was set as `private` only as expected.

As per the code - https://github.com/aws/amazon-ecs-agent/blob/4d4c4afffc7283089c74d4513a9c5d90d3842c43/agent/api/task/task.go#L1518

The "if" block would only be executed if the value of "ok" would be true. 

And here - https://github.com/aws/amazon-ecs-agent/blob/4d4c4afffc7283089c74d4513a9c5d90d3842c43/agent/api/task/task.go#L1729

IpcMode should be null and it should return false.

So ideally the IpcMode was not at all overridden and it should use the default setting of the docker daemon.

### Expected Behavior

I expected the container launched via ECS should have used IpcMode as `private` instead of `shareable`
### Observed Behavior

The manually started container showed IpcMode as `private`
Container launched via ECS showed IpcMode as `shareable`

Docker daemon had the following option mentioned - `"default-ipc-mode": "private"`

### Environment Details

```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 26
  Running: 3
  Paused: 0
  Stopped: 23
 Images: 3
 Server Version: 19.03.13-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0 (expected: fec3683)
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.232-177.418.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.85GiB
 Name: ip-10-0-16-58.ap-south-1.compute.internal
 ID: FMON:HNP2:G26G:QOYL:E7SN:MPZE:B2FW:ZF6R:6N6X:VLO2:XZXP:TQ2B
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

```
ECS agent version :- 1.54.0
```

**Comment by sharanyad** [comment] 2021-07-15 19:35
I was able to reproduce the issue. Looking into where this change is stemming from.

**Comment by sharanyad** [comment] 2021-07-16 00:24
@dhruvmukherjee Looks like in docker api version 1.40 the default value of ipcMode was [changed](https://docs.docker.com/engine/api/version-history/) from 'shareable' to 'private'. Hence the container started manually has ipcMode as private. 
ECS Agent uses 1.21 api version for the docker client because of which ipcMode is shareable. 

But that said, while using 1.21 version docker client and dockerd option set as `default-ipc-mode=private`, the containers still start with ipcMode as shareable. Digging more.

**Comment by sharanyad** [comment] 2021-07-16 16:29
Missed that `default-ipc-mode` option is supported only from API version 1.40, hence this wont be respected with 1.21 client version. 

If ipcMode `private` is required, the only way is to explicitly set it in ECS task definition. 

Since there is no action item here, I'm closing this issue. Please feel free to reopen if there are more questions. 

Thanks,
Sharanya

**Closed by sharanyad** 2021-07-16 16:29 UTC
