### ISSUE TITLE
Fix vendoring for fsouza/go-dockerclient 

### ISSUE THREAD

**Issue by vsiddharth** [aws/amazon-ecs-agent#694] opened 2017-02-02 22:48 UTC

**Comment by petderek** [comment] 2017-03-31 16:21
This is a bug caused by rewriting imports using mockgen. This only affects our code generate scripts -- no issues with the build or agent itself.

**Comment by samuelkarp** [comment] 2017-05-12 22:58
Looks like @petderek's fix was merged.

**Closed by samuelkarp** 2017-05-12 22:58 UTC
Labels: enhancement, scope/ECS Agent
