### ISSUE TITLE
Agent creates giant logs, crashes

### ISSUE THREAD

**Issue by tamasflamich** [aws/amazon-ecs-agent#507] opened 2016-08-24 16:06 UTC
Agent version: **1.11.1**

On the ECS dashboard we noticed disconnected ECS agents regularly. SSHd into one of the host instances:

```
ls /var/log/ecs
...
ecs-agent.log.2016-08-24-00
ecs-agent.log.2016-08-24-01
ecs-agent.log.2016-08-24-02
ecs-agent.log.2016-08-24-07
ecs-agent.log.2016-08-24-08
...
```

This was quite suspicious. It turned out that `ecs-agent.log.2016-08-24-02` is a very large log file (1GB) with the following content:

```
2016-08-24T02:45:01Z [INFO] Redundant container state change for task [task_name]:27 arn:aws:ecs:eu-west-1:[account_id]:task/[task_id], Status: (RUNNING->RUNNING) Containers: [container1 (RUNNING->RUNNING),container2 (RUNNING->RUNNING),container3 (RUNNING->RUNNING),]: container3([container_path]) (RUNNING->RUNNING) to RUNNING, but already RUNNING
2016-08-24T02:46:00Z [WARN] Error retrieving stats for container 5d53938f8bb99168274410c4abc463304053a093d32fa11f81b90e2c110f982d: io: read/write on closed pipe
2016-08-24T02:46:39Z [WARN] Error retrieving stats for container 5dba9b8670f1a222dcf16f163d5b12190ab2a0ff0c56f30fafa510aa20ec2813: io: read/write on closed pipe
2016-08-24T02:46:58Z [INFO] Creating poll dialer, host: ecs-a-1.eu-west-1.amazonaws.com
2016-08-24T02:47:18Z [INFO] Redundant container state change for task [task_name_2]:25 arn:aws:ecs:eu-west-1:[account_id]:task/[task_id_2], Status: (RUNNING->RUNNING) Containers: [container1 (RUNNING->RUNNING),container2 (RUNNING->RUNNING),container4 (RUNNING->RUNNING),container5 (RUNNING->RUNNING),]: container1([container_path]) (RUNNING->RUNNING) to RUNNING, but already RUNNING
2016-08-24T02:47:18Z [INFO] Redundant container state change for task [task_name_2]:25 arn:aws:ecs:eu-west-1:[account_id]:task/[task_id_2], Status: (RUNNING->RUNNING) Containers: [container1 (RUNNING->RUNNING),container2 (RUNNING->RUNNING),container4 (RUNNING->RUNNING),container5 (RUNNING->RUNNING),]: container2([container_path]) (RUNNING->RUNNING) to RUNNING, but already RUNNING
2016-08-24T02:47:18Z [INFO] Redundant container state change for task [task_name_2]:25 arn:aws:ecs:eu-west-1:[account_id]:task/[task_id_2], Status: (RUNNING->RUNNING) Containers: [container1 (RUNNING->RUNNING),container2 (RUNNING->RUNNING),container4 (RUNNING->RUNNING),container5 (RUNNING->RUNNING),]: container4([container_path]) (RUNNING->RUNNING) to RUNNING, but already RUNNING
2016-08-24T02:47:18Z [INFO] Redundant container state change for task [task_name_2]:25 arn:aws:ecs:eu-west-1:[account_id]:task/[task_id_2], Status: (RUNNING->RUNNING) Containers: [container1 (RUNNING->RUNNING),container2 (RUNNING->RUNNING),container4 (RUNNING->RUNNING),container5 (RUNNING->RUNNING),]: container5([container_path]) (RUNNING->RUNNING) to RUNNING, but already RUNNING
2016-08-24T02:49:09Z [WARN] Error retrieving stats for container ded1fb6bb4815779050ff971d39e207a6b12f7c89d67223532e7052958aea018: io: read/write on closed pipe
2016-08-24T02:49:24Z [WARN] Error retrieving stats for container 757491d64e433d72a953ca2316d35a67015e8cfb56b28e26e0971f88f36ff735: io: read/write on closed pipe
2016-08-24T02:50:36Z [WARN] Error retrieving stats for container 224c4e80d4cd3958b0bceede45eb4d6918ae260139dca83848ba893ad8663e0a: io: read/write on closed pipe
2016-08-24T02:51:39Z [WARN] Error retrieving stats for container b6042e91121f8829eac587ccdc3ebe51f9154d2cf9f8230b1a7b95052f5e1f54: io: read/write on closed pipe
2016-08-24T02:51:39Z [WARN] Error retrieving stats for container b6042e91121f8829eac587ccdc3ebe51f9154d2cf9f8230b1a7b95052f5e1f54: dial unix /var/run/docker.sock: socket: too many open files
2016-08-24T02:51:39Z [WARN] Error retrieving stats for container b6042e91121f8829eac587ccdc3ebe51f9154d2cf9f8230b1a7b95052f5e1f54: dial unix /var/run/docker.sock: socket: too many open files

[millions of the same record]

2016-08-24T02:59:59Z [WARN] Error retrieving stats for container b6042e91121f8829eac587ccdc3ebe51f9154d2cf9f8230b1a7b95052f5e1f54: dial unix /var/run/docker.sock: socket: too many open files
2016-08-24T02:59:59Z [WARN] Error retrieving stats for container b6042e91121f8829eac587ccdc3ebe51f9154d2cf9f8230b1a7b95052f5e1f54: dial unix /var/run/docker.sock: socket: too many open files
```

Then the agent probably crashed and restarted a couple of hours later:

```
2016-08-24T07:40:17Z [INFO] Starting Agent: Amazon ECS Agent - v1.11.1 (0d123a2)
2016-08-24T07:40:17Z [INFO] Loading configuration
2016-08-24T07:40:17Z [WARN] Invalid value for task cleanup duration, will be overridden to 3h0m0s, parsed value 0, minimum threshold 1m0s
2016-08-24T07:40:17Z [INFO] Checkpointing is enabled. Attempting to load state
2016-08-24T07:40:17Z [INFO] Loading state! module="statemanager"
2016-08-24T07:40:17Z [INFO] Restored cluster '[cluster]'
2016-08-24T07:40:17Z [INFO] Detected Docker versions [1.17 1.18 1.19 1.20 1.21 1.22]
2016-08-24T07:40:17Z [INFO] Restored from checkpoint file. I am running as 'arn:aws:ecs:eu-west-1:[account]:container-instance/[container_instance_id]' in cluster '[cluster]'
2016-08-24T07:40:17Z [INFO] Registered! module="api client"
2016-08-24T07:40:17Z [INFO] Saving state! module="statemanager"
2016-08-24T07:40:17Z [INFO] Beginning Polling for updates
2016-08-24T07:40:17Z [INFO] Start listening to deregister-container-instance event from ACS client
```

**Comment by aaithal** [comment] 2016-08-24 16:20
Hi @tamasflamich, thank you for reporting this issue. This seems like the duplicate of #478, which was fixed in the [v1.12.1 release](https://github.com/aws/amazon-ecs-agent/tree/v1.12.1). Please let us know if you continue to run into problems.

**Closed by aaithal** 2016-08-24 16:20 UTC
