### ISSUE TITLE
ECS Cluster metric reporting does not work with Docker 1.11

### ISSUE THREAD

**Issue by ryanwalls** [aws/amazon-ecs-agent#387] opened 2016-04-25 21:11 UTC
As soon as we updated to Docker 1.11, our ECS cluster stopped reporting metrics.

<img width="1341" alt="screenshot 2016-04-25 11 05 12" src="https://cloud.githubusercontent.com/assets/842653/14799058/f11c4f54-0af7-11e6-988f-4e41de1cf21b.png">

**Comment by samuelkarp** [comment] 2016-04-25 21:14
@ryanwalls Can you provide the following information?

* ECS Agent version (output of `curl localhost:51678/v1/metadata`)
* Docker version (output of `sudo docker version`)
* Docker debugging info (output of `sudo docker info`)
* EC2 AMI ID
* Relevant log files (usually in `/var/log/ecs` and `/var/log/docker`)

**Comment by ryanwalls** [comment] 2016-04-25 21:32
@samuelkarp 

Docker version is probably where we need to stop looking.  We use the https://get.docker.com script to install our docker engine... which unfortunately grabs the latest version all the time.  They released 1.11 on 4/12, https://github.com/docker/docker/wiki/Engine-1.11.0.  So I would say that's more than a coincidence.  

Sorry for bad description... we did update our architecture.  I'll update the title.

**Comment by ryanwalls** [comment] 2016-04-25 21:34
Agent version: 1.8.1
Docker version: 1.11

I can provide the other log files if wanted.  I imagine the Docker 1.11 thing is a known issue.

**Comment by samuelkarp** [comment] 2016-04-25 21:34
Docker 1.11.0 breaks our CloudWatch metrics feature as the `runc` and `containerd` integration changed some of the things we use to power that feature.  I'll mark this as a bug so we can track publicly; we've already been looking at paths forward here.

**Comment by ryanwalls** [comment] 2016-04-25 21:35
@samuelkarp Great.  Thanks for the quick response.

**Comment by samuelkarp** [comment] 2016-04-28 17:40
@ryanwalls There is a workaround that appears to work for me, but it's still not ideal.  You'll want to verify on your system that these are the right settings.

In Docker versions prior to 1.11, Docker would maintain state information about containers in a directory like `/var/run/docker/execdriver/native`, which we'd mount into the agent container as `/var/lib/docker/execdriver/native`.  Starting with 1.11, the directory used by Docker changed.  On Ubuntu 14.04 with the Docker project's build of Docker 1.11, the directory looks to now be located at `/run/runc`.  I was able to get the metrics working by changing the mount to `/run/runc:/var/lib/docker/execdriver/native:ro`.  Please let us know if this works for you.

**Comment by ryanwalls** [comment] 2016-04-29 03:48
@samuelkarp Thanks for the workaround!  It worked for us on our Ubuntu instances.  Metrics are coming in again.

**Comment by stannnous** [comment] 2016-05-20 14:02
We have the same problem since upgrading from Docker 1.9 on Ubuntu 14.04 to Docker 1.11 on Ubuntu 16.04 but the workaround doesn't work for us.

```
        "Mounts": [
            {
                "Source": "/var/log/ecs",
                "Destination": "/log",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/lib/ecs/data",
                "Destination": "/data",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/sys/fs/cgroup",
                "Destination": "/sys/fs/cgroup",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/run/runc",
                "Destination": "/var/lib/docker/execdriver/native",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```
The ECS log (attached) contains a lot of:

> 2016-05-20T13:31:44Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:c3738c63b52a4a6859708558fcdb0c2b3a29310302202a524b5767d7ea088e62}"
> 2016-05-20T13:31:44Z [WARN] Error getting instance metrics module="tcs client" err="No task metrics to report"

and

> 2016-05-20T13:32:24Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1002 Channel long idle: No message is received, close the channel"
[ecs-agent-log.txt](https://github.com/aws/amazon-ecs-agent/files/274684/ecs-agent-log.txt)

**Comment by rodlogic** [comment] 2016-05-23 23:12
Same here. The workaround doesn't work for us either.

**Comment by djenriquez** [comment] 2016-05-25 17:40
Confirmed the following mounts fixed the issue for ECS-Agent 1.9.0 running on Docker 1.11.1:
```
        "Mounts": [
            {
                "Source": "/var/lib/ecs/data",
                "Destination": "/data",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/sys/fs/cgroup",
                "Destination": "/sys/fs/cgroup",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/run/runc",
                "Destination": "/var/lib/docker/execdriver/native",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/log/ecs",
                "Destination": "/log",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ]```

**Comment by stannnous** [comment] 2016-05-25 20:55
@djenriquez That's the same mounts we have also using ECS-Agent 1.9.0 on Docker 1.11.1 but it doesn't work for us. Could the host OS be playing a role here? We're running Ubuntu 16.04. What did you test on?

**Comment by asmarques** [comment] 2016-05-26 09:39
Metric reporting is also not working on Ubuntu 16.04 with Docker 1.10.3 and ECS Agent 1.9.0 despite `/var/lib/docker/execdriver/native` being correctly mounted in the container.

The following message shows up in the logs:
> 2016-05-26T09:28:59Z [DEBUG] Invalid container statitistics reported, got number of cores = 0
> 2016-05-26T09:28:59Z [DEBUG] Error getting stats module="stats" error="Invalid container statistics reported" contianer="&{containerMetadata:0xc20839dc80 ctx:0xc20836e9c0 cancel:0x4ff240 statePath:/var/lib/docker/execdriver/native/a5fc48167915f0367fc3cc52cec23f0de090711aae45c46054550b9b36d32b5b statsQueue:0xc20836e980 statsCollector:0xcd9be8}"
> 2016-05-26T09:29:04Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:a5fc48167915f0367fc3cc52cec23f0de090711aae45c46054550b9b36d32b5b}"
> 2016-05-26T09:29:04Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:4ff9719a31b0be20669fa26f97c91702c0c8ff3d899f1014659453d62829cd5a}"
> 2016-05-26T09:29:04Z [WARN] Error getting instance metrics module="tcs client" err="No task metrics to report"

Looking at the code it seems this could be fixed by #400.

**Comment by aaithal** [comment] 2016-05-26 15:28
@asmarques As you correctly pointed out, #400 should fix the issue as it removes the need for mounting any of the `cgroup` or `execdriver` volumes to the ECS Agent (In fact, we have a [PR](https://github.com/aws/amazon-ecs-init/pull/47) to not mount these volumes when running the ECS Agent with ecs-init).

**Comment by richardpen** [comment] 2016-06-01 00:19
This should be fixed in ECS Agent [v1.10.0](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.10.0) release. I'm closing this issue for now, please let us know if you have any issues.

**Closed by richardpen** 2016-06-01 00:19 UTC
Labels: bug, pending release

**Comment by vladgh** [comment] 2016-06-01 03:04
@aaithal Just to make sure got this right, the following lines are not needed in the run command for v1.10.0 anymore?

```
-v /sys/fs/cgroup:/sys/fs/cgroup:ro",
-v /run/runc:/var/lib/docker/execdriver/native:ro",
```

**Comment by samuelkarp** [comment] 2016-06-01 03:05
@vladgh Yes, that's correct.
