### ISSUE TITLE
ecs-agent on CentOS - `eni not managed by ecs`

### ISSUE THREAD

**Issue by packplusplus** [aws/amazon-ecs-agent#1520] opened 2018-08-15 16:19 UTC
### Summary
I've been running ecs-init on centos 7, in an attempt to use awsvpc networking on some ECS tasks. There appears to be some issue when tasks with awsvpc that are flapping, ENIs aren't cleaned up. This seems to happen when we do a bad deploy, or config change. 

Looking for some help figuring out how to debug this, and or if it's something I should just expect to happen, and kill instances when this occurs. 

### Description

I think ecs-agent is crashing and leaving an empty, `/var/lib/ecs/data/ecs_agent_data.json`. At that point it no longer has any idea what ENIs it should know about, but I'm not sure, since eventually the agent start running again, and tasks that were running continue to run and report back to ECS. 

```
2018-08-14T16:31:48Z [INFO] Amazon ECS agent Version: 1.19.1, Commit: 13a0fabe
2018-08-14T16:31:48Z [INFO] Creating root ecs cgroup: /ecs
2018-08-14T16:31:48Z [INFO] Creating cgroup /ecs
2018-08-14T16:31:48Z [WARN] Disabling TaskCPUMemLimit because agent is unabled to setup '/ecs' cgroup: cgroup create: unable to create controller: cgroups: cgroup mountpoint does not exist
2018-08-14T16:31:48Z [INFO] Loading state! module="statemanager"
2018-08-14T16:31:48Z [CRITICAL] Could not unmarshal existing state; corrupted data? module="statemanager" err="unexpected end of JSON input" data="[]"
2018-08-14T16:31:48Z [CRITICAL] Error loading previously saved state: unexpected end of JSON input
2018-08-14T16:34:55Z [INFO] Loading configuration
2018-08-14T16:34:55Z [INFO] Amazon ECS agent Version: 1.19.1, Commit: 13a0fabe
2018-08-14T16:34:55Z [INFO] Creating root ecs cgroup: /ecs
2018-08-14T16:34:55Z [INFO] Creating cgroup /ecs
2018-08-14T16:34:55Z [WARN] Disabling TaskCPUMemLimit because agent is unabled to setup '/ecs' cgroup: cgroup create: unable to create controller: cgroups: cgroup mountpoint does not exist
2018-08-14T16:34:55Z [INFO] Loading state! module="statemanager"
2018-08-14T16:34:55Z [CRITICAL] Could not unmarshal existing state; corrupted data? module="statemanager" err="unexpected end of JSON input" data="[]"
2018-08-14T16:34:55Z [CRITICAL] Error loading previously saved state: unexpected end of JSON input
2018-08-14T16:39:16Z [INFO] Loading configuration
2018-08-14T16:39:16Z [INFO] Amazon ECS agent Version: 1.19.1, Commit: 13a0fabe
2018-08-14T16:39:17Z [INFO] Creating root ecs cgroup: /ecs
2018-08-14T16:39:17Z [INFO] Creating cgroup /ecs
2018-08-14T16:39:17Z [WARN] Disabling TaskCPUMemLimit because agent is unabled to setup '/ecs' cgroup: cgroup create: unable to create controller: cgroups: cgroup mountpoint does not exist
2018-08-14T16:39:17Z [INFO] Loading state! module="statemanager"
2018-08-14T16:39:17Z [INFO] Event stream ContainerChange start listening...
2018-08-14T16:39:17Z [WARN] Udev watcher reconciliation: unable to send state change: udev watcher send ENI state change: eni not managed by ecs: 0a:48:c5:a7:cd:46
2018-08-14T16:39:17Z [WARN] Udev watcher reconciliation: unable to send state change: udev watcher send ENI state change: eni not managed by ecs: 0a:cb:14:53:fd:d6
```

### Expected Behavior
ecs-agent should clean up ENI's by querying the ECS service, not only relying on it's state file.

### Observed Behavior
ecs-agent doesn't clean up ENI's all the time

### Environment Details
* Docker Version: 1.18.0-ce
* ecs-agent: 1.20.0

### Supporting Log Snippets

TBD

**Comment by adnxn** [comment] 2018-08-16 03:28
> Looking for some help figuring out how to debug this, and or if it's something I should just expect to happen, and kill instances when this occurs.

1. Do you find this is reliably reproducible? Or do instances end up in this state seemingly randomly?

```
2018-08-14T16:31:48Z [CRITICAL] Could not unmarshal existing state; corrupted data? module="statemanager" err="unexpected end of JSON input" data="[]"
2018-08-14T16:31:48Z [CRITICAL] Error loading previously saved state: unexpected end of JSON input
```
2. Given the log snippet provided above - Do instances end up in this state paired with these specific log lines?

**Comment by dshmelev** [comment] 2018-08-20 12:27
I've a similar problem on official AMI (amzn-ami-2018.03.a-amazon-ecs-optimized (ami-c91624b0)). 
I updated container tag in task definition and caught the error `[WARN] Udev watcher reconciliation: unable to send state change: udev watcher send ENI state change: eni not managed by ecs`. New task does not start and containers hang "PENDING"..
ECS agent logs:
```
2018-08-20T11:04:30Z [INFO] Managed task [arn:aws:ecs:eu-west-1:172801717669:task/9d9663ad-e43d-4a04-8ef7-22b83b7ae68e]: task at steady state: RUNNING
2018-08-20T11:04:30Z [INFO] Managed task [arn:aws:ecs:eu-west-1:172801717669:task/9d9663ad-e43d-4a04-8ef7-22b83b7ae68e]: redundant container state change. aws-cli to STOPPED, but already STOPPED
2018-08-20T11:04:30Z [INFO] Managed task [arn:aws:ecs:eu-west-1:172801717669:task/9d9663ad-e43d-4a04-8ef7-22b83b7ae68e]: task at steady state: RUNNING
2018-08-20T11:04:30Z [INFO] Managed task [arn:aws:ecs:eu-west-1:172801717669:task/9d9663ad-e43d-4a04-8ef7-22b83b7ae68e]: redundant container state change. zabbix-agent to RUNNING, but already RUNNING
2018-08-20T11:04:30Z [INFO] Managed task [arn:aws:ecs:eu-west-1:172801717669:task/9d9663ad-e43d-4a04-8ef7-22b83b7ae68e]: task at steady state: RUNNING
2018-08-20T11:04:30Z [INFO] Managed task [arn:aws:ecs:eu-west-1:172801717669:task/9d9663ad-e43d-4a04-8ef7-22b83b7ae68e]: redundant container state change. telegraf to RUNNING, but already RUNNING
2018-08-20T11:04:30Z [INFO] Managed task [arn:aws:ecs:eu-west-1:172801717669:task/9d9663ad-e43d-4a04-8ef7-22b83b7ae68e]: task at steady state: RUNNING
2018-08-20T11:04:30Z [INFO] Managed task [arn:aws:ecs:eu-west-1:172801717669:task/9d9663ad-e43d-4a04-8ef7-22b83b7ae68e]: redundant container state change. ~internal~ecs-emptyvolume-source to STOPPED, but
already STOPPED
2018-08-20T11:04:30Z [INFO] Managed task [arn:aws:ecs:eu-west-1:172801717669:task/9d9663ad-e43d-4a04-8ef7-22b83b7ae68e]: task at steady state: RUNNING
2018-08-20T11:04:32Z [INFO] Duplicate ENI attachment message for ENI with MAC address: 06:90:c8:4a:ce:da
2018-08-20T11:04:36Z [INFO] Saving state! module="statemanager"
2018-08-20T11:05:56Z [WARN] Udev watcher event-handler: unable to send state change: udev watcher send ENI state change: timed out waiting for eni '06:b7:0b:15:53:a4' in state: context deadline exceeded
2018-08-20T11:06:15Z [WARN] Udev watcher reconciliation: unable to send state change: udev watcher send ENI state change: eni not managed by ecs: 06:b7:0b:15:53:a4
2018-08-20T11:06:19Z [INFO] Timed out waiting for ENI ack; removing ENI attachment record with MAC address: 06:90:c8:4a:ce:da
2018-08-20T11:06:20Z [INFO] Starting ENI ack timer with duration=2m59.999992186s, ENI Attachment: task=arn:aws:ecs:eu-west-1:172801717669:task/30d2d15f-e226-4d72-b472-2d943dabb02f;attachment=arn:aws:ecs:e
u-west-1:172801717669:attachment/2c311f00-7a42-498f-8521-5e6c7be4cd21;attachmentSent=false;mac=06:90:c8:4a:ce:da;status=NONE;expiresAt=2018-08-20 11:09:20.188181163 +0000 UTC m=+2425264.796064574
2018-08-20T11:06:20Z [INFO] Adding eni info for task 'arn:aws:ecs:eu-west-1:172801717669:task/30d2d15f-e226-4d72-b472-2d943dabb02f' to state, attachment=arn:aws:ecs:eu-west-1:172801717669:attachment/2c311
f00-7a42-498f-8521-5e6c7be4cd21 mac=06:90:c8:4a:ce:da
2018-08-20T11:06:20Z [INFO] Saving state! module="statemanager"
2018-08-20T11:06:45Z [WARN] Udev watcher reconciliation: unable to send state change: udev watcher send ENI state change: eni not managed by ecs: 06:b7:0b:15:53:a4
2018-08-20T11:07:15Z [WARN] Udev watcher reconciliation: unable to send state change: udev watcher send ENI state change: eni not managed by ecs: 06:b7:0b:15:53:a4
2018-08-20T11:07:35Z [INFO] Starting ENI ack timer with duration=2m59.999990282s, ENI Attachment: task=arn:aws:ecs:eu-west-1:172801717669:task/7dce10ee-19a5-4da3-945d-6c76df183cc5;attachment=arn:aws:ecs:e
u-west-1:172801717669:attachment/fa1fe78b-abcf-4bd9-b0ba-6e4a6594b129;attachmentSent=false;mac=06:d5:69:fd:c6:aa;status=NONE;expiresAt=2018-08-20 11:10:35.037567223 +0000 UTC m=+2425339.645450592
2018-08-20T11:07:35Z [INFO] Adding eni info for task 'arn:aws:ecs:eu-west-1:172801717669:task/7dce10ee-19a5-4da3-945d-6c76df183cc5' to state, attachment=arn:aws:ecs:eu-west-1:172801717669:attachment/fa1fe
78b-abcf-4bd9-b0ba-6e4a6594b129 mac=06:d5:69:fd:c6:aa
2018-08-20T11:07:35Z [INFO] Saving state! module="statemanager"
2018-08-20T11:07:45Z [WARN] Udev watcher reconciliation: unable to send state change: udev watcher send ENI state change: eni not managed by ecs: 06:b7:0b:15:53:a4
2018-08-20T11:08:15Z [WARN] Udev watcher reconciliation: unable to send state change: udev watcher send ENI state change: eni not managed by ecs: 06:b7:0b:15:53:a4
2018-08-20T11:08:45Z [WARN] Udev watcher reconciliation: unable to send state change: udev watcher send ENI state change: eni not managed by ecs: 06:b7:0b:15:53:a4
2018-08-20T11:09:04Z [INFO] TCS Websocket connection closed for a valid reason
2018-08-20T11:09:04Z [INFO] Connected to TCS endpoint
2018-08-20T11:09:15Z [WARN] Udev watcher reconciliation: unable to send state change: udev watcher send ENI state change: eni not managed by ecs: 06:b7:0b:15:53:a4
2018-08-20T11:09:20Z [INFO] Timed out waiting for ENI ack; removing ENI attachment record with MAC address: 06:90:c8:4a:ce:da
```

**Comment by richardpen** [comment] 2018-08-20 18:31
@packplusplus @dshmelev The message "eni not managed by ecs xxx" is expected if you are using the [task networking](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-networking.html) feature. The agent is periodically going through all the interface on the instance to make sure the ENI of the `awsvpc` mode task is attached, this message was generated for all the interfaces it detected that are not attached for the task, eg: container veth interface, default eni.

@packplusplus If you are running into the problem of the state file corruption, can you provide the information requested by @adnxn?

@dshmelev From the logs " Timed out waiting for ENI ack", it seems that the ENI wasn't successfully attached to the instance. How frequent is this happening? Did you try to replace this instance?

**Comment by dshmelev** [comment] 2018-08-20 18:43
Hello @richardpen.
I don't see this interface (06:b7:0b:15:53:a4) in web console. But I see this on instance. And I believe, this is old ENI.
```dev93     Link encap:Ethernet  HWaddr 06:B7:0B:15:53:A4
          BROADCAST MULTICAST  MTU:9001  Metric:1
          RX packets:1317328541 errors:0 dropped:0 overruns:0 frame:0
          TX packets:964469895 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1676036791633 (1.5 TiB)  TX bytes:4486910200258 (4.0 TiB)```

BTW I see my VPC interface `06:90:c8:4a:ce:da` in web console. This interface  is attached to my instance successfully.

**Comment by richardpen** [comment] 2018-08-20 20:26
@dshmelev From what I can see in the logs, `06:b7:0b:15:53:a4` is an ENI that was created for a `awsvpc` task, but it failed to attach to the instance within the duration, so the waiting for ENI attachemnt timed out and the task was moved to stopped, after that the ENI should be removed from the instance. If that's not the case you see, can you reach to the customer support and provide the following information:
* id of the task that statys in `pending`
* output of `ifconfig`
* the interface details(ifconfig interface_name) that you believe is the old ENI
* agent logs in `/var/logs/ecs`

Thanks,
Peng

**Comment by dshmelev** [comment] 2018-08-21 09:10
@richardpen I returned my instance to ECS cluster and now I see problem again.
ENI interface created and attached ok:
<img width="1096" alt="screenshot 2018-08-21 at 11 57 30" src="https://user-images.githubusercontent.com/184456/44391888-a1bc6f00-a539-11e8-933c-c83b57ccbde6.png">

But the task does not start (Last status: DEPROVISIONING (Timeout waiting for network interface provisioning to complete.)):
![image](https://user-images.githubusercontent.com/184456/44391989-d4fefe00-a539-11e8-8978-abe33463d40c.png)

Ifconfig output:
```
[root@ip-10-0-11-73 ~]# ifconfig -a
dev93     Link encap:Ethernet  HWaddr 06:B7:0B:15:53:A4
          BROADCAST MULTICAST  MTU:9001  Metric:1
          RX packets:1317328541 errors:0 dropped:0 overruns:0 frame:0
          TX packets:964469895 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1676036791633 (1.5 TiB)  TX bytes:4486910200258 (4.0 TiB)

docker0   Link encap:Ethernet  HWaddr 02:42:00:7F:6A:8E
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:ff:fe7f:6a8e/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:23818835 errors:0 dropped:0 overruns:0 frame:0
          TX packets:66861531 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:217972244110 (203.0 GiB)  TX bytes:3627939676 (3.3 GiB)

ecs-bridge Link encap:Ethernet  HWaddr A6:00:57:4F:5B:AD
          inet addr:169.254.172.1  Bcast:0.0.0.0  Mask:255.255.252.0
          inet6 addr: fe80::5cd6:17ff:fe34:5719/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2727 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2885 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:293949 (287.0 KiB)  TX bytes:1015276 (991.4 KiB)

eth0      Link encap:Ethernet  HWaddr 06:89:B1:49:B3:78
          inet addr:10.0.11.73  Bcast:10.0.11.255  Mask:255.255.255.0
          inet6 addr: fe80::489:b1ff:fe49:b378/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:1675322680 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1500780274 errors:0 dropped:89 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1579989023849 (1.4 TiB)  TX bytes:3028321942490 (2.7 TiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:21 errors:0 dropped:0 overruns:0 frame:0
          TX packets:21 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4037 (3.9 KiB)  TX bytes:4037 (3.9 KiB)

veth16b541b4 Link encap:Ethernet  HWaddr A6:00:57:4F:5B:AD
          inet6 addr: fe80::a400:57ff:fe4f:5bad/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:320 errors:0 dropped:0 overruns:0 frame:0
          TX packets:735 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:41041 (40.0 KiB)  TX bytes:149640 (146.1 KiB)
```

Agent logs:
```
[root@ip-10-0-11-73 ecs]# cat ecs-cni-eni-plugin.log
2018-08-20T11:02:54Z [INFO] Cleaned up dhclient for device(hardware address=06:b7:0b:15:53:a4): eth0
```
[ecs-agent.log](https://github.com/aws/amazon-ecs-agent/files/2305593/ecs-agent.log)

**Comment by richardpen** [comment] 2018-08-21 20:13
@dshmelev Thanks for providing the information, here is what I see from the log:
Task that uses the `eni-079ab568b8acb701d` was failed due to the "ENI Attachment timeout", this happened because for some reason the interface doesn't show up on the instance for 3mins after `ec2 attach` API was called. 

The confusion here is the status of the eni from the console, the "attached" shown in the console doesn't mean the interface is actually attached to the interface and ready for use. There is some delay for the interface to be setup and attach to the interface. We have saw some error if the instance is "unhealth", the interface will never show up on the instance even the console show the interface was attached to the instance. I'd suggest you replace this instance and see if the error persists on the new instance.

The interface `06:b7:0b:15:53:a4` is used by an old task which has already been stopped, and this interface should be detached from this instance. But for some reason, this interface wasn't removed from the instance, this may be another signal to indicate this is an "unhealthy" instance so the attach and detach doesn't work. I'd suggest you to replace this instance and see if this error persists.


Hope this answer your question, please let me know if you have other question.
Thanks,
Peng

**Comment by adnxn** [comment] 2018-10-24 00:50
> Hope this answer your question, please let me know if you have other question.

Closing this issue due to age. Please reopen if you have any new information.

**Closed by adnxn** 2018-10-24 00:50 UTC
Labels: more info needed
