### ISSUE TITLE
Missing container metadata file (v1.15.0)

### ISSUE THREAD

**Issue by bndw** [aws/amazon-ecs-agent#1051] opened 2017-11-03 17:16 UTC
### Summary
The container metadata fie is not being written for containers started by the ECS Agent.

### Description
After upgrading to `1.15.0` and enabling container metadata by running the agent with `ECS_ENABLE_CONTAINER_METADATA=true`, there are no metadata files being written to disk. 

The directories are created on the host at `/var/lib/ecs/data/metadata/task_id/container_name/`, however no files exist in these directories.

`ECS_CONTAINER_METADATA_FILE` is set inside the container and the directory is available at `/opt/ecs/metadata/random_ID/`, however no file exists.

### Expected Behavior
I expected to find an `ecs-container-metadata.json` file in the directories.

### Observed Behavior
There is no file

##### ECS Agent metadata
```json
{
  "Cluster": "foo",
  "ContainerInstanceArn": "arn:aws:ecs:us-east-2:ACCOUNT_ID:container-instance/807843bb-fa48-4359-80c9-4b2576ec8902",
  "Version": "Amazon ECS Agent - v1.15.0 (d2dd240)"
}
```

##### Docker info
```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.9.16-coreos-r1
Operating System: Container Linux by CoreOS 1298.7.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: ip-10-10-0-96.us-east-2.compute.internal
ID: xxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by samuelkarp** [comment] 2017-11-03 17:19
Since it looks like you're on Container Linux, can you provide the `docker run` command you're using to start the ECS agent?

It would also be helpful if you could provide logs for the ECS agent.  If you're not comfortable including those publicly, please email them to me at skarp at amazon.com.  Thanks!

**Comment by bndw** [comment] 2017-11-03 17:32
Logs sent via email. Here's my Docker run command (via Terraform formatted cloud-config)

```
/usr/bin/docker run --name ecs-agent \
    --network=host \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    --volume=/var/log/ecs:/log \
    --volume=/var/ecs-data:/data \
    --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
    --volume=/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro \
    --publish=0.0.0.0:51678:51678 \
    --env=ECS_LOGFILE=/log/ecs-agent.log \
    --env=ECS_LOGLEVEL=$${ECS_LOGLEVEL} \
    --env=ECS_DATADIR=/data \
    --env=ECS_CLUSTER=$${ECS_CLUSTER} \
    --env=ECS_AVAILABLE_LOGGING_DRIVERS='["awslogs"]' \
    --env=ECS_ENABLE_TASK_IAM_ROLE=true \
    --env=ECS_INSTANCE_ATTRIBUTES=$${ECS_INSTANCE_ATTRIBUTES} \
    --env=ECS_ENABLE_CONTAINER_METADATA=true \
    --log-driver=awslogs \
    --log-opt awslogs-region=${aws_region} \
    --log-opt awslogs-group=${ecs_log_group_name} \
    amazon/amazon-ecs-agent:$${ECS_VERSION}

```

**Comment by samuelkarp** [comment] 2017-11-03 18:07
Thanks.  Since you're mounting the agent data directory on the host as `/var/ecs-data`, you'll need to set `ECS_HOST_DATA_DIR=/var/ecs-data`.  By default, the agent assumes that the data directory is present on the host at `/var/lib/ecs/data` and that's what it's mounting into your containers.

There are a few other parameters you should be able to remove:

* `--publish=0.0.0.0:51678:51678` - Since you're running the agent with `--network=host` (which is what we recommend), you do not need to manually publish this port.
* `--volume=/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro` - The agent used to use this to help with metrics collection, but we switched to relying on `docker stats` around when Docker 1.12 came out.  This mount is no longer necessary.

Please let me know if this fixes it!

**Comment by bndw** [comment] 2017-11-03 18:50
I've set `ECS_HOST_DATA_DIR=/var/ecs-data` but I have the same issue. Here's an empty metadata directory for one of my running containers:

```
ls -lah /var/ecs-data/data/metadata/2386acbb-afce-4a15-b3e5-5de4148db5c1/nautilus
total 16K
drwxr-xr-x. 2 root root 4.0K Nov  3 18:13 .
drwxr-xr-x. 4 root root 4.0K Nov  3 18:13 ..
```

**Comment by samuelkarp** [comment] 2017-11-06 03:39
It looks like something is adding an extra `data/` into the path.  I reproduced what you're experiencing and you'll find the correct files written out into `/var/ecs-data/metadata`.  I'm looking to see where this is going wrong in the code.

**Comment by samuelkarp** [comment] 2017-11-06 03:51
The code as-written is really expecting the end of the host path to be equivalent to the container path for the data directory (e.g., it would expect `/var/ecs-data:/ecs-data`).  This is a bug, but to get around it for now you can change the container path of your mount to `/ecs-data` and then `ECS_DATADIR=/ecs-data` and `ECS_HOST_DATA_DIR=/var`.

So, like this:

```
--volume=/var/ecs-data:/ecs-data \
--env=ECS_DATADIR=/ecs-data \
--env=ECS_HOST_DATA_DIR=/var \
```

**Comment by bndw** [comment] 2017-11-07 22:13
@samuelkarp Thanks, that got me around the problem!

**Comment by bndw** [comment] 2017-11-07 22:26
@samuelkarp Upon further inspection I'm seeing unexpected port mappings in the data file.

Here I'm running a container that has been assigned port mapping `0.0.0.0:32769->80/tcp`

```sh
docker ps

CONTAINER ID        IMAGE                                                        COMMAND                  CREATED             STATUS              PORTS                       NAMES
50e4958241ad        xxx.dkr.ecr.us-east-2.amazonaws.com/xxx/streamline:latest    "/usr/local/bin/main"    10 minutes ago      Up 10 minutes       0.0.0.0:32769->80/tcp       ecs-streamline-6-streamline-de99e9d0cabdd3f88301
```

But the metadata file has unexpected PortMappings. I expected to see `HostPort= 32769`, but it's set to `0`

```json
{
	"Cluster": "xxx",
	"ContainerInstanceARN": "arn:aws:ecs:us-east-2:xxx:container-instance/dcc9fa0a-fba3-4a82-9159-210f7e693695",
	"TaskARN": "arn:aws:ecs:us-east-2:xxx:task/1af3eed7-97ac-4b80-95cf-66747138c5dd",
	"ContainerID": "50e4958241ad07299dbed24c4668f21ef6cf2f8500ad2f70cf86170e638ce802",
	"ContainerName": "streamline",
	"DockerContainerName": "/ecs-streamline-6-streamline-de99e9d0cabdd3f88301",
	"ImageID": "sha256:54e3d53df4f8e9920373efa0fc678e73c89b721985d9af8bb2add64b0770920f",
	"ImageName": "xxx.dkr.ecr.us-east-2.amazonaws.com/xxx/streamline:latest",
	"PortMappings": [
		{
			"ContainerPort": 80,
			"HostPort": 0,
			"BindIp": "",
			"Protocol": "tcp"
		}
	],
	"Networks": [
		{
			"NetworkMode": "default",
			"IPv4Addresses": [
				"172.17.0.3"
			]
		}
	],
	"MetadataFileStatus": "READY"
}
```

**Comment by samuelkarp** [comment] 2017-11-07 22:31
@bndw I think you're now running into https://github.com/aws/amazon-ecs-agent/issues/1052, which will be fixed by https://github.com/aws/amazon-ecs-agent/pull/1053.

**Comment by nmeyerhans** [comment] 2017-11-07 22:31
@bndw, you've run into #1052. Sorry for the inconvenience, but we've got a fix in the works...

**Comment by adnxn** [comment] 2017-11-17 21:12
closing since #1053 is included with 1.15.1 onwards

**Closed by adnxn** 2017-11-17 21:12 UTC
Labels: bug

**Comment by bndw** [comment] 2017-11-18 00:49
After update to 1.15.2 I no longer see container metadata files on the host, nor do I see the environment variables inside my containers. Has this changed?

**Comment by adnxn** [comment] 2017-11-18 03:23
@bndw The metadata feature has not changed with the 1.15.2 release. As a sanity check - is `ECS_ENABLE_CONTAINER_METADATA` enabled in the agent's ecs.config?

**Comment by bkdinoop** [comment] 2017-12-11 19:29
I too face the same issue with 1.16 i have enabled ECS_ENABLE_CONTAINER_METADATA in ecs.config and restarted the agent but metadata is not updated

In /var/lib/ecs/data/ecs_agent_data.json i can see "metadataFileUpdated": false
