### ISSUE TITLE
Running `make test-in-docker` fails on unexpected linker response.

### ISSUE THREAD

**Issue by adamjt** [aws/amazon-ecs-agent#142] opened 2015-07-22 01:12 UTC
On a fresh installation of Ubuntu 14.04.2 server, and with Docker version 1.7.1, running `make test-in-docker` fails on a single test defined [here](https://github.com/aws/amazon-ecs-agent/blob/a2fe6ba7e1dd58bcd518b8e91492f4630c067470/agent/engine/engine_integ_test.go#L543).

Truncated output:

```=== RUN TestLinking
2015-07-22T01:10:25Z [INFO] Pulling container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (NONE->RUNNING),netcat (NONE->RUNNING),]" container="linkee-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (NONE->RUNNING)"
2015-07-22T01:10:25Z [INFO] Redundant status change; ignoring module="TaskEngine" task="testDynamicPortForward2-1 testDynamicPortForward2, Status: (STOPPED->STOPPED) Containers: [netcat (STOPPED->STOPPED),]" current="STOPPED" change="STOPPED"
2015-07-22T01:10:25Z [INFO] Redundant status change; ignoring module="TaskEngine" task="testDynamicPortForward2-1 testDynamicPortForward2, Status: (STOPPED->STOPPED) Containers: [netcat (STOPPED->STOPPED),]" current="STOPPED" change="STOPPED"
2015-07-22T01:10:29Z [INFO] Creating container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (PULLED->RUNNING),netcat (NONE->RUNNING),]" container="linkee-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (PULLED->RUNNING)"
2015-07-22T01:10:29Z [INFO] Created container successfully module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (PULLED->RUNNING),netcat (NONE->RUNNING),]" container="linkee-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (PULLED->RUNNING)"
2015-07-22T01:10:29Z [INFO] Redundant status change; ignoring module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (CREATED->RUNNING),netcat (NONE->RUNNING),]" current="CREATED" change="CREATED"
2015-07-22T01:10:29Z [INFO] Starting container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (CREATED->RUNNING),netcat (NONE->RUNNING),]" container="linkee-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (CREATED->RUNNING) - Exit: 0"
2015-07-22T01:10:29Z [INFO] Redundant status change; ignoring module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (NONE->RUNNING),]" current="RUNNING" change="RUNNING"
2015-07-22T01:10:29Z [INFO] Pulling container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (NONE->RUNNING),]" container="netcat-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (NONE->RUNNING)"
2015-07-22T01:10:33Z [INFO] Creating container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (PULLED->RUNNING),]" container="netcat-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (PULLED->RUNNING)"
2015-07-22T01:10:33Z [INFO] Created container successfully module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (PULLED->RUNNING),]" container="netcat-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (PULLED->RUNNING)"
2015-07-22T01:10:33Z [INFO] Starting container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (CREATED->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (CREATED->RUNNING),]" container="netcat-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (CREATED->RUNNING) - Exit: 0"
2015-07-22T01:10:33Z [INFO] Redundant status change; ignoring module="TaskEngine" task="TestLinking-1 TestLinking, Status: (CREATED->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (CREATED->RUNNING),]" current="CREATED" change="CREATED"
2015-07-22T01:10:33Z [INFO] Task change event module="TaskEngine" event="{TaskArn:TestLinking Status:3 Reason: SentStatus:NONE}"
2015-07-22T01:10:33Z [INFO] Redundant status change; ignoring module="TaskEngine" task="TestLinking-1 TestLinking, Status: (RUNNING->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (RUNNING->RUNNING),]" current="RUNNING" change="RUNNING"
2015-07-22T01:10:34Z [INFO] Stopping container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (RUNNING->STOPPED) Containers: [linkee (RUNNING->STOPPED),netcat (RUNNING->STOPPED),]" container="linkee-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (RUNNING->STOPPED) - Exit: 0"
2015-07-22T01:10:34Z [INFO] Stopping container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (RUNNING->STOPPED) Containers: [linkee (RUNNING->STOPPED),netcat (RUNNING->STOPPED),]" container="netcat-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (RUNNING->STOPPED) - Exit: 0"
2015-07-22T01:10:34Z [INFO] Redundant status change; ignoring module="TaskEngine" task="TestLinking-1 TestLinking, Status: (RUNNING->STOPPED) Containers: [linkee (RUNNING->STOPPED),netcat (STOPPED->STOPPED),]" current="STOPPED" change="STOPPED"
2015-07-22T01:10:34Z [INFO] Task change event module="TaskEngine" event="{TaskArn:TestLinking Status:4 Reason: SentStatus:NONE}"
--- FAIL: TestLinking (9.22s)
	engine_integ_test.go:583: Got response:  instead of 'hello linker'```

**Comment by euank** [comment] 2015-07-22 03:47
Thanks for the heads up. We've also experienced this test being flaky in newer versions of Docker as well.

I opened #143 which makes this test pass reliably for me with a new Docker version and, hopefully, works for you as well.

**Comment by adamjt** [comment] 2015-07-22 17:47
Thanks for the quick response! I'm seeing a new failure mode for this test after running with the new code:

```=== RUN TestLinking
2015-07-22T09:09:17Z [INFO] Pulling container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (NONE->RUNNING),netcat (NONE->RUNNING),]" container="linkee-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (NONE->RUNNING)"
2015-07-22T09:09:17Z [INFO] Redundant status change; ignoring module="TaskEngine" task="testDynamicPortForward2-1 testDynamicPortForward2, Status: (STOPPED->STOPPED) Containers: [netcat (STOPPED->STOPPED),]" current="STOPPED" change="STOPPED"
2015-07-22T09:09:17Z [INFO] Redundant status change; ignoring module="TaskEngine" task="testDynamicPortForward2-1 testDynamicPortForward2, Status: (STOPPED->STOPPED) Containers: [netcat (STOPPED->STOPPED),]" current="STOPPED" change="STOPPED"
2015-07-22T09:09:21Z [INFO] Creating container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (PULLED->RUNNING),netcat (NONE->RUNNING),]" container="linkee-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (PULLED->RUNNING)"
2015-07-22T09:09:21Z [INFO] Created container successfully module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (PULLED->RUNNING),netcat (NONE->RUNNING),]" container="linkee-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (PULLED->RUNNING)"
2015-07-22T09:09:21Z [INFO] Starting container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (CREATED->RUNNING),netcat (NONE->RUNNING),]" container="linkee-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (CREATED->RUNNING) - Exit: 0"
2015-07-22T09:09:21Z [INFO] Redundant status change; ignoring module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (CREATED->RUNNING),netcat (NONE->RUNNING),]" current="CREATED" change="CREATED"
2015-07-22T09:09:21Z [INFO] Redundant status change; ignoring module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (NONE->RUNNING),]" current="RUNNING" change="RUNNING"
2015-07-22T09:09:21Z [INFO] Pulling container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (NONE->RUNNING),]" container="netcat-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (NONE->RUNNING)"
2015-07-22T09:09:25Z [INFO] Creating container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (PULLED->RUNNING),]" container="netcat-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (PULLED->RUNNING)"
2015-07-22T09:09:25Z [INFO] Created container successfully module="TaskEngine" task="TestLinking-1 TestLinking, Status: (NONE->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (PULLED->RUNNING),]" container="netcat-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (PULLED->RUNNING)"
2015-07-22T09:09:25Z [INFO] Starting container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (CREATED->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (CREATED->RUNNING),]" container="netcat-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (CREATED->RUNNING) - Exit: 0"
2015-07-22T09:09:25Z [INFO] Redundant status change; ignoring module="TaskEngine" task="TestLinking-1 TestLinking, Status: (CREATED->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (CREATED->RUNNING),]" current="CREATED" change="CREATED"
2015-07-22T09:09:25Z [INFO] Task change event module="TaskEngine" event="{TaskArn:TestLinking Status:3 Reason: SentStatus:NONE}"
2015-07-22T09:09:25Z [INFO] Redundant status change; ignoring module="TaskEngine" task="TestLinking-1 TestLinking, Status: (RUNNING->RUNNING) Containers: [linkee (RUNNING->RUNNING),netcat (RUNNING->RUNNING),]" current="RUNNING" change="RUNNING"
2015-07-22T09:09:26Z [INFO] Stopping container module="TaskEngine" task="TestLinking-1 TestLinking, Status: (RUNNING->STOPPED) Containers: [linkee (STOPPED->STOPPED),netcat (RUNNING->STOPPED),]" container="netcat-127.0.0.1:51670/amazon/amazon-ecs-netkitten:latest (RUNNING->STOPPED) - Exit: 0"
2015-07-22T09:09:26Z [INFO] Task change event module="TaskEngine" event="{TaskArn:TestLinking Status:4 Reason: SentStatus:NONE}"
--- FAIL: TestLinking (9.30s)
	engine_integ_test.go:598: Retrying getting response from container; got nothing
	engine_integ_test.go:586: Error dialing simple containerdial tcp 127.0.0.1:24751: connection refused
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4d91b4]```

**Comment by euank** [comment] 2015-07-31 20:51
I've looked at this a bit more, but couldn't reproduce it on a fresh instance with `test-in-docker`... Does it still happen on `dev` and does it happen reliably for you?

**Comment by adamjt** [comment] 2015-07-31 20:53
I can only reproduce locally on an Ubuntu VM under Virtualbox on OS X. It seems to work elsewhere!

**Comment by euank** [comment] 2015-07-31 21:23
Strange (and strangely specific). I guess Docker's networking is behaving subtly differently there... I'd still like to figure this one out so I'll leave it open, but it's less critical certainly if it only happens in that configuration.

**Comment by adamjt** [comment] 2015-07-31 22:20
Sounds good to me. I've moved my testing to an EC2 instance, but will update this issue if I can figure any more out.

**Comment by samuelkarp** [comment] 2015-10-09 18:16
@adamjt I'm going to close this out for now.  If you're able to reproduce the failures again, we're happy to continue looking at it.

**Closed by samuelkarp** 2015-10-09 18:16 UTC
Labels: bug
