### ISSUE TITLE
Blocker: Stopped containers do not get deregistered from target groups -> serious routing issues

### ISSUE THREAD

**Issue by fabfuel** [aws/amazon-ecs-agent#500] opened 2016-08-19 09:15 UTC
If a container (with a dynamic port) stops, the task is correctly recognized as `STOPPED (Essential container in task exited)`, but the container does not get deregistered from the ELB target group.

To reproduce it, just stop a container via `docker stop` on the ECS instance or just press the task's `Stop` button in the Management console.

**Comment by fabfuel** [comment] 2016-08-24 07:27
Yesterday this turned out to a serious issue. 
It's a show stopper if you use dynamic ports:

I had to restart docker and the ECS agent after installing a monitoring client on a new ECS instance. 
Due to the docker restart, all containers were stopped. 
The ECS agent then started new tasks on the node. So far so good, BUT:

Docker (or the ECS agent) always seems to start with the same dynamic port and it is then incrementally increasing the dynamic port number for every additional container.

That led to **reusing a port which was already in use** before the restart.

And because the stopped containers are not removed from a target group, a previously registered target became healthy again. But the problem was: **Another application was now using this port**!

It also led to the same instance and port being registered in two different target groups.

And as a result, the Application ELB was sending traffic to Application B, although it was meant to be routed to Application A.

I will also contact business support regarding this issue.

Best
Fabian

**Comment by samuelkarp** [comment] 2016-08-26 15:59
@fabfuel Thank you for reporting this.  We have identified the cause and are working on a fix.  We will update this issue with more information once it becomes available.

**Comment by joelgerard** [comment] 2016-09-07 19:44
@samuelkarp Any update on this? This is a bug with extremely high severity.

**Comment by gabrielR0** [comment] 2016-09-13 08:48
+1 Since the unhealthy containers are not unregistered from Application load balancer we've reached the  limit of "Number of times a target can be registered per load balancer: 100"

**Comment by aaithal** [comment] 2016-09-20 15:51
Hi All,

We have recently deployed a fix that should fix this issue. Please reach out to us if you have any further questions/comments on this. Closing the issue for now.

Thanks,
Anirudh

**Closed by aaithal** 2016-09-20 15:51 UTC
Labels: bug

**Comment by shuangwu42** [comment] 2017-05-30 13:59
We have observed the same issue with the latest version 1.14.1. Are you sure it was fixed? Thank you!

**Comment by samuelkarp** [comment] 2017-05-31 18:20
@shuangwu42 Please open a new issue if you're experiencing problems.

**Comment by kwent** [comment] 2018-04-06 22:07
Same issue with the newly health check introduced on the task definition.

If the health check at the container level (through task definition) fail but the health check at the ELB level is succeeded. Target is marked are unhealthy at the ELB level but never unregistered.

**Comment by ryanpagel** [comment] 2018-11-21 18:02
We're also experiencing this issue using ECS Fargate 1.2.0.  We currently have an accumulation of unregistered targets in a target group. 

![image](https://user-images.githubusercontent.com/805791/48860010-42166f80-ed85-11e8-873b-c3c78ae3c377.png)

**Comment by vlobovikov** [comment] 2019-08-27 09:10
HI, we have the same problem: agent version: 1.30

![Bildschirmfoto 2019-08-27 um 11 09 43](https://user-images.githubusercontent.com/29395665/63757936-409d4900-c8bb-11e9-9a9f-cd534c3c463c.png)
