### ISSUE TITLE
Agent memory usage grows for large volumes of tasks

### ISSUE THREAD

**Issue by yumex93** [aws/amazon-ecs-agent#1946] opened 2019-03-18 17:09 UTC
### Summary
We have one customer observe the issue that when they have large volume of tasks, agent memory usage grows constantly.
 
To give more details, they are starting 40 short lived tasks per minute on instances with amzn-ami-2018.03.i-amazon-ecs-optimized(ap-northeast-1) ami. They find that these tasks consumes agent memory and the process size keeps growing. 

### Environment Details

* AMI: amzn-ami-2018.03.i-amazon-ecs-optimized
* Region: ap-northeast-1

**Comment by fenxiong** [comment] 2019-10-04 23:32
Based on the description, I suspect the memory growth might be caused by the fact that each task is only removed from memory after a wait time specified by `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION`, which is by default 3h. So when this default is used, the memory will grow when a lot of short lived tasks are launched in a short time. However can't say this for sure since we lack customer data on this. Closing since I don't see much we can do here.

**Closed by fenxiong** 2019-10-04 23:32 UTC
Labels: kind/enhancement
