### ISSUE TITLE
ECS agent slowly leaking memory and/or not returning it to the host system

### ISSUE THREAD

**Issue by toraora** [aws/amazon-ecs-agent#2865] opened 2021-05-12 01:04 UTC
### Summary
Our monitoring indicates that the ECS agent's memory usage grows unbounded over time. It eventually trips certain high-memory alert thresholds that we have set up for our servers.

### Description
The actual memory utilization of the services running on our ECS cluster is fairly constant. However, notice the upward trend of memory usage in the following graph:

![ecs-memory-leak-3](https://user-images.githubusercontent.com/5341921/117901007-4f8a8180-b27f-11eb-9591-ff517295d7ec.png)

Inspecting `top` on this host shows 16GB VIRT and 15.2GB RES for the agent process.

This trend exists in some, but not all, of the machines in our cluster:

![ecs-memory-leak-2](https://user-images.githubusercontent.com/5341921/117901074-73e65e00-b27f-11eb-9d17-73c5a0e929e2.png)

The agent is written in Go, so this may be caused by the runtime allocating heap space, garbage collecting, and then the operating system not reclaiming the memory: https://github.com/golang/go/issues/42330

We're not sure though, and some guidance on how to pull debug information (pprof doesn't seem to be enabled) would be great. One thing we can test is setting `GODEBUG=madvdontneed=1` to change the memory reclaiming behavior.

### Expected Behavior
Memory usage of ecs-agent stays constant

### Observed Behavior
Memory usage of ecs-agent grows over time 

### Environment Details
- c5.4xlarge (16 vCPU, 32GB memory)
- ECS-optimized Amazon Linux 2 AMI (kernel 4.14.225-169.362.amzn2.x86_64)
- ECS agent version v1.51.0 (5c821610)
- Docker version 19.03.13-ce

Agent configuration (set in userdata):
```
echo ECS_CLUSTER=${cluster_name} >> /etc/ecs/ecs.config
echo ECS_AVAILABLE_LOGGING_DRIVERS=[\"json-file\",\"syslog\",\"fluentd\"] >> /etc/ecs/ecs.config
echo ECS_DISABLE_IMAGE_CLEANUP=false >> /etc/ecs/ecs.config
echo ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=30m >> /etc/ecs/ecs.config
echo ECS_RESERVED_MEMORY=64 >> /etc/ecs/ecs.config
echo ECS_LOGLEVEL=info >> /etc/ecs/ecs.config
echo ECS_AGENT_HEALTHCHECK_HOST=127.0.0.1 >> /etc/ecs/ecs.config
```

**Comment by becryan** [comment] 2021-05-15 20:37
I have been seeing extremely high CPU usage (> 95%) and not dropping in one build compared to others in our system. The only difference between the two systems is the version of the ECS agent (with the 95% one being this version). This may explain things!

**Comment by sparrc** [comment] 2021-05-17 17:53
@toraora have you been able to test with setting `GODEBUG=madvdontneed=1`?

We haven't upgrade to golang 1.16 yet (which turns this setting on by default), but in some initial testing we did find the reported memory usage to be significantly lower.

**Comment by toraora** [comment] 2021-05-19 21:01
We have not; we deployed a cron that restarts the agent every day to avoid runaway memory usage.

This looks like it could be caused by BoltDB and its page caching behavior: https://github.com/boltdb/bolt/issues/253

Similar symptoms have been noticed and investigated in LXD: https://github.com/lxc/lxd/issues/5584

**Comment by sparrc** [comment] 2021-05-21 20:54
The boltdb issue you linked explicitly states that this is expected behavior: https://github.com/boltdb/bolt/issues/253#issuecomment-55622731 . Not sure if it is that exactly but it seems likely.

We can try to repro and see if setting `GODEBUG=madvdontneed=1` or using golang 1.16 solves the issue.

@toraora Are you actually seeing any OOM errors because of this? My understanding is that linux should have no issues reallocating this memory.

**Comment by toraora** [comment] 2021-05-21 23:58
I don't think this has caused OOMs, but we'll keep an eye out. We have generic high memory usage alerts across our fleet of servers that we may want to re-evaluate; this is actually stated as one of the reasons for [the change in Go 1.16](https://github.com/golang/go/issues/42330):

>  This generally leads to poor user experience, like confusing stats in top and other monitoring tools; and bad integration with management systems that respond to memory usage.

**Comment by sparrc** [comment] 2021-05-24 20:36
That makes sense, our next agent release will hopefully be built with golang 1.16.4, we'll let you know once it's ready.

**Comment by mssrivas** [comment] 2021-08-24 21:16
https://github.com/aws/amazon-ecs-agent/pull/2993 is being worked in to potential deal with this issue

**Comment by toraora** [comment] 2021-09-01 00:26
Hey,

Memory usage is measured via `top`, e.g.

`26448 root      20   0   21.6g  20.9g  10524 S   0.0 68.3   9852:57 agent`

- a rough ballpark for the number of started tasks per host per day is probably about 100
- each task definition consists of just two containers (the application itself and an Envoy sidecar) and a fixed set of about 20 environment variables
- we are using the fluentd log driver, but the agent itself just logs to /var/log
- network mode is mostly host, but we are experimenting with moving services to bridged networking

**Comment by stewartcampbell** [comment] 2021-10-18 10:27
We are seeing something similar, although our ECS instance has about 5 short running tasks executing every minute. As you can see below, the agent memory usage increases over time and needs to be reset to recover the memory.

![image](https://user-images.githubusercontent.com/78276883/137714143-b7cc94a2-d5ce-41f7-a241-df1fabaccee4.png)

**Comment by stewartcampbell** [comment] 2021-10-19 08:44
I have sent the .pprof file as requested. There is no runtime-stats.log file on the server.

**Comment by angelcar** [comment] 2021-10-19 16:38
Hi @stewartcampbell, I reviewed the memory profile you sent, but nothing stood out. Maybe the memory profile was taken too soon?

In your graph above, I see that the memory peaks in about 3 days time. Would you be able to get another memory profile after the agent has been running for 2 or 3 days? 

Also, could you confirm what version of the agent you're in, as well as the OS? it's odd that the `/var/log/ecs/runtime-stats.log` file is not there, if `ECS_ENABLE_RUNTIME_STATS` is true, then it should.

**Comment by stewartcampbell** [comment] 2021-10-21 15:54
Hi that's the email sent again. You can see below stats including IO & CPU are still creeping up. The server usage pattern over that time has not changed.

![image](https://user-images.githubusercontent.com/78276883/138313639-b612d50c-6460-44da-aea0-34d176fdcbe3.png)

Thanks.

**Comment by angelcar** [comment] 2021-10-21 22:33
Ack. Will take a deeper look, thank you!

**Comment by fenxiong** [comment] 2021-11-08 17:33
The fix has been released in ecs agent version [1.57.0](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.57.0). please upgrade to that version to resolve the issue.

closing the issue. feel free to let us know if the issue is not resolved after the upgrade.

**Closed by fenxiong** 2021-11-08 17:33 UTC
Labels: kind/bug, kind/tracking

**Comment by fr-herrteuer** [comment] 2022-09-06 06:49
@angelcar is this issue also happen in Amazon ECS-Optimized Amazon Linux AMI ?
currently we are using Amazon ECS-Optimized Amazon Linux AMI, of which ecs-agent is 1.51.0 and will not be update in new AMI

- Amazon ECS-Optimized Amazon Linux AMI  --> latest ami ecs-agent 1.51.0
- Amazon ECS-Optimized Amazon Linux 2 AMI  --> latest ami ecs-agent 1.62.2

reference:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-versions.html

**Comment by sparrc** [comment] 2022-09-06 17:04
hi @fr-herrteuer, this issue could still happen in the latest Amazon Linux AMI (AL1). It will be fixed in the latest AL2 AMI.

**Comment by fcirone** [comment] 2023-01-24 14:37
we are having a similuar issue with ECS Fargate Platform 1.4.0.
checking here https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform-linux-fargate.html
the last update was "November 5, 2020"

Could the same problem be affecting fargate containers?

**Comment by chienhanlin** [comment] 2023-05-04 23:38
Hello @fcirone , ECS Fargate Platform version 1.40 is managed by Fargate Agent, which is different from ECS Agent on EC2. To help ECS investigate the issue, please share more info and data, and send them to [ecs-agent-external@amazon.com](mailto:ecs-agent-external@amazon.com). Thank you.
