### ISSUE TITLE
Setting ECS_INSTANCE_ATTRIBUTES doesn't work correctly

### ISSUE THREAD

**Issue by PicoSushi** [aws/amazon-ecs-agent#2074] opened 2019-06-06 08:26 UTC
### Summary
To add ECS_INSTANCE_ATTRIBUTES to instance, I used argument as `--env=ECS_INSTANCE_ATTRIBUTES='{"com.amazonaws.ecs.capability.logging-driver.awslogs":"true"}'` on ecs-agent, but it didn't correctly add attribute to instance.

#### Service deployment fails
For some reasons, I need to use self-made AMI, and launch amazon-ecs-agent at auto scaling group's user_data. So, I created ECS cluster with my AMI and tried to deploy my service using ECS, but error occurred.

> service XXXX was unable to place a task because no container instance met all of its requirements. The closest matching container-instance xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx is missing an attribute required by your task. For more information, see the Troubleshooting section.

#### Checking attribute difference
So, I compared instance attributes between official one (created via ECS's console, using `amzn-ami-*.h-amazon-ecs-optimized` AMI) and my instance, using below command.

`aws ecs describe-container-instances --cluster "${PROJECT}-${SERVER_ENV}" --container-instances "arn:aws:ecs:ap-northeast-1:XXXXXX:container-instance/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" --query 'containerInstances[0].attributes'`

And the diff result is that, official one has attribute as ` {"name": "ecs.capability.execution-role-awslogs"},` . So, I add `ECS_INSTANCE_ATTRIBUTES` on launching ecs-agent.

current ecs-agent running command:
```
docker run \
       --name ecs-agent \
       --detach=true \
       --restart=always \
       --volume=/var/run/docker.sock:/var/run/docker.sock \
       --volume=/var/log/ecs/:/log \
       --volume=/var/lib/ecs/data:/data \
       --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
       --volume=/var/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro \
       --publish=127.0.0.1:51678:51678 \
       --env=ECS_LOGFILE=/log/ecs-agent.log \
       --env=ECS_LOGLEVEL=info \
       --env=ECS_DATADIR=/data \
       --env=ECS_CLUSTER="${project}-${server_env}" \
       --env=ECS_INSTANCE_ATTRIBUTES='{"com.amazonaws.ecs.capability.logging-driver.awslogs":"true"}' \
       amazon/amazon-ecs-agent:latest
```

#### Result
As a result, on first launch in newly created instance ECS's deployment worked well. But, after ecs-agent dies and restarts, ECS can't deploy service to the instance with the restarted ecs-agent anymore. Does this not work after ecs-agent's restart? Or, my solution is wrong completely?

### Expected Behavior
-  Add `"name": "ecs.capability.execution-role-awslogs"` to ECS instance attribute.
- Be able to deploy service even after ecs-agent's restart.
- I can deploy service anytime, as many as I want.

### Observed Behavior
-  Add `"name": "ecs.capability.execution-role-awslogs"` to ECS instance attribute.
- Can't deploy service after ecs-agent's restart.
- I can't deploy service. But, immediately after instance's launch, I can deploy service.

### Environment Details
- docker info (on ECS instance)
```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1039-aws
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.91GiB
Name: ip-10-0-42-236
ID: GI7X:UU54:LC3P:ITSK:O2JN:KOID:Z6UR:2WBK:MAJ5:FEAG:VSM3:KKAP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```
- curl
`{"Cluster":"XXXXXXXX","ContainerInstanceArn":"arn:aws:ecs:ap-northeast-1:XXXXXXXX:container-instance/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","Version":"Amazon ECS Agent - v1.28.0 (d2456beb)"}`
- df -h
```
Filesystem      Size  Used Avail Use% Mounted on
udev            967M     0  967M   0% /dev
tmpfs           196M  944K  195M   1% /run
/dev/nvme0n1p1   30G  5.0G   25G  17% /
tmpfs           978M     0  978M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           978M     0  978M   0% /sys/fs/cgroup
/dev/loop0       18M   18M     0 100% /snap/amazon-ssm-agent/1335
/dev/loop1       90M   90M     0 100% /snap/core/6818
/dev/loop2       89M   89M     0 100% /snap/core/6964
tmpfs           196M     0  196M   0% /run/user/1001
```

**Comment by petderek** [comment] 2019-06-06 15:11
`ECS_INSTANCE_ATTRIBUTES` is intended for custom attributes, and won't override attributes namespaced for aws/ecs.

To configure your instance for use with awslogs

```
# in /etc/ecs/ecs.config
ECS_AVAILABLE_LOGGING_DRIVERS=["awslogs"]
```

[More documentation is available here.](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html)

Please let us know if this doesn't resolve the issue.

**Comment by PicoSushi** [comment] 2019-06-07 02:47
Hmm, I set `ECS_AVAILABLE_LOGGING_DRIVERS=["awslogs"]` in /etc/ecs/ecs.config, but newly created instance had attribute as `"name": "com.amazonaws.ecs.capability.logging-driver.none"` and no `"com.amazonaws.ecs.capability.logging-driver.awslogs"`. Why?

**Comment by petderek** [comment] 2019-06-07 18:18
> Why?

That’s a great question — it should work. We can reproduce this behavior on our end as well. It looks like there’s a bug if you only provide one log configuration option. I’ll have to explore this a bit more.

We will need to fix that behavior. The config below, on the other hand, worked for us. You could use this in the mean time.
 
```
ECS_AVAILABLE_LOGGING_DRIVERS=[“awslogs”,”none”]
```

**Comment by yunhee-l** [comment] 2019-06-07 21:45
Sorry @PicoSushi there's been a bit of miscommunication. 
We have tried reproducing this error and have not been able to see the same issue. 
How are you setting the ECS_AVAILABLE_LOGGING_DRIVERS value in ecs.config? Are you doing this in a new instance through userdata, or updating it on already-running instance? Did you restart the instance if it was the latter?

**Comment by PicoSushi** [comment] 2019-06-10 01:59
@yunhee-l 
I'm running ecs-agent in userdata on newly created instance. And, `ecs.config` is put when making AMI, using packer.

**Comment by yunhee-l** [comment] 2019-06-10 16:31
could you please send the following things to yhlee _at_ amazon _dot_ com?
- ecs.config you are using
- debug level agent log 
- output of describe-container-instances call

**Comment by PicoSushi** [comment] 2019-06-13 09:51
@petderek I tried with `ECS_AVAILABLE_LOGGING_DRIVERS=[“awslogs”,”none”]`, but the problem not solved. Oddly, new attribute added: `com.amazonaws.ecs.capability.logging-driver.json-file` .

@yunhee-l I sent mail. But, no log file found. I specified `ECS_LOGLEVEL=debug` and `ECS_LOGFILE=/log/ecs-agent.log`,  mount host's `/var/log/ecs/` to guest's `/log` (as my first comment) and checked host's `/var/log/ecs` and nothing found.

**Comment by petderek** [comment] 2019-06-17 17:17
Looking through this again, it looks like the ecs config volume isn't shared from the agent start script you provided:

`--volume=/etc/ecs:/etc/ecs \`

**Comment by PicoSushi** [comment] 2019-06-18 03:38
@petderek Hmm, that's right. But, I added that parameter and created new instance with the user data, but I couldn't find neither `com.amazonaws.ecs.capability.logging-driver.json-file` nor `com.amazonaws.ecs.capability.logging-driver.awslogs`. And, there're nothing at `/var/log/ecs`, too.

**Comment by PicoSushi** [comment] 2019-06-18 03:58
NOTE: `/etc/ecs/ecs.config` is correctly placed when making AMI and exists on launched instance. Also,  `/var/log/ecs` exists, but blank.

**Comment by petderek** [comment] 2019-06-19 18:27
So I'm wondering if something is preventing the config file from being visible within the agent container? That has its own set of downsides, but a way you can rule that out is by adding the logging drivers as an environment variable:

`--env=ECS_AVAILABLE_LOGGING_DRIVERS='["awslogs","json-file","none"]'`

**Comment by PicoSushi** [comment] 2019-07-02 09:35
@petderek It worked. Current ecs-agent running userdata:
```
docker run \
       --name ecs-agent \
       --detach=true \
       --restart=always \
       --volume=/etc/ecs:/etc/ecs \
       --volume=/var/run/docker.sock:/var/run/docker.sock \
       --volume=/var/log/ecs/:/log \
       --volume=/var/lib/ecs/data:/data \
       --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
       --volume=/var/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro \
       --publish=127.0.0.1:51678:51678 \
       --env=ECS_LOGLEVEL=info \
       --env=ECS_CLUSTER="${project}-${server_env}" \
       --env=ECS_AVAILABLE_LOGGING_DRIVERS='["awslogs","json-file","none"]' \
       amazon/amazon-ecs-agent:latest
```
I wonder why `ecs.config` isn't load correctly... But this workaround works.

**Comment by sharanyad** [comment] 2019-07-08 22:12
Closing this issue for now. Please feel free to reopen if it persists.

**Closed by sharanyad** 2019-07-08 22:12 UTC
