### ISSUE TITLE
Log level ignored

### ISSUE THREAD

**Issue by barakseri1** [aws/amazon-ecs-agent#2617] opened 2020-09-06 08:32 UTC
### Summary

The ECS config file contains the flag ECS_LOGLEVEL=crit, yet the logs produce trace and debug output.

### Description

Inspecting the container shows that it received the ECS_LOGLEVEL env variable.
The issue started on 1.44.3. 
I am also running containers with older versions where the issue does not occur

### Expected Behavior
ecs-agent container prints crit level errors

### Observed Behavior
ecs-agent container prints trace/debug level

### Environment Details
AMI amzn2-ami-ecs-hvm-2.0.20200905-x86_64-ebs

### Supporting Log Snippets

1599195704811683347 [Debug] No container health metrics to report
1599195704817436771 [Debug] Received message of type: AckPublishMetric
1599195704817460131 [Trace] TCS activity occurred
1599195704817474306 [Debug] Received AckPublishMetric from tcs

**Comment by fierlion** [comment] 2020-09-08 22:56
I'm working on a repro now:
on ECS optimized AMI with agent v  v1.39.0 I am able to set the log level down through `crit` and up through `debug` and can see filtered logs for each.

Testing with 1.44.3 now.

**Comment by fierlion** [comment] 2020-09-14 19:38
Please let me know if you have (or anyone reading this has) any more information on this issue that could help me repro what you're seeing.  
If I don't hear back in the next couple of days, I'll assume the issue is resolved.

**Comment by barakseri1** [comment] 2020-09-15 06:54
**Agent details**
```
[root@ip-172-30-2-49 ec2-user]# curl -s http://localhost:51678/v1/metadata
{"Cluster":"GSMS","ContainerInstanceArn":"arn:aws:ecs:us-east-1:934849693526:container-instance/9d5a3cfa-10eb-4c27-a896-4b3a699ad217","Version":"Amazon ECS Agent - v1.44.3 (33b647b8)"}
```

**Agent config**
```
[root@ip-172-30-2-49 ec2-user]# cat /etc/ecs/ecs.config
ECS_CLUSTER=GSMS
ECS_ENABLE_SPOT_INSTANCE_DRAINING=true
ECS_CONTAINER_STOP_TIMEOUT=300s
ECS_CONTAINER_START_TIMEOUT=5m
ECS_LOGLEVEL=crit
```

**Logs (after restarting the container)**
```
evel=info time=2020-09-15T06:50:04Z msg="Managed task [arn:aws:ecs:us-east-1:934849693526:task/43ac9a0f-2e55-4fab-88d6-a1c0e5e38590]: task has reached stopped. Waiting for container cleanup" module=task_manager.go
level=info time=2020-09-15T06:50:04Z msg="Managed task [arn:aws:ecs:us-east-1:934849693526:task/43ac9a0f-2e55-4fab-88d6-a1c0e5e38590]: waiting for event for task" module=task_manager.go
level=info time=2020-09-15T06:50:04Z msg="Managed task [arn:aws:ecs:us-east-1:934849693526:task/360634b3-5511-4c26-b92c-1e5dcc4c1aa6]: wait over; ready to move towards status: RUNNING" module=task_manager.go
level=info time=2020-09-15T06:50:04Z msg="Managed task [arn:aws:ecs:us-east-1:934849693526:task/360634b3-5511-4c26-b92c-1e5dcc4c1aa6]: task at steady state: RUNNING" module=task_manager.go
level=info time=2020-09-15T06:50:04Z msg="Managed task [arn:aws:ecs:us-east-1:934849693526:task/360634b3-5511-4c26-b92c-1e5dcc4c1aa6]: waiting for event for task" module=task_manager.go
level=info time=2020-09-15T06:50:04Z msg="Managed task [arn:aws:ecs:us-east-1:934849693526:task/a18c522b-5d62-43fd-850f-ff3dc9bb0111]: wait over; ready to move towards status: RUNNING" module=task_manager.go
level=info time=2020-09-15T06:50:04Z msg="Managed task [arn:aws:ecs:us-east-1:934849693526:task/a18c522b-5d62-43fd-850f-ff3dc9bb0111]: task at steady state: RUNNING" module=task_manager.go
level=info time=2020-09-15T06:50:04Z msg="Managed task [arn:aws:ecs:us-east-1:934849693526:task/a18c522b-5d62-43fd-850f-ff3dc9bb0111]: waiting for event for task" module=task_manager.go
level=info time=2020-09-15T06:50:04Z msg="DockerGoClient: Starting streaming metrics for container 25cdd49bf52f59bce0d720c478a9c7b30d92201b52c2466ec5413a4ca376c404" module=docker_client.go
...
```

**Comment by pin007** [comment] 2020-09-15 10:44
I'm experiencing the same issue, in my case `info` level is ignored:

**Agent metadata:**

```
# curl -s http://localhost:51678/v1/metadata
{"Cluster":"qa-platform","ContainerInstanceArn":"arn:aws:ecs:eu-west-1:563770389081:container-instance/868a628f-db45-46cd-b32d-20cb7e5610d4","Version":"Amazon ECS Agent - v1.44.3 (33b647b8)"}
```

**Agent configuration:**

```
ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","syslog","awslogs","none"]
ECS_AWSVPC_BLOCK_IMDS=true
ECS_CONTAINER_STOP_TIMEOUT=30s
ECS_CONTAINER_START_TIMEOUT=5m
ECS_DATADIR=/data
ECS_DISABLE_METRICS=false
ECS_ENABLE_SPOT_INSTANCE_DRAINING=true
ECS_ENABLE_TASK_CPU_MEM_LIMIT=true
ECS_ENABLE_TASK_ENI=true
ECS_ENABLE_TASK_IAM_ROLE=true
ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=3h
ECS_LOGLEVEL=info
ECS_POLL_METRICS=true
ECS_POLLING_METRICS_WAIT_DURATION=15s
ECS_RESERVED_MEMORY=512
ECS_VOLUME_PLUGIN_CAPABILITIES=["efsAuth"]
ECS_CLUSTER=qa-platform
```

**Logs:**

```
ecs-agent[1504]: 1600166247605763602 [Debug] Received message of type: AckPublishMetric
ecs-agent[1504]: 1600166247605790305 [Trace] TCS activity occurred
ecs-agent[1504]: 1600166247605801734 [Debug] Received AckPublishMetric from tcs
ecs-agent[1504]: 1600166247606826972 [Debug] Received message of type: AckPublishMetric
ecs-agent[1504]: 1600166247606846542 [Trace] TCS activity occurred
ecs-agent[1504]: 1600166247606856126 [Debug] Received AckPublishMetric from tcs
```

**Comment by pin007** [comment] 2020-09-15 10:46
I'm experiencing the same issue, in my case `info` level is ignored:

**Agent metadata:**

```
# curl -s http://localhost:51678/v1/metadata
{"Cluster":"qa-platform","ContainerInstanceArn":"arn:aws:ecs:eu-west-1:######:container-instance/868a628f-db45-46cd-b32d-20cb7e5610d4","Version":"Amazon ECS Agent - v1.44.3 (33b647b8)"}
```

**Agent configuration:**

```
ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","syslog","awslogs","none"]
ECS_AWSVPC_BLOCK_IMDS=true
ECS_CONTAINER_STOP_TIMEOUT=30s
ECS_CONTAINER_START_TIMEOUT=5m
ECS_DATADIR=/data
ECS_DISABLE_METRICS=false
ECS_ENABLE_SPOT_INSTANCE_DRAINING=true
ECS_ENABLE_TASK_CPU_MEM_LIMIT=true
ECS_ENABLE_TASK_ENI=true
ECS_ENABLE_TASK_IAM_ROLE=true
ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=3h
ECS_LOGLEVEL=info
ECS_POLL_METRICS=true
ECS_POLLING_METRICS_WAIT_DURATION=15s
ECS_RESERVED_MEMORY=512
ECS_VOLUME_PLUGIN_CAPABILITIES=["efsAuth"]
ECS_CLUSTER=qa-platform
```

**Logs:**

```
ecs-agent[1504]: 1600166247605763602 [Debug] Received message of type: AckPublishMetric
ecs-agent[1504]: 1600166247605790305 [Trace] TCS activity occurred
ecs-agent[1504]: 1600166247605801734 [Debug] Received AckPublishMetric from tcs
ecs-agent[1504]: 1600166247606826972 [Debug] Received message of type: AckPublishMetric
ecs-agent[1504]: 1600166247606846542 [Trace] TCS activity occurred
ecs-agent[1504]: 1600166247606856126 [Debug] Received AckPublishMetric from tcs
```

**Comment by fierlion** [comment] 2020-09-15 19:09
I'll need to ask for some more detailed steps and environment details to help me understand your scenarios

> after restarting the container
can you describe which container you restart and how you are restarting it?

I tested in the latest AL2 ECS-optimized AMI (ECS Agent v1.44.3)

this time I tried:
1. `ssh` onto the instance and rm the `/var/log/ecs/ecs-agent.log` file (so I know my change is having an effect)
2. update the /etc/ecs/ecs.config file to add `ECS_LOGLEVEL=crit`
3. `docker ps` to find the ECS Agent docker container ID
4. `docker kill <ECS Agent container ID>` (ECS Init will immediately restart the ECS Agent container and the new log level takes effect.)
5. I confirm this by `ls /var/log/ecs/`, noting that there is no ecs-agent.log file (since no crit log lines have been written)
6. I then update the /etc/ecs/ecs.config file to change `ECS_LOGLEVEL=info`
7. `docker ps` and `docker kill <ECS Agent container ID>` again.  The ECS Agent container is again immediately created.
8. `ls /var/log/ecs/` now shows an ecs-agent.log file with info level logs.

Please walk me through your steps to update the config and restart the ECS Agent.

**Comment by fierlion** [comment] 2020-09-21 19:53
If I don't hear back soon, I'll assume you were able to remedy the issue.
If anyone can help me with the details I've asked for, we'll be happy to look into what's going on here.
Otherwise I'll resolve this issue as no-repro.

**Comment by fierlion** [comment] 2020-09-22 14:35
closing -- please re-open if you experience this issue and can give detail on how your experience differed from those outlined in the repro steps above.

**Closed by fierlion** 2020-09-22 14:35 UTC
Labels: more info needed
