### ISSUE TITLE
Windows EC2 cluster ECS Task's container IP address gets reset after running successfully for an hour or so

### ISSUE THREAD

**Issue by tonetechnician** [aws/amazon-ecs-agent#3122] opened 2022-02-02 14:30 UTC
### Summary
When running an ECS task using an EC2 Windows cluster, the task starts and runs perfectly for about an hour or so. Shortly after that it's IP gets reset to a link address IP (169) and I'm unable to ping the gateway and gain access to services + the web. The ec2 instance runningthe container doesn't experience the same issue. The ec2 instance is also able to restart the task without an issue but the task is never able to keep it's IP address consistently.

<img width="1025" alt="Screenshot 2022-02-02 at 09 44 47" src="https://user-images.githubusercontent.com/13471797/152168963-5d5e39a3-c1e0-4de9-a791-456ec272303b.png">

<img width="562" alt="Screenshot 2022-02-02 at 10 40 27" src="https://user-images.githubusercontent.com/13471797/152168904-e43809b9-1145-4b1e-ad11-bea831690745.png">

#### Environment:

**Windows 2019 with ECS Container Support** - (ami amazon/Windows_Server-2019-English-Full-ECS_Optimized-2021.12.16)

```.ps1
PS C:\Users\Administrator> docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)
  registry: Manage Docker registries (Docker Inc., 0.1.0)

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 3
 Server Version: 20.10.7
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.2366)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.763GiB
 Name: EC2AMAZ-TQC1N7V
 ID: U5PP:2DXA:3ZEL:5K4Y:MTNB:MQG6:635Z:R5HU:OZWN:WXPB:SS6T:SVYF
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Task Definition. 

```.json
{
    "taskDefinitionArn": "arn:aws:ecs:us-east-2:000000000000:task-definition/pak-builder:34",
    "containerDefinitions": [
        {
            "name": "pak-builder",
            "image": "000000000000.dkr.ecr.us-east-2.amazonaws.com/image-registry:1.0.7",
            "cpu": 0,
            "memory": 2512,
            "portMappings": [
                {
                    "containerPort": 80,
                    "hostPort": 80,
                    "protocol": "tcp"
                },
                {
                    "containerPort": 8081,
                    "hostPort": 8081,
                    "protocol": "tcp"
                },
                {
                    "containerPort": 9092,
                    "hostPort": 9092,
                    "protocol": "tcp"
                }
            ],
            "essential": true,
            "entryPoint": [
                "powershell",
                "/start.ps1"
            ],
            "environment": [
            ],
            "mountPoints": [],
            "volumesFrom": [],
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "/ecs/unreal-packer",
                    "awslogs-region": "us-east-2",
                    "awslogs-stream-prefix": "ecs"
                }
            },
            "healthCheck": {
                "command": [
                    "CMD-SHELL",
                    "curl -f http://localhost:6050/health || exit 1"
                ],
                "interval": 10,
                "timeout": 2,
                "retries": 3,
                "startPeriod": 30
            }
        }
    ],
    "family": "pak-builder",
    "taskRoleArn": "arn:aws:iam::000000000000:role/task-role",
    "executionRoleArn": "arn:aws:iam::000000000000:role/task-role",
    "networkMode": "awsvpc",
    "revision": 34,
    "volumes": [],
    "status": "ACTIVE",
    "requiresAttributes": [
        {
            "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
        },
        {
            "name": "ecs.capability.execution-role-awslogs"
        },
        {
            "name": "com.amazonaws.ecs.capability.ecr-auth"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
        },
        {
            "name": "com.amazonaws.ecs.capability.task-iam-role"
        },
        {
            "name": "ecs.capability.container-health-check"
        },
        {
            "name": "ecs.capability.execution-role-ecr-pull"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
        },
        {
            "name": "ecs.capability.task-eni"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.29"
        }
    ],
    "placementConstraints": [],
    "compatibilities": [
        "EC2"
    ],
    "requiresCompatibilities": [
        "EC2"
    ],
    "memory": "2512",
    "registeredAt": "2022-02-02T08:25:50.507Z",
    "registeredBy": "arn:aws:iam::000000000000:user/User",
    "tags": [
    ]
}
```

### Expected Behavior

I expect the task to run consistently without losing it's ENI address. 

### Logs 

Logs from logs-collector.ps1

[collect.zip](https://github.com/aws/amazon-ecs-agent/files/7987295/collect.zip)

**Comment by fenxiong** [comment] 2022-02-08 18:09
hi,
thanks for submitting the issue. we will look into it

**Comment by karanvircu** [comment] 2022-02-09 18:43
We are observing the same behavior.
in summary 

We are running Windows containers on ECS with EC2 Container instances:

- Containers base image is `mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019`
- EC2 Container Instance is using ami-0157267592b210b1f (Windows_Server-2019-English-Full-ECS_Optimized-2022.01.18)
- Networking mode is awsvpc, with ENI trunking disabled on a m5.4xlarge instance.

Observed behavior:
After some time since the containers are started, the DHCP on the containers' ethernet adapter is set to "Disabled" and it gets a 169.254.50.x address. 


Currently, we can only get the expected DHCP/IP configuration, once we restart the container ( using Restart-computer from within the container) or stop and start the task.

**Comment by tonetechnician** [comment] 2022-02-09 19:03
@karanvircu 

I've found I've been able to workaround this issue by ensuring my container is communicating through the interface regularly - I've been successfully running my service for the past four days. 

For me, I provide this behaviour with the docker health check. I'm running an API service with a /health endpoint. The docker health check simply makes requests to the endpoint and then within the endpoint, I make a request to Google returning a 500 if I don't receive a response from Google.

I initially did this to ensure that the container restarted automatically but to my surprise, it has stopped the interface from being lost. 

Strange issue! But hopefully this helps you!

**Comment by jterry75** [comment] 2022-02-09 21:15
Thank you for the report and update. This is very odd indeed. I'm attempting to repro and will continue to look into this.

**Comment by jterry75** [comment] 2022-02-10 21:52
@tonetechnician - I have been unable to repro thus far so its unfortunately not something simple. Is this happening on multiple machines in your cluster or on just one machine? Is the host eni getting a different IP as well or just the container endpoint?

**Comment by karanvircu** [comment] 2022-02-17 19:27
Updates since my last [comment](https://github.com/aws/amazon-ecs-agent/issues/3122#issuecomment-1034079864). 

We switched to the ECS instance with AMI `Windows_Server-2019-English-Full-ECS_Optimized-2021.11.11` i.e with 
ECS Agent version `v1.57.0`. And our three windows containers have been running without any issues since last week.
Though with this version, we have lost the metrics(including container insights) which seems like were added as part of the [v1.57.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.57.1) release

We tried with the newest ECS agent version `v1.59.0`( ami - `Windows_Server-2019-English-Full-ECS_Optimized-2022.02.10`) and that seems to have the same problem aswell. 

@jterry75 I can confirm again with the second part of the question "Is the host eni getting a different IP as well or just the container endpoint?" in a day or two. But, what i recall from last time is that host eni does not seem to have any or at least the same issues as the container's eni.

**Comment by jterry75** [comment] 2022-02-23 16:49
Yea, I have still been unable to repro unfortunately. However, from the picture above and the reports I think that its just the container's ip that is getting reset. Still looking.

**Comment by tonetechnician** [comment] 2022-03-02 15:05
@jterry75 @karanvircu 

Just an update from my side. I've started to suspect this is a memory issue in the ec2 instance. 

After upping my ec2 instance to a c5.2xlarge instances, the tasks would run pretty consistently but every so often it would lose the eni. I also experienced issues with my cpp app where it would just crash in mid execution with no reasonable logs.  

I double checked my task definition and saw the memory limit was still set to 2000, I had originally thought this was a soft limit, but think it is most likely a hard limit. After pushing this up to the max the ec2 instance can support, I'm happy to say my task has been running without any issues! I still have my health check in place, so not sure if that is also contributing, but in my experience, out of memory issues can cause hard to debug errors, which makes me think it could well be the issue. 

@karanvircu do you have any memory limits set on your task?

**Comment by jterry75** [comment] 2022-03-02 22:39
Very interesting indeed. Did you by chance check if the host vnic was in the enabled state when your container experienced the oom or low memory state when it drops the ip? Can we rule out that the host vnic did not take over the ip? I will try a repro where I balloon the memory of the container to close to its limit and see if that causes any difference to the behavior.

**Comment by tonetechnician** [comment] 2022-03-03 06:47
Hey @jterry75 

I think I spoke too soon. I see that through the night my tasks have still been losing their eni and restarting. So not sure the out of memory is the root cause. 

> Did you by chance check if the host vnic was in the enabled state when your container experienced the oom or low memory state when it drops the ip? Can we rule out that the host vnic did not take over the ip?

No, I seem to remember when looking deeper into this it wasn't the case - but I will need to reconfirm. I will need to do some more monitoring and testing today!

I'm also just wondering if it's worth me sending you our image that you could test and reproduce with?

**Comment by tonetechnician** [comment] 2022-03-03 08:07
So here are some more screenshots which I hope will help you to see the issue. I started the task at 08:56:32, and the container eni is lost at 09:56:22. This behaviour is still very consistent.

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/13471797/156521427-25706c45-5f60-4f0a-a751-96d4ecf86644.png">

The host eni is still attached and it's ip remains the same:

<img width="591" alt="Screenshot 2022-03-03 at 09 22 07" src="https://user-images.githubusercontent.com/13471797/156521643-52148df9-1b32-4525-a926-dae2772ecc67.png">

The container adapter still exists, but the ip address is lost (ipconfig /all entered initially at container start and entered after the eni is lost):

<img width="931" alt="image" src="https://user-images.githubusercontent.com/13471797/156521812-c287d1ba-0d8e-45eb-b469-0cc3f8aead98.png">

On the host, the virtual adapter (Ethernet 4) is still listed here.

<img width="999" alt="image" src="https://user-images.githubusercontent.com/13471797/156522424-0f8074b8-815d-41c7-a260-9d3631f510c5.png">

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/13471797/156522030-1a871f2c-0ad4-4c33-8881-9b3dfd41340e.png">

However, it is no longer connected, here it also shows the hour long connectivity before stopping: 

<img width="365" alt="image" src="https://user-images.githubusercontent.com/13471797/156522075-747f746c-dc95-4db1-b14a-2aab5f8c2052.png">

<img width="810" alt="image" src="https://user-images.githubusercontent.com/13471797/156522503-0bfc5063-af9b-4365-a1c3-a6dee57a7367.png">

**Comment by rawahars** [comment] 2022-03-25 01:09
Hi @tonetechnician, Was the same behavior observed again?

**Comment by tonetechnician** [comment] 2022-03-25 06:32
Hey there @rawahars.

It has indeed, my team and I have been pressing on with the issue because we've been needing to get some demoes out. Including a health check and having the container restart has allowed us to move forward with the issue, but we will be going into a stability phase soon and then I intend to create a minimal image that reproduces the image that I can send to the AWS team for debug as ideally it shouldn't happen at all.

**Comment by tonetechnician** [comment] 2022-04-13 18:45
Hey @rawahars @jterry75 

Just an update here. I have a base image that is very simple but reproduces the issue. I have been able to reproduce my side consistently with this image. It implements a health check that checks whether the container can reach the outside web. 

Would it be possible to send it to you so you can check it out in your environment? I have a feeling it is to do with the size of the image, although could be wrong. I have been struggling to find a way to get logs from ecs that can give me more information on the problem so I'm hoping there could be more info on the AWS backend side. 

@karanvircu What size is the image that you guys are running and experiencing the same issue with?

**Comment by jterry75** [comment] 2022-04-14 20:17
@tonetechnician - That would be great. Could you please update the original ticket with information about how to access the image?

**Comment by tonetechnician** [comment] 2022-04-15 08:32
Thanks @jterry75 

I've logged a new ticket with request to send the image + task definition that reproduces the issue. Will feedback here once that's gone through.

**Comment by jterry75** [comment] 2022-04-15 15:52
Thank you. Will look today

**Comment by tonetechnician** [comment] 2022-04-15 18:01
Thanks @jterry75 

I'm not sure if my ticket went through. I submitted to the console home feedback page which I think is actually incorrect. Would you be able to provide a link that will create a ticket more directly with your team? 

Thanks!

**Comment by tonetechnician** [comment] 2022-04-15 18:10
Thanks @jterry75 

I realised I sent feedback to the wrong page. You should see it in the ECS feedback now. I'll wait to heare back so I can send the image + task definition.

**Comment by jterry75** [comment] 2022-04-18 19:01
@tonetechnician - Are you sure you sent it :)? I don't have any tickets in my queue from you. Can you ask them to assign it to Windows Containers?

**Comment by tonetechnician** [comment] 2022-04-18 19:17
Thanks for checking @jterry75 

Pretty sure I sent it. Although I didn't receive any confirmation email from aws :/ 

I used this feedback link, is it correct? 

<img width="684" alt="image" src="https://user-images.githubusercontent.com/13471797/163863139-e418c89a-7b84-4d6e-adc0-0e4002138055.png">

**Comment by tonetechnician** [comment] 2022-04-20 11:11
Hey @jterry75 

Just wanted to check if anything landed in your queue? 

Still not 100% sure my requests for support are going through.

**Comment by jterry75** [comment] 2022-04-20 17:46
Perfect will be on the lookout

**Comment by tonetechnician** [comment] 2022-04-21 07:40
Thanks, please let me know if you need anything more from me!

**Comment by jterry75** [comment] 2022-04-27 03:57
Hey sorry for the long response. We do have the ticket now as it has been forwarded to us. Will look tomorrow. Thank you!

**Comment by jterry75** [comment] 2022-06-07 17:29
@tonetechnician - Not sure if you have been updated by the support engineer or not so I thought that I would write it here as well. The fix for the issue I am hoping to get some guidance from Microsoft HNS folks here: https://github.com/microsoft/hcsshim/issues/1419. But what is happening is that when on the private subnet for your setup, for some reason the IPv4 address is getting a Valid/PerferredLifetime assigned at 1 hr when the workload container starts. After this 1hr since it is a Manual IPv4 assigned address (not DHCP) the IP expires and the Task ENI no longer has connectivity. The odd part is that when on a public subnet this does not happen and the IPv4 will have a lifetime of "Infinite" and thus it never expires. But what makes no sense at all is that in both cases we do not set the lifetime when creating the vNIC in the container network namespace. So this is some default behavior that is happening from Windows as far as I can tell. If the Microsoft folks can give me a way to force an infinite lifetime then I can fix this in the CNI really easy. 

For now, there are a few workarounds. The easiest is to find the IPv4 address for the task bridge adapter in the container and set is lifetime to Infinite via PS.

```
PS > Get-NetAdapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
vEthernet (nat-ep-43ec... Hyper-V Virtual Ethernet Adapter #4          27 Up           <MAC>        10 Gbps
vEthernet (taskbr02c5b... Hyper-V Virtual Ethernet Adapter #3          20 Up           <MAC>       25 Gbps
```

So in this case ifIndex `20` is the `taskbr*` adapter.

Then you can get the IPv4 addresses for this adapter:
```
Get-NetIPAddress -ifIndex 20

IPAddress         : <address>
InterfaceIndex    : 20
InterfaceAlias    : vEthernet (taskbr***)
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 16
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Preferred
ValidLifetime     : 00:56:00
PreferredLifetime : 00:56:00
SkipAsSource      : False
PolicyStore       : ActiveStore
```

Once you know the `<address>` you can update this lifetime to be Infinite

```
Set-NetIPAddress -InterfaceIndex 20 -IPAddress <address> -ValidLifetime [timespan]::MaxValue -PreferredLifetime [timespan]::MaxValue
```

Then it wont expire and you wont drop connectivity.

If you have an instance that has already lost connectivity and you want to reconnect it you can simply use the `Remove/Add-NetIPAddress` cmdlets to remove the `169.*` address as well as the originally assigned address and then add it back with the `Add` cmdlet. Once done you will get connectivity back on the instance since that IP was reserved by ECS for that container anyways.

**Comment by tonetechnician** [comment] 2022-06-16 09:20
Thanks @jterry75 for the investigation and figuring this out! It looks very promising. I'll try this out my side and see if it helps! I have already migrated the service to Nomad to mitigate the issue which has been working stably. Will try with ECS again though. 

Thanks!

**Closed** 2022-07-12 19:40 UTC
Labels: os/windows, kind/tracking

**Comment by rawahars** [comment] 2023-03-23 18:25
We have released a patch starting with March ECS optimized AMIs. This patch will ensure that the ENI's IP address is not reseted to the link-local IP address.

Please update your ECS Optimized AMIs to the latest version to ensure that the mitigation changes are applied.
More information about retrieving the latest ECS Windows AMIs can be found here- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/retrieve-ecs-optimized_windows_AMI.html
