### ISSUE TITLE
Zombie reaping: add support for `docker run --init`

### ISSUE THREAD

**Issue by jakecollins** [aws/amazon-ecs-agent#865] opened 2017-06-27 13:33 UTC
It seems that the zombie reaping problem can now be solved by using `docker run --init`. It would be useful to be able to start ECS containers using this option. 

https://docs.docker.com/engine/reference/commandline/run/#options

https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by nmeyerhans** [comment] 2017-06-27 21:21
Thanks. We agree that zombies should be reaped. I'm going to resolve this request, though, as it's a duplicate of #852

**Closed by nmeyerhans** 2017-06-27 21:21 UTC
