### ISSUE TITLE
ECS Exec Command Exit Code Ignored by AWS CLI

### ISSUE THREAD

**Issue by ATLJLawrie** [aws/amazon-ecs-agent#2846] opened 2021-04-14 22:56 UTC
### Summary
ECS Exec does not seem to pass through the exit code of command back to AWS CLI.

### Description
When attempting to use `aws ecs execute-command` to execute a command on an ECS container the commands return code doesn't pass back to the shell where the AWS CLI command was executed.

### Expected Behavior
```
> aws ecs execute-command --region us-east-1 --cluster fargate-esc-cluster --task <task_arn> --container ubuntu --command "ls /tmp/folderthatdoesntexist" --interactive


The Session Manager plugin was installed successfully. Use the AWS CLI to start a session.


Starting session with SessionId: ecs-execute-command-123
ls: cannot access '/tmp/folderthatdoesntexist': No such file or directory


Exiting session with sessionId: ecs-execute-command-123.

> echo $?
1
```
### Observed Behavior
```
> aws ecs execute-command --region us-east-1 --cluster fargate-esc-cluster --task <task_arn> --container ubuntu --command "ls /tmp/folderthatdoesntexist" --interactive


The Session Manager plugin was installed successfully. Use the AWS CLI to start a session.


Starting session with SessionId: ecs-execute-command-123
ls: cannot access '/tmp/folderthatdoesntexist': No such file or directory


Exiting session with sessionId: ecs-execute-command-123.

> echo $?
0
```
validating container side error code
```
> aws ecs execute-command --region us-east-1 --cluster fargate-esc-cluster --task <task_arn> --container ubuntu --command "sh -c 'ls -l /tmp/folderthatdoesntexist || echo $?'" --interactive


The Session Manager plugin was installed successfully. Use the AWS CLI to start a session.


Starting session with SessionId: ecs-execute-command-123
ls: cannot access '/tmp/folderthatdoesntexist': No such file or directory
130

Exiting session with sessionId: ecs-execute-command-123.
> echo $?
0

```
### Environment Details
Testing with ECS Fargate.  ECS Exec works great we are just trying to utilize the functionality in scripts and noticed that errors weren't stopping execution.

**Comment by chienhanlin** [comment] 2021-04-16 23:08
Hello @ATLJLawrie The exit code 0 is sent since the `aws ecs execute-command` command completed successfully on the host; therefore we don't see code 1 here. To fetch an error code of an unsuccessful command inside the container, some commands has to be executed inside the container.

Please find [AWS CLI Return Codes](https://docs.aws.amazon.com/cli/latest/topic/return-codes.html) in AWS CLI Command Reference for your reference. Thanks.

**Comment by fierlion** [comment] 2021-04-23 17:46
In this case the 0 exit code is the expected behavior for a successful `ecs execute-command` call.
The interactive exec session mostly follows the `ssm start-session` pattern https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ssm/start-session.html
It seems that your use case follows the `ssm run-command` pattern (see https://docs.aws.amazon.com/systems-manager/latest/userguide/command-exit-codes.html)  This `run-command` like functionality isn't currently supported by ecs execute-command.

So for now you might need to get creative.  For the `ls` example above, you can try:
```
aws ecs execute-command \
--region us-east-1 \
--cluster fargate-esc-cluster \
--task <task_arn> \
--container ubuntu 
--interactive 
--command "/bin/sh -c 'ls /tmp/folderthatdoesntexist && echo ok'" | grep ok
```
The overall `ecs execute-command | grep` call will return nothing for a non-existent directory, and return `ok` for an available directory.
This is just one (hacky!) way to surface the output of the specific call from the interactive session to your current shell session.

`ecs execute-command` is still pretty new and we're constantly working to make it better.

**Comment by fierlion** [comment] 2021-04-23 17:46
I'll close this issue for now.  Please re-open if you have more questions.

**Closed by fierlion** 2021-04-23 17:46 UTC

**Comment by blimmer** [comment] 2021-09-27 21:50
:+1: - I would love a way to see the exit code using `execute-command`. I wonder, when `--non-interactive` is enabled (right now I get a runtime error if I try to use that flag), will that enable seeing the exit code?

**Comment by jMac029** [comment] 2021-10-08 03:04
> 👍 - I would love a way to see the exit code using `execute-command`. I wonder, when `--non-interactive` is enabled (right now I get a runtime error if I try to use that flag), will that enable seeing the exit code?

I too would like to know when the `--non-interactive` feature will be enabled. Trying to run an `execute-command` in a pipeline as a stage in a deployment is to a command on a task and I get no output only: 

```
Migrate Script Output: The Session Manager plugin was installed successfully. Use the AWS CLI to start a session.


Starting session with SessionId: ecs-execute-command-0ec9d1fd4ce1f9b6d
Starting dependencies..
Cannot perform start session: EOF
```
It appears my script completes but would prefer to have the actual output from the script completing.

**Comment by jMac029** [comment] 2021-10-08 03:20
found a workaround for being able to run `execute-command` as part of a CI pipeline. Needed to use `unbuffer` to run the command with `tty` available. 

`unbuffer aws ecs execute-command ...`

https://github.com/aws/amazon-ssm-agent/issues/354#issuecomment-855470237

**Comment by jkribeiro** [comment] 2022-01-19 13:29
I don't think a hack/workaround is enough to close this issue. It seems to be an important feature/fix. 
Is it possible to know from the maintainers if this feature/fix is included in the ECS EXEC backlog?

Having command output is very common when using Docker exec. The same behaviour should be considered for ECS EXEC.
```
docker exec -it a sh -c 'exit 4'
echo $?
4
```

**Comment by trent-abc** [comment] 2022-09-07 21:20
@jkribeiro hit the nail on the head. It's not at all expected behaviour that because SSM connected successfully then the exit code should be 0.  At least add a flag like `--exit-with-command-status` or something similar to bubble up the error.

**Comment by RobinHoutevelts** [comment] 2023-04-07 09:01
> Please re-open if you have more questions.

@fierlion can we reopen this? Doing `&& echo ok'" | grep ok` is not a solution.
I prefer [a flag like `trent-abc` suggested.](https://github.com/aws/amazon-ecs-agent/issues/2846#issuecomment-1239899897)

**Comment by djdevin** [comment] 2023-06-21 16:28
Yes, please reopen this.

I was expecting ECS execute-command to have similar functionality to `kubectl exec`, `oc rsh` etc. but it is severely lacking and difficult to use with any CLI tools due to the lack of non-interactive mode and return values.

**Comment by sxarp** [comment] 2023-07-28 03:15
I'm doing like this to see the output:
```
$ aws ecs execute-command --interactive --command '/bin/sh -c "command_to_execute && echo command_successfully_finished"' | tee /dev/tty | grep "command_successfully_finished"
```

**Comment by bsramin** [comment] 2023-09-27 20:12
This issue absolutely needs to be reopened. The proposed solution is very far from being considered acceptable 😞

**Comment by bsramin** [comment] 2023-09-27 20:15
@fierlion can you re-open this issue? Thanks!

**Comment by fierlion** [comment] 2023-11-20 18:26
ECS Execute Command as designed is targeted at interactive debugging.  To a limited extent ECS Execute Command's design maps to SSM's [start-session](https://docs.aws.amazon.com/cli/latest/reference/ssm/start-session.html) API, vs SSM's [run-command](https://docs.aws.amazon.com/systems-manager/latest/userguide/run-command-handle-exit-status.html) API (which is meant for programmatic interactions).

Please feel free to add an issue to the [ECS Containers Roadmap](https://github.com/aws/containers-roadmap/issues?q=is%3Aissue+is%3Aopen+ecs+execute).  A quick look over the existing ECS Execute Command related issues didn't surface this particular issue.  

If you find an existing issue that meets your feature expectations, add a 👍 to it -- this roadmap is a primary mechanism for us as engineers to get feature requests prioritized.

**Comment by trent-abc** [comment] 2023-11-20 18:54
Created issue here - please 👍 https://github.com/aws/containers-roadmap/issues/2207

**Comment by denmely** [comment] 2025-02-05 21:47
I had a problem with php artisan migrate --database=api.


```sh
output=$(unbuffer aws ecs execute-command \
    --cluster test \
    --task xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx \
    --container api-test \
    --region us-east-1 \
    --command "php artisan migrate --database=api" \
    --interactive)
echo "$output"
if echo "$output" | grep -q "SQLSTATE\|FAIL\|error\|Exception"; then
  echo "Migration Failed"
fi
```
_Exiting session with sessionId: ecs-execute-command-8bfhkvekhlqrrlyjgxxxxxxxx.
Migration Failed_
