### ISSUE TITLE
Docker network settings breaks after upgrade from 1.15.2 to 1.6.1

### ISSUE THREAD

**Issue by jmetzmeier** [aws/amazon-ecs-agent#1169] opened 2018-01-08 23:07 UTC
### Description
After upgrading from ecs-agent 1.15.2 to 1.6.1 via moving to a new ECS-optimized Amazon Linux AMI, our proxy nginx containers, which use docker-gen, are no longer able to generate proper configurations. This appears to be due to a difference in the "NetworkSettings" key that is shown in docker inspect. Here is a comparison (unchanged task definitions):

1.15.2:

```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "a52888fd07828acb8c4804edfabc1911ceb0201401abb804de260b99ea2a2223",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32770"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/a52888fd0782",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "cca835da91ffe43b86a5dc0f5412e26e5ec4027ea4911e98305896c3076fa5af",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "4a26dd4ae7e798b01f3d182a7a216053949d1a99b978549ceb95cdee7fe1d2a5",
                    "EndpointID": "cca835da91ffe43b86a5dc0f5412e26e5ec4027ea4911e98305896c3076fa5af",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
```

1.6.1:

```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "3e4faad803214c9086142fbc85ae30b5a7076e8f4d6a850f0cd27d2c13072ca6",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/3e4faad80321",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "a210bf213d97310c6091c91206fc4b44a0151f85ceec0e7b572f370e37832368",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
```

In the 1.6.1 example, "IPAddress" and "Ports" is empty. The docker version is the same in both of these cases - 17.06.2-ce. 

### Expected Behavior
Our application doesn't break everytime we run `yum update`.

### Observed Behavior
Metadata changes from the different ecs-agent versions, resulting in docker-gen no longer functioning properly.

### Environment Details

[root@ip-172-31-22-121 ~]# docker info
Containers: 130
 Running: 4
 Paused: 0
 Stopped: 126
Images: 5
Server Version: 17.06.2-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: 
 Metadata file: 
 Data Space Used: 5.154GB
 Data Space Total: 23.33GB
 Data Space Available: 18.17GB
 Metadata Space Used: 8.176MB
 Metadata Space Total: 25.17MB
 Metadata Space Available: 16.99MB
 Thin Pool Minimum Free Space: 2.333GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.75-25.55.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86GiB
Name: ip-172-31-22-121
ID: APSP:VB4C:V4Q7:DKYG:TO6Q:VHEH:F4JC:GBWI:HXC7:TD65:IOHJ:AML3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by richardpen** [comment] 2018-01-09 00:07
@jmetzmeier I think the 1.6.1 you mentioned is the agent version 1.16.1, please correct me if I'm wrong. If the provided output is the raw docker inspect output, I'm suspecting that the container may not be in running status by the time `docker inspect` was called, can you confirm that? As most of the information under `NetworkSetting`  will only be available if the container is in running state.

If that's not the case, can you briefly describe the workflow of your task, is the docker-gen running inside a separate container or within the same container as nginx, when was docker-gen called?

**Comment by jmetzmeier** [comment] 2018-01-09 04:23
@richardpen Yes, sorry, it is agent version 1.16.1. You are correct, it appears the container was killed before I ran the `docker inspect`. Because the health checks are failing for this task, the containers are getting killed often.

We are using this project which contains nginx and docker-gen in the same container: https://github.com/jwilder/nginx-proxy

The reason it's no longer passing health checks is that the `upstream` block in the nginx config is not being completely written. It looks like this with 1.16.1:

```
upstream XXX.subtext.org {
}
```

With 1.15.2 it looks like this:

```
upstream XXX.subtext.org {
                                ## Can be connect with "bridge" network
                        # ecs-knotweed-qa-subtextUiTask-1HUGMFKKEOADI-1-subtext-ui-8af0a3d9a6a19abff201
                        server 172.17.0.2:3000;
}
```

The part of the template that generates the block looks like this:

```
upstream {{ $host }} {
{{ range $container := $containers }}
        {{ $addrLen := len $container.Addresses }}

        {{ range $knownNetwork := $CurrentContainer.Networks }}
                {{ range $containerNetwork := $container.Networks }}
                        {{ if eq $knownNetwork.Name $containerNetwork.Name }}
                                ## Can be connect with "{{ $containerNetwork.Name }}" network

                                {{/* If only 1 port exposed, use that */}}
                                {{ if eq $addrLen 1 }}
                                        {{ $address := index $container.Addresses 0 }}
                                        {{ template "upstream" (dict "Container" $container "Address" $address "Network" $containerNetwork) }}
                                {{/* If more than one port exposed, use the one matching VIRTUAL_PORT env var, falling back to standard web port 80 */}}
                                {{ else }}
                                        {{ $port := coalesce $container.Env.VIRTUAL_PORT "80" }}
                                        {{ $address := where $container.Addresses "Port" $port | first }}
                                        {{ template "upstream" (dict "Container" $container "Address" $address "Network" $containerNetwork) }}
                                {{ end }}
                        {{ end }}
                {{ end }}
        {{ end }}
{{ end }}
}
```

I did not make any modifications to the task definition.

**Comment by richardpen** [comment] 2018-01-10 00:03
@jmetzmeier Thanks for providing these details, I was able to reproduce on our side. After digging into the code of [docker-gen](https://github.com/jwilder/docker-gen), this is caused by the way docker-gen acquire the current container ID, the related code is [here](https://github.com/jwilder/docker-gen/blob/master/context.go#L162), it relies on the cgroup path of the container.

In ECS Agent 1.16.0 we added a new feature to enable task level resource limitation using cgroup, and the cgropu path of the container was modified to have the task id as a prefix, see detailed discussion in #1119. So in order to make it work you have to disable this feature by adding this line `ECS_ENABLE_TASK_CPU_MEM_LIMIT=false` in `/etc/ecs/ecs.config`, and restart the agent by `sudo stop ecs` and `sudo start ecs`. In this way the container cgroup path won't be modified, and docker-gen should be able to acquire the container ID.

Please let me know if that works for you.

Thanks,
Peng

**Comment by richardpen** [comment] 2018-01-10 00:05
Closing this issue, as this is duplicate of #1119, feel free to ask in that issue.

**Closed by richardpen** 2018-01-10 00:05 UTC

**Comment by jmetzmeier** [comment] 2018-01-10 15:49
@richardpen Thanks for the investigation.

**Comment by dancingfrog** [comment] 2018-02-27 20:48
@jmetzmeier @richardpen Thank you! Big save!
