### ISSUE TITLE
Agent fail to start: failed to make EC2Metadata request

### ISSUE THREAD

**Issue by Bragrel** [aws/amazon-ecs-agent#2329] opened 2020-01-07 14:37 UTC
### Summary

I'm attempting to add instances to existing cluster. Instances can't join the cluster. 

### Description

AMIs:
- amzn2-ami-ecs-hvm-2.0.20190815-x86_64-ebs (ami-0b16d80945b1a9c7d)
- amzn2-ami-ecs-hvm-2.0.20191212-x86_64-ebs (ami-00afc256a955c31b5)

Probably related issue: https://github.com/aws/amazon-ecs-agent/issues/1857

### Expected Behavior
Instances can join cluster. 

### Observed Behavior
In ecs agent logs I've found following:
```
2020-01-07T14:13:53Z [ERROR] Unable to register as a container instance with ECS: RequestError: send request failed
caused by: Post https://ecs.us-east-1.amazonaws.com/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020-01-07T14:13:53Z [ERROR] Error registering: RequestError: send request failed
```

After ecs agent update, I found following in logs:
```
2020-01-07T14:17:25Z [WARN] Unable to obtain Outpost ARN from EC2 Metadata: EC2MetadataError: failed to make EC2Metadata request
caused by: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>
```

### Environment Details

Instances are in private subnet with route to NAT Gateway. Outbound traffic allowed (instances can reach internet).
Setup was working as intended for some time.

### Supporting Log Snippets

ecs-logs-collector:
[Before ecs agent update](https://drive.google.com/open?id=11IJD5qCp2Wfrn09maKB_NAR4m5sRCmnv)
[After ecs agent update](https://drive.google.com/open?id=1DIJX1Q7Wt8_nrRGoeAjUgV0cXwkiBzsJ)

**Comment by jy19** [comment] 2020-01-07 19:30
Hi, I am unable to access the logs you've linked - could you either paste it in the comments or upload it as a zip file?

**Comment by Bragrel** [comment] 2020-01-07 21:35
Hi, @jy19 you can find files in [dropbox](https://www.dropbox.com/sh/pc13mbhmo34yts0/AACPQzNQkR9d77WrribNCvbIa?dl=0)

**Comment by jy19** [comment] 2020-01-07 23:09
Looking through your logs, the `[WARN]` logs should only be on older version of agents, and your latest logs that is running agent version 1.35.0 does not have them as expected. Regarding being unable to register container instance, it looks like it's not able to connect to the internet properly. Can you ssh into the instances you're trying to register to a cluster and ping any public ip address? Also double check if anything changed with your network settings (outbound access in security group rules, route to NAT Gateway)

**Comment by Bragrel** [comment] 2020-01-08 08:46
@jy19  yes, instance can reach internet:
```
admin@ip-10-0-1-204:~$ ssh ec2-user@10.0.0.79
The authenticity of host '10.0.0.79 (10.0.0.79)' can't be established.
ECDSA key fingerprint is SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.0.0.79' (ECDSA) to the list of known hosts.

   __|  __|  __|
   _|  (   \__ \   Amazon Linux 2 (ECS Optimized)
 ____|\___|____/

For documentation, visit http://aws.amazon.com/documentation/ecs
33 package(s) needed for security, out of 70 available
Run "sudo yum update" to apply all updates.
[ec2-user@ip-10-0-0-79 ~]$ ping google.com
PING google.com (172.217.12.238) 56(84) bytes of data.
64 bytes from iad30s15-in-f14.1e100.net (172.217.12.238): icmp_seq=1 ttl=47 time=1.48 ms
64 bytes from iad30s15-in-f14.1e100.net (172.217.12.238): icmp_seq=2 ttl=47 time=1.09 ms
64 bytes from iad30s15-in-f14.1e100.net (172.217.12.238): icmp_seq=3 ttl=47 time=1.08 ms
64 bytes from iad30s15-in-f14.1e100.net (172.217.12.238): icmp_seq=4 ttl=47 time=1.08 ms
64 bytes from iad30s15-in-f14.1e100.net (172.217.12.238): icmp_seq=5 ttl=47 time=1.07 ms
64 bytes from iad30s15-in-f14.1e100.net (172.217.12.238): icmp_seq=6 ttl=47 time=1.32 ms
^C
--- google.com ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5006ms
rtt min/avg/max/mdev = 1.076/1.193/1.488/0.157 ms
```
I double checked network ACLs (both inbound/outbound looks the same):
![image](https://user-images.githubusercontent.com/5269504/71962081-bf12db80-3209-11ea-8a4c-78bc6e9e3284.png)

Private subnet have route to NAT Gateway, public subnet have route to Internet Gateway:
![image](https://user-images.githubusercontent.com/5269504/71962829-5fb5cb00-320b-11ea-99f0-7d07f644922d.png)
![image](https://user-images.githubusercontent.com/5269504/71962921-9a1f6800-320b-11ea-9a0b-a242bfe41699.png)



Security group allow all outbound traffic:
![image](https://user-images.githubusercontent.com/5269504/71962395-6263f080-320a-11ea-88be-6e001d9100d7.png)

**Comment by jy19** [comment] 2020-01-08 19:35
Sorry, I did not look at the ecs-init logs properly last time. Could you try deleting the ecs-data file located at `/var/lib/ecs/data/ecs_agent_data.json` and see if that helps with starting up agent?

**Comment by Bragrel** [comment] 2020-01-08 19:54
Thank you for your reply.
This file does not exist:
```
admin@ip-10-0-1-204:~$ ssh -A ec2-user@10.0.0.79
Last login: Wed Jan  8 08:23:07 2020 from ip-10-0-1-204.ec2.internal

   __|  __|  __|
   _|  (   \__ \   Amazon Linux 2 (ECS Optimized)
 ____|\___|____/

For documentation, visit http://aws.amazon.com/documentation/ecs
33 package(s) needed for security, out of 70 available
Run "sudo yum update" to apply all updates.
[ec2-user@ip-10-0-0-79 ~]$ ls /var/lib/ecs/data/ecs_agent_data.json
ls: cannot access /var/lib/ecs/data/ecs_agent_data.json: No such file or directory
[ec2-user@ip-10-0-0-79 ~]$ sudo ls /var/lib/ecs/data/ecs_agent_data.json
ls: cannot access /var/lib/ecs/data/ecs_agent_data.json: No such file or directory
```

**Comment by jy19** [comment] 2020-01-08 21:42
I will investigate from our service side why your instances are failing to register - can I get the full cluster arn that you are trying to register the instance to? (email to ecs-agent-external at amazon dot com) also confirming that this is in us-east-1 (as seen from logs)?

**Comment by Bragrel** [comment] 2020-01-09 08:14
Yes, this is in us-east-1. I've sent an email with requested info.
Thank you for doing this!

**Comment by jy19** [comment] 2020-01-11 00:03
From my side, i can see that there are 8 instances in the cluster (different from the ones you've included in your email) and none of them have agent connected, as expected. Since the error you are facing seems to be that the requests can't get properly sent, there is nothing i can find from service side why it may be failing to register (the requests never reach). I will try and reproduce this issue based on your network settings to see if i can see what the problem may be. 

To double check, your instances are in a private subnet, and you have a NAT gateway set up to connect to a public subnet that is connected to the internet?

**Comment by Bragrel** [comment] 2020-01-11 08:04
> From my side, i can see that there are 8 instances in the cluster (different from the ones you've included in your email)

This is weird. I've sent you a screenshot where you can see that we don't have other instances (except bastion instance) in that VPC. I wonder what instances you can see in that cluster. Can you share instances ids with me?

>To double check, your instances are in a private subnet, and you have a NAT gateway set up to connect to a public subnet that is connected to the internet?

I've sent a bunch of screenshots to confirm this.

**Comment by fenxiong** [comment] 2020-01-16 00:28
To help us debug, could you try the following steps on the instance (to get some tcpdump output to let us have a clue on why the connection is failing):
(1) In one terminal, start tcpdump with `sudo tcpdump -w /tmp/ping.dump -i eth0` and in another terminal, ping public internet (e.g. `ping -c 3 google.com`) (then stop tcpdump in first terminal).
(2) In one terminal, start tcpdump with `sudo tcpdump -w /tmp/ecs.dump -i eth0` and in another terminal, start the ecs agent (`sudo systemctl start ecs`)
(3) Send the file /tmp/ping.dump and /tmp/ecs.dump to ecs-agent-external AT amazon.com

Thanks.

**Comment by Bragrel** [comment] 2020-01-17 10:07
@fenxiong I've sent requested info. Thanks!

**Comment by Bragrel** [comment] 2020-01-20 13:27
@fenxiong contacted me to explain the problem. I think I need to let everybody know. 
The problem was in ECS VPC endpoint which was configured incorrectly. Here is more info on how to configure it: https://aws.amazon.com/blogs/compute/setting-up-aws-privatelink-for-amazon-ecs-and-amazon-ecr/

@fenxiong @jy19 Thank you very much!

**Comment by fenxiong** [comment] 2020-01-20 17:13
@Bragrel no problem, glad that we can help. Closing the issue now. Let us know if you have other question. Thanks!

**Closed by fenxiong** 2020-01-20 17:13 UTC
