### ISSUE TITLE
EC2 Windows Instances for ECS - Configure proxy for ECS end point

### ISSUE THREAD

**Issue by sriramk2387** [aws/amazon-ecs-agent#824] opened 2017-05-30 18:05 UTC
I am trying to get Windows ECS setup in our AWS account – as per http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_Windows_getting_started.html.
The new EC2 does not register with ECS and I looked at the comments here - https://github.com/aws/amazon-ecs-agent/issues/660.

Our AWS  account restricts direct outbound traffic and is allowed through a proxy. I had to add the proxy to the user data to get that agent registered.
It looks like the EC2 now has trouble connecting with ECS service end-point – how or where do I configure the proxy for this?

**Error:** 

> Could not register module="api client" err="RequestError: send request failed
> caused by: Post https://ecs.us-east-1.amazonaws.com/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"

**Comment by samuelkarp** [comment] 2017-06-01 18:26
It looks like this is a duplicate of https://github.com/aws/amazon-ecs-agent/issues/808.  See that issue for a suggestion.

**Closed by samuelkarp** 2017-06-01 18:26 UTC
