### ISSUE TITLE
Consistent health check failures after stable service registers instance in elb

### ISSUE THREAD

**Issue by ldm810** [aws/amazon-ecs-agent#1561] opened 2018-09-06 02:52 UTC
### Summary

I notice that the service is  in a stable state. 
Then, hours later it is followed by a message like `service X registered 1 instances in elb Y`

Afterwards, it reports a  host is unhealthy with a log like this
`service X (instance i-Z) is unhealthy in elb Y due to (reason Instance has failed at least the UnhealthyThreshold number of health checks consecutively.)`

Why is it registering an instance if the service is stable?
### Description

We consistently see this behavior where the service is stable and then the service is registering an instance. I don't understand if the service is stable, why is it registering a new instance. In all cases, when the instance gets registered, an instance fails a health check.

During this time period, we also notice high backend connection errors.

### Expected Behavior
The service should not register a new instance if the service is stable. 

### Observed Behavior
When the service is stable, the service registers an instance in the ELB

**Comment by haikuoliu** [comment] 2018-09-10 20:10
This seems to be a duplicate of #1564, closing this in favor of #1564.

**Closed by haikuoliu** 2018-09-10 20:10 UTC
