### ISSUE TITLE
Run Options parity with docker-compose?

### ISSUE THREAD

**Issue by consultantRR** [aws/amazon-ecs-agent#170] opened 2015-08-15 20:51 UTC
Is it too broad of an ecs-agent enhancement request to simply request run options parity will all of the run options currently supported in a docker-compose.yml config file?  ;)

See:  https://docs.docker.com/compose/yml/

Two specific options for which I have personally have strong needs which are currently supported by docker-compose and (I believe) unsupported by ecs-agent are `env_file` and `labels`.

Happy to further discuss use cases if needed, and to help prioritize.

**Comment by euank** [comment] 2015-08-17 18:48
I'm going to close this as a duplicate of #127 which we're already tracking. If you think this is distinctly different, feel free to re-open.

I am interested in what use-case you have for `env_file` since it really is just sugar over setting environment variables, which is easy enough to do in the task definition.

Best,
Euan

**Closed by euank** 2015-08-17 18:48 UTC

**Comment by consultantRR** [comment] 2015-08-17 19:10
A few thoughts on `env_file`:

I can envision multiple cases in which I don't want env vars, and particularly, their runtime values explicit in the task definition. Yes I understand that it is "sugar" of sorts in that docker-compose (which does this today) and ecs-agent (which I propose should do this) is just parsing an `env_file` at runtime and sending explicit `-e` flags to the Docker daemon at runtime. But maybe, for example, I want privilege separation? Maybe I want my container hosts to have private access to an S3 bucket to fetch this `env_file`, but I don't want my operator (to whom I grant IAM permissions to create task definitions) to be privy to those values. Maybe I don't want these env var values present anywhere in the AWS API (ie: only the local ecs-agent knows the values at runtime.) Maybe I simply want to manage my env vars in an independent table for easy swapability between prod and dev environments without drastic changes to my task definition. Maybe I want the env vars and values to live with my project repo rather than in an infrastructural or operator repo. Maybe I want to generate the `env_file` dynamically at or just prior to runtime. Maybe I want to alter values in the `env_file` across the life of an existing task definition without altering the task definition.

Happy to further discuss if it might be helpful.

**Comment by consultantRR** [comment] 2015-08-17 19:12
PS: Here is a comment I posted in an AWS Forums thread which elaborates a little in context:

```
With ECS being a service that potentially runs containers on multiple and/or random hosts in a cluster, the concept would need to be adapted a bit in regards to being able to specify an env file location that was available to all hosts in the cluster. Ideally, both S3 and HTTP/HTTPS locations would be supported. (In fact, if HTTP/HTTPS locations were supported, it would be possible to write a service that generated an .env file dynamically on request, rather than simply serving up a static .env file.)
```
