### ISSUE TITLE
ECS cluster overlay network

### ISSUE THREAD

**Issue by omus** [aws/amazon-ecs-agent#607] opened 2016-11-21 17:49 UTC
It would be nice if ECS supported [multi-host networking](https://docs.docker.com/engine/userguide/networking/get-started-overlay/). The way I imagine this working is that all ECS container instances within the same cluster would share an overlay named "cluster". Task definitions could then specify the network mode "cluster" to use it.

**Comment by CpuID** [comment] 2016-11-21 19:41
Related: https://github.com/aws/amazon-ecs-agent/issues/437

**Comment by samuelkarp** [comment] 2016-11-23 19:35
Thanks @CpuID, closing as a duplicate of https://github.com/aws/amazon-ecs-agent/issues/437.  @omus Thanks for the suggestion!

**Closed by samuelkarp** 2016-11-23 19:35 UTC
