### ISSUE TITLE
ecs-agent doesn't detect GPU on initial startup, but does after restarting

### ISSUE THREAD

**Issue by heyryanw** [aws/amazon-ecs-agent#3823] opened 2023-07-20 22:53 UTC
### Summary
The ecs-agent should be able to detect if the instance has a GPU on initial startup, but currently logs the error:
`"Config for GPU support is enabled, but GPU information is not found; continuing without it" module=nvidia_gpu_manager_unix.go`
on initial startup. Looking into `/var/lib/ecs/gpu`, there is no entry for the detected gpu information, but this will be populated if ecs-agent is restarted.

### Description
1) Launch GPU enabled instance from AMI
2) Configure settings in /etc/ecs/ecs.config including `ECS_ENABLE_GPU_SUPPORT=true` during boot
3) Observe `/var/log/ecs-agent/log` shows error message ```msg="Config for GPU support is enabled, but GPU information is not found; continuing without it" module=nvidia_gpu_manager_unix.go```
4) Observe lack of json in `/var/lib/ecs/gpu`
5) Restart ecs service
6) Observe ecs-agent.log now shows registering GPU, and see entity in `/var/lib/ecs/gpu`

### Expected Behavior
ecs-agent correctly identifies GPU on initial startup, and populates `/var/lib/ecs/gpu` without user intervention

### Observed Behavior
ecs-agent is not detecting GPU on initial startup, and is not showing entry in `/var/lib/ecs`

### Environment Details
Instance type: g4dn.*
OS: Amazon Linux 2
Arch: amd64 or arm64
AMI: Custom with base from `ami-000a54989336780b5`

### Supporting Log Snippets
```
< initial instance launch >
ecs-agent.log:level=error time=2023-07-20T22:18:12Z msg="Config for GPU support is enabled, but GPU information is not found; continuing without it" module=nvidia_gpu_manager_unix.go
ecs-init.log:2023-07-20T22:18:07Z [INFO] pre-start: setting up GPUs
ecs-init.log:2023-07-20T22:18:07Z [INFO] By using the GPU Optimized AMI, you agree to Nvidia’s End User License Agreement: https://www.nvidia.com/en-us/about-nvidia/eula-agreement/
ecs-init.log:2023-07-20T22:18:07Z [INFO] pre-start: done setting up GPUs
< restart ecs >
ecs-init.log:2023-07-20T22:30:06Z [INFO] pre-start: setting up GPUs
ecs-init.log:2023-07-20T22:30:06Z [INFO] By using the GPU Optimized AMI, you agree to Nvidia’s End User License Agreement: https://www.nvidia.com/en-us/about-nvidia/eula-agreement/
```

**Comment by amogh09** [comment] 2023-09-25 19:28
Hi @heyryanw. Thank you for raising this issue and sorry that you are having trouble using GPU instances on ECS. 

I was not able to reproduce this issue using an ECS GPU AMI. I understand that you are using a custom AMI. 

The GPU info file is created by ecs-init before it starts ECS Agent. From the logs you provided, it seems like GPU setup was completed by ecs-init at `2023-07-20T22:18:07Z`, so unless ecs-init encountered an error (should be logged with `[ERROR] Nvidia GPU Manager:` prefix), the GPU info file should be present at `2023-07-20T22:18:12Z` when ECS Agent looks for it. 

Can you please reproduce the issue and provide full set of logs using [ECS Logs Collector](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html) for further investigation?

**Comment by singholt** [comment] 2023-10-24 22:39
closing this ticket, please reopen when you have logs and send our way at ecs-agent-external@amazon.com

**Closed by singholt** 2023-10-24 22:39 UTC
Labels: more info needed
