### ISSUE TITLE
Using ECS Optimized AMI 2018.03.f some containers wont start 

### ISSUE THREAD

**Issue by dannygu** [aws/amazon-ecs-agent#1568] opened 2018-09-11 19:08 UTC
### Summary
After upgrading ECS AMI 2018.03.e to 2018.03.f several containers wont start, the following error is seen in container log `standard_init_linux.go:190: exec user process caused "permission denied"`

### Description
We've recently upgraded ECS AMI 2018.03.e (ECS agent 1.20.1-1.amzn1 / Docker 18.03.1ce-5.0.amzn1) to 2018.03.f (Docker 18.06.1-ce + ECS Agent 1.20.2), after the upgrade some containers work as they did before while others produce the following error in docker logs `standard_init_linux.go:190: exec user process caused "permission denied"`, we've downgraded back to 2018.03.e and everything works fine, not sure this error is related to ECS Agent, perhaps an SELinux issue/change ? 

### Expected Behavior
Container should start, no changes were performed in task json or config, only version upgrade of Docker/ECS Agent.

### Observed Behavior
Container fails to start with the following error `standard_init_linux.go:190: exec user process caused "permission denied"`

### Environment Details
ECS Optimized AMI 2018.03.f 
Docker 18.06.1-ce 
ECS Agent 1.20.2

### Supporting Log Snippets
`standard_init_linux.go:190: exec user process caused "permission denied"`

**Comment by jahkeup** [comment] 2018-09-11 20:09
Thanks for the report @dannygu. Digging into this, I have a few initial questions:

* Are there particular container images or executables/commands that are affected that you can share with us? That'll help us diagnose and reproduce this issue (if you've derived from some public base layer, that works too).

* Have you tried updating the Docker daemon on the 2018.03.e instances? If so, does this issue persist? It may be worth trying to update the kernel and docker independently.

* Do you have any extra configuration present that would enable selinux? The reason I ask is because SELinux is disabled by default on Amazon Linux, so I wouldn't expect that to have a hand in this.

If there are any details that you'd feel more comfortable sharing in private, please feel free to email me at `jakeev @ amazon.com`.

**Comment by dannygu** [comment] 2018-09-12 06:40
Hi @jahkeup ,

-  The images that wont start have an entrypoint to a simple shell script, i can share them with you privately if you'd like me to.

-  No, haven't tried that, i'll try and upgrade manually and let you know.

-  No, we don't modify any SELinux related setting on the ECS Optimized image (are you sure SELinux is disabled on ECS Optimized AMI?)

Thanks.

**Comment by jahkeup** [comment] 2018-09-12 14:40
Thanks for the details @dannygu , I have some suspicions that are related to the scripts themselves and the container image that they're in. I threw together a quick test here of what may be happening: https://gist.github.com/jahkeup/f84251385970e6fb2bb811f9c5efe8c4

In short: there could be problems with the permissions of the script and/or the paths of their interpreter that are being specified in them. I'm happy to take a look at the scripts in question if you'd like an extra set of eyes on them.

**Comment by vmiszczak-teads** [comment] 2018-09-17 09:08
Hello,

We had the same kind of issue with the latest CoreOS image. Our effective user did not have execute permission on the entrypoint. It was working up to 18.03 and has been fixed by https://github.com/moby/moby/pull/36587.
This may help.

**Comment by jhmartin** [comment] 2018-09-17 16:06
@vmiszczak-teads which exact coreos image was impacted?

**Comment by dannygu** [comment] 2018-09-25 13:57
I can update this issue is resolved for me, after reviewing @vmiszczak-teads comments i verified permissions and indeed found that was the cause, thanks.

**Closed** 2018-09-25 16:01 UTC
Labels: more info needed

**Comment by SkxNMDI5** [comment] 2018-10-15 11:42
> Hi @jahkeup ,
> 
> * The images that wont start have an entrypoint to a simple shell script, i can share them with you privately if you'd like me to.
> * No, haven't tried that, i'll try and upgrade manually and let you know.
> * No, we don't modify any SELinux related setting on the ECS Optimized image (are you sure SELinux is disabled on ECS Optimized AMI?)
> 
> Thanks.

I confirm SELinux is disabled on ECS Optimized image
