### ISSUE TITLE
Docker ps hanging

### ISSUE THREAD

**Issue by sergiofigueras** [aws/amazon-ecs-agent#803] opened 2017-05-14 12:24 UTC
Hello guys,

We've an ECS cluster, that is currently running with 6 x1.large EC2 spot instances. The issue is that by some unknown reason, suddenly one of those instances just stop responding any docker commands, even a simple `docker ps`. Then, we've a lot of services in `pending` state, and also it seems that the whole cluster stuck when dividing the tasks, since no other task turns to `running` state. Also, the `Agent Connected` turns to `false`, as shown below:

<img width="1380" alt="screen shot 2017-05-14 at 9 24 58 am" src="https://cloud.githubusercontent.com/assets/1733227/26033711/3aa389b8-3887-11e7-9db7-69c96b2159d8.png">

I wish that I could extract the logs there, but usage of `ecs-logs-collector` is not possible because it hangs when it tries to get docker information, and stop responding too.

I think that some container is the root cause for this issue. But I cannot collect the logs, and I cannot do anything on it. What is the issue there? What should I do in that situation?

Thanks,

Sergio.

**Comment by samuelkarp** [comment] 2017-05-16 23:13
@sergiofigueras It looks like this is a duplicate of https://github.com/aws/amazon-ecs-agent/issues/806, so I'll close this one.

**Closed by samuelkarp** 2017-05-16 23:13 UTC
