### ISSUE TITLE
Cluster Memory Utilisation reporting incorrect value

### ISSUE THREAD

**Issue by asceresini** [aws/amazon-ecs-agent#697] opened 2017-02-06 06:27 UTC
*Docker stats* and *top* are both reporting cluster memory utilization of about 80% whereas ECS agent is reporting about 15%.

**Comment by asceresini** [comment] 2017-02-06 06:28
Reverting back to the previous version 2016.09.d fixes the issue.

**Comment by aaithal** [comment] 2017-02-06 16:40
Hi @asceresini, thanks for reporting this. We modified the way we compute the "MemoryUtilization" metric with the v1.14.0 Agent (released with the latest AMI) to exclude the filesystem cache usage. You can read more about it in our [docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html#available_cloudwatch_metrics) (the note below the table) and in pull #582 and in issue #280. The details and the impact are documented [here](https://github.com/aws/amazon-ecs-agent/issues/280#issuecomment-262655248). I'm closing this thread for now. Please feel free to continue the discussion or open a new issue if needed. 

Thanks,
Anirudh

**Closed by aaithal** 2017-02-06 16:40 UTC

**Comment by davidpelaez** [comment] 2017-07-08 02:53
@aaithal I'm a little lost with the docs. For instance I have a cluster with +81% memory utilization in 15 t2.micro instances (considering the value shown as memory available in the instance list) and the console shows 8.01% for memory utilization. I don't understand how the difference can be so big under any circumstance. Are you certain this is not a bug?

**Comment by davidpelaez** [comment] 2017-07-08 03:03
Could you provide an example where the most recent behavior is a good metric to monitor cluster health? It took me about 2 hours to see that the number of running tasks wasn't increasing because the instances didn't have much memory available but of course this wasn't showing in the metric at all. Had the metric show available memory on the machines I would've been able to understand the problem quickly. This of course doesn't mean my interpretation is correct, I just want to understand in which case the current value is meaningful so that I can consider that in the future.
