### ISSUE TITLE
1.29.0 CannotPullContainerError pull access denied requiring multiple host destruction

### ISSUE THREAD

**Issue by eedwards-sk** [aws/amazon-ecs-agent#2137] opened 2019-07-19 00:06 UTC
### Summary
After pushing a new ECR image and attempting to deploy, instance started failing to pull image from ECR, even with no permissions changes.

### Description

Status reason | CannotPullContainerError: Error response from daemon: pull access denied for FOO.dkr.ecr.us-east-1.amazonaws.com/foo/app, repository does not exist or may require 'docker login'

3 different ECS services, across 2 different hosts, all started showing this error upon attempting to launch new tasks during a deployment.

I confirmed I could pull the image locally on my own workstation when performing a `docker login` to ECR.

No permissions changes were made to the instance.

The ecs tasks all have task execution roles that have the proper ECS Role Policy attached.

The ecs hosts themselves have the proper ECS permissions in their instance roles.

After re-creating the hosts, they pulled fine.

I'm trying to figure out what state the instance got into and how to resolve it in the future. It should not be failing to pull ECR images.

I'm opening this to start it as a point for tracking these issues in the future, as extensive searching did not surface anyone else having this same issue.

### Environment Details
ubuntu bionic 18.04
ecs agent 1.29.0

**Comment by shubham2892** [comment] 2019-08-08 20:43
@eedwards-sk Is it possible the that Docker logged out in the instance, do you have Docker logs from the hosts in which this happened. Also, can you email me Date/time of when the issue occurred at shugy at amazon dot com.

**Comment by eedwards-sk** [comment] 2019-08-08 20:57
@shubham2892 Thanks for your response.

Unfortunately I don't persist docker agent logs from the hosts to any external store, so any of that detail was lost the moment I re-created the hosts (prior to opening the issue).

During investigation I did check the logs (syslog and the docker daemon as well as ecs-agent) and nothing obvious was surfaced, but I was also focused on recovering services more than the root cause.

Considering this was happening at the same time across multiple hosts, I'm not sure it was an issue specific to one host.

For the time / date, the closest I can approximate is when the replacement hosts came online, which was July 18th 6:56 PM CDT (July 18th 11:56 PM UTC)

**Comment by pasanw** [comment] 2019-08-13 02:09
I also ran into this issue. Without any change to the cluster instances, pulls began to fail across all hosts with the exact same error reported above. These instances were online and pulling images fine for just over a month.

We are running the containerized agent (1.29.1) on our cluster instances. The issue can be resolved by restarting the agent container on each instance.

**Comment by yumex93** [comment] 2019-08-14 18:22
I will try to see whether I can reproduce the issue on my side. However, @pasanw do you have the agent debug level logs during the time period having the issue. If you still have it, could you send the log to yumex at amazon dot com.  It would help a lot for debugging the issue.

**Comment by pasanw** [comment] 2019-08-14 22:48
Thanks @yumex93, I've sent you logs via e-mail. Unfortunately the log level was INFO, hope it can still be of use. Let me know if it successfully reached your inbox.

**Comment by yumex93** [comment] 2019-08-16 00:47
@pasanw Which email address you are using to send me the log?

**Comment by yumex93** [comment] 2019-08-16 18:09
@pasanw Sorry. The log did not provide enough information that can help me figure out whether this can be a credential issue, a docker issue or just an issue on ECR side. 
Just wanna to collect more information, before the issue happens, did you try to update your image on ECR?
Besides, would you be able to turn on debug level and use ecs log [collector](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html) to collect logs and send to us when it happens again. This will get more info that can help us dig into the problems.

**Comment by fcoelho** [comment] 2019-08-29 19:51
@yumex93 I'm also having issues with this. Had to recreate the instance to get things going again, and this just happened one more time. There's a few messages from docker that look like this:

```
Aug 29 19:30:44 ip-xx-xx-xx-xx dockerd: time="2019-08-29T19:30:44.909653497Z" level=error msg="Not continuing with pull after error: denied: The security token included in the request is invalid."
```

I've ran the ecs log collector program though before enabling debug mode. Can I send the results to you as well?

I've enabled debug mode on this instance and will report back with new logs if this happens again, but the log collector had to restart docker to enable debug mode and things seem to be working as expected now. for reference, this instance is a `c5.large` with eni trunking enabled using ami `ami-02bf9e90a6e30dc74` in `eu-west-1`

**Comment by yunhee-l** [comment] 2019-08-30 18:32
@fcoelho please feel free to send it to either @yumex93 or myself (yhlee _at_ amazon _dot_ com).@fcoelho please feel free to send it to either @yumex93 or myself (yhlee _at_ amazon _dot_ com).

**Comment by yunhee-l** [comment] 2019-09-04 19:19
@fcoelho thank you for sending the logs, I've replied to your email!

**Comment by radamisa** [comment] 2019-10-21 19:11
We've also encountered this multiple times with ECS Agent 1.32.0 running on `Amazon Linux AMI 2.0.20191014 x86_64 ECS HVM GP2` in `us-east-1`.

**Comment by hlarsen** [comment] 2019-10-21 19:31
we've also seen it happen a few times, though we're just now getting back to the projects involving ECS so it's becoming more of a concern.

is the workaround to restart the agent on each ec2 instance?
is there any more public information about how or why this is happening?

i'd obviously love to do nothing rather than have to worry about restarting the agent.

**Comment by cyastella** [comment] 2019-10-21 20:57
Hi,
Sorry for facing the issue. When the CFN stack is deleted and recreated, the task execution role with the same role ARN is deleted and recreated. Since currently when agent caches the credentials of the role, it uses the combination of region, roleARN, registryID, endpointOverride as the key. Which means, as such case, agent will use the credentials from the cache rather than the credentials of the newly created role. This is a known issue and we will work on it in the future.

For now as a workaround, if such an error occurs, we suggest you restart agent on the instance manually after deleting the stack, which will clear the cache, and then recreate the CFN stack. Another workaround will be not specify the execution role name when use CFN to create role.

Thanks

**Comment by mikalai-t** [comment] 2019-11-27 10:43
@cyastella Thank you so much!

**Comment by jungtaek-raphael** [comment] 2020-03-27 11:24
@cyastella Thank you!! You saved my life

**Comment by fierlion** [comment] 2020-04-28 18:59
note: if you face this issue and are willing to help out here with more logs, please use [ecs logs collector](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html) and send to ecs-agent-external at amazon dot com.  

We are actively looking into clarifying the root cause and repro of this scenario.

**Comment by dzmitry-kankalovich** [comment] 2020-06-19 03:13
I am just going to add to the workaround said by @cyastella:
If you have a named Exec Role and prefer to keep it that way, then even a slight change in naming would also work, for example you can append `v2` to the role name.

**Comment by UlrichEckhardt** [comment] 2020-10-28 12:22
I'm not sure if you still have problems reproducing this. However, I think the way is to simply

- use an execution role with a name
- delete a stack 
- create the stack again

The second and third steps is what I always did to make sure that the stack configuration was proper (I'm a beginner with CFN) and which then caused the issues when ECR tried to deploy on EC2 instances that had the role credentials cached already. The pattern that only some instances were affected was actually what I noticed first.

**Comment by kyleian** [comment] 2020-11-11 15:46
@fierlion Sent you some logs to that specified email address.

Conditions/workflow for reproducing:
- Brand new EC2 in ECS Cluster
- Deploy ECS Service/TaskDef via Cloudformation; Task/Execution roles (that contain ECR permissions) for service/task def contained within that same template; successful deploy/pull of image from ECR, no issues
- Nuke the ECS Service Stack, which deletes task/exec roles
- Redeploy ECS Service via cloudformation - yields error in status reason CannotPullContainerError

Something I noticed in the ECS UI in my current working example, is I do see that the task actually _does_ pull the image occasionally, eg state == "RUNNING", however the error is still manifested in the Status Reason: 

`CannotPullContainerError: Error response from daemon: pull access denied for $REDACTED_REGISTRY_ID, repository does not exist or may require 'docker login': denied: The security token included in the request is in`

It is unclear to me the difference for why occasionally it'll manage to pull the image with RUNNING state but still display the CannotPullContainerError, but the majority of the time I see this we're not able to pull the image when that error is displayed (perhaps within the timing of the token from the original role still being actually valid? The majority of the time I have seen this, it is likely the token is actually expired for the old role that was deleted, am attempting to replicate that case currently, will send separately as a followup.)

Our workaround for now will be to separate out the IAM roles into a separate stack to prevent them from being destroyed on an ecs-service stack delete/rollback.

**Comment by awons** [comment] 2020-11-16 12:32
@kyleian For us the reason why it managed to start the task was because the image already existed on the instance. So it looks as if it still uses the existing image but tries to pull the latest one anyway. And hence the error. At least that's our assumption.

**Comment by fierlion** [comment] 2021-02-04 21:50
@awons 
I imagine that if you were to test with `ECS_IMAGE_PULL_BEHAVIOR=always` it would force the image to be pulled, and likely force the behavior, (while `default` will try to pull first, and fall back to the cache and `prefer-cached` would do the opposite.)
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html

Note, I'm working on a repro now based on the above steps (thanks all).

**Comment by fierlion** [comment] 2021-02-05 21:09
I am able to reproduce this -- I've attached my taskdef 
repro steps:

  Create a generic VPC using the console's VPC wizard,  This will have a public
  and a private subnet.  We'll use the public subnet for this test.
  Create an ecs cluster and launch an EC2 using the latest ECS Optimized AMI in
  the above VPC's public subnet.

  Also, you'll need to create an ECR busybox repo and upload the latest busybox
  image to it.  Replace the image in the supplied taskdef with your busybox ECR
  image.

  The supplied cloud formation stack will create the task/service/log group but
  more importantly will create the task IAM role.  When you tear down and
  re-create the stack, if you don't update the task IAM role name, then you'll
  hit the error.

  Run the following command to create your service/task/etc:
  ```
  $ aws cloudformation create-stack --stack-name ecs-shell --template-body file://./ecs-shell.yml --capabilities CAPABILITY_NAMED_IAM --parameters     'ParameterKey=SubnetID,ParameterValue=<subnet-id>' 'ParameterKey=Cluster,ParameterValue=<cluster-id>' 'ParameterKey=SecurityGroup,                   ParameterValue=<subnet-security-group>'
  ```
[cloudformation.txt](https://github.com/aws/amazon-ecs-agent/files/5935344/cloudformation.txt)

I'm now looking into what's happening with the task IAM credentials expiration between stack delete and create.

**Comment by shubham2892** [comment] 2021-02-26 18:02
Upon further investigation we have come to know that when an IAM role is deleted and recreated with the same name, the ec2 instance associated with the role will no longer be able to use the permissions granted though that role, this is the expected behavior(https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_manage_delete.html). As mentioned in the comments above, it is recommended that each time you launch a CloudFormation template, you give your IAM role(s) a unique name.

**Closed by shubham2892** 2021-02-26 18:02 UTC
Labels: kind/bug, kind/tracking, workaround available

**Comment by hlarsen** [comment] 2021-02-26 18:24
> Upon further investigation we have come to know that when an IAM role is deleted and recreated with the same name, the ec2 instance associated with the role will no longer be able to use the permissions granted though that role, this is the expected behavior

@shubham2892 how is this accurate when we can simply restart the ecs-agent to fix the issue?

> Since currently when agent caches the credentials of the role, it uses the combination of region, roleARN, registryID, endpointOverride as the key. Which means, as such case, agent will use the credentials from the cache rather than the credentials of the newly created role. This is a known issue and we will work on it in the future.

the above explanation was given to us quite a while ago, is it no longer accurate?

everything points to this being an issue with the ecs-agent caching IAM permissions, not with EC2/IAM - i'm happy to be corrected if i'm wrong here.

**Comment by jpcope** [comment] 2023-03-28 09:03
For anyone else finding this: if one alters the iam role on an ec2 instance such that the old role no longer exists, one MUST refresh the ec2 instances or restart the ecs-agent. The ecs-agent does not appear to automatically discover that a new role is being used on an existing ec2 instance.

If one runs into this using cloudformation, note that `AWS::IAM::InstanceProfile` resource type's Roles parameter updates without replacement. So if there is some other resource receiving a property from that resource type that "on update requires replacement" (Launch Configs) or "on update performs an instance refresh" (Launch Templates), one will need to update a property on the `AWS::IAM::InstanceProfile` resource type that on `update requires replacement` at the same time. Note that all the other properties trigger a physical resource replacement, just not `Roles`.

**Comment by shubmanh** [comment] 2023-03-28 18:44
Hi team, is there any update on the fix for this issue?

I'm using the latest ECS agent version `1.69.0` and still facing this issue.

**Comment by andrey-autofi** [comment] 2024-10-01 20:29
Still facing the same problem, ECS Agent `v1.86.3`
Please do something!
