### ISSUE TITLE
Long delay before pulling new containers to be run after ecs-agent start

### ISSUE THREAD

**Issue by vhartikainen** [aws/amazon-ecs-agent#1160] opened 2018-01-04 08:33 UTC
### Summary
After start, ecs-agent waits for several minutes until it gets new tasks and starts them up.

### Description
After booting up new Container Instance, it's not very optimal to wait for several minutes until the agent starts pulling new container images and starts them up.

Not sure if this is a ecs-agent or ECS service feature in particular.

### Expected Behavior
When started & joined the cluster -> immediately pull new tasks (if possible)

### Observed Behavior
3-5 minutes delay until tasks received to be run.

### Environment Details
* `docker info`
```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.2-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: 
 Metadata file: 
 Data Space Used: 1.071 GB
 Data Space Total: 23.35 GB
 Data Space Available: 22.28 GB
 Metadata Space Used: 741.4 kB
 Metadata Space Total: 25.17 MB
 Metadata Space Available: 24.42 MB
 Thin Pool Minimum Free Space: 2.335 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.43-17.38.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.03
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.798 GiB
Name: aaaa
ID: aaaa
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
* `curl http://localhost:51678/v1/metadata`
```
{"Cluster":"aaaa","ContainerInstanceArn":"arn:aws:ecs:eu-west-1:aaa:container-instance/aaaa","Version":"Amazon ECS Agent - v1.14.4 (f94beb4)"}
```
### Supporting Log Snippets
```
2018-01-03T13:28:17Z [INFO] Loading configuration
2018-01-03T13:28:17Z [INFO] Loading state! module="statemanager"
2018-01-03T13:28:17Z [INFO] Event stream ContainerChange start listening...
2018-01-03T13:28:17Z [INFO] Creating root ecs cgroup: /ecs
2018-01-03T13:28:17Z [INFO] Creating cgroup /ecs
2018-01-03T13:28:18Z [INFO] Registering Instance with ECS
2018-01-03T13:28:18Z [INFO] Registered container instance with cluster!
2018-01-03T13:28:18Z [INFO] Registration completed successfully. I am running as 'arn:aws:ecs:eu-west-1:aaaa:container-instance/aaaaa' in cluster 'aaaa'
2018-01-03T13:28:18Z [INFO] Saving state! module="statemanager"
2018-01-03T13:28:18Z [INFO] Beginning Polling for updates
2018-01-03T13:28:18Z [INFO] Event stream DeregisterContainerInstance start listening...
2018-01-03T13:28:18Z [INFO] Initializing stats engine
2018-01-03T13:28:18Z [INFO] NO_PROXY set:169.254.169.254,169.254.170.2,/var/run/docker.sock
2018-01-03T13:28:18Z [INFO] Connected to ACS endpoint
2018-01-03T13:28:18Z [INFO] Connected to TCS endpoint
2018-01-03T13:28:28Z [INFO] Handling http request module="Handlers" method="GET" from="127.0.0.1:48460" uri="/v1/metadata"
2018-01-03T13:28:28Z [INFO] Handling http request module="Handlers" method="GET" from="127.0.0.1:48462" uri="/v1/tasks"
2018-01-03T13:28:28Z [INFO] Saving state! module="statemanager"
2018-01-03T13:31:20Z [INFO] Saving state! module="statemanager"
2018-01-03T13:31:20Z [INFO] Waiting for any previous stops to complete module="TaskEngine" task="aaaa:13 arn:aws:ecs:eu-west-1:aaaa:task/aaaa, TaskStatus: (NONE->RUNNING) Containers: [aaaa (NONE->RUNNING),]" seqnum="2"
2018-01-03T13:31:20Z [INFO] Wait over; ready to move towards status: RUNNING module="TaskEngine" task="aaaa:13 arn:aws:ecs:eu-west-1:aaaa:task/aaaa, TaskStatus: (NONE->RUNNING) Containers: [aaaa (NONE->RUNNING),]"
2018-01-03T13:31:20Z [INFO] Creating cgroup /ecs/aaaa
2018-01-03T13:31:20Z [INFO] Pulling container aaaa(aaaa.dkr.ecr.eu-west-1.amazonaws.com/aaaa:0.0.1) (NONE->RUNNING) concurrently. Task: aaaa:13 arn:aws:ecs:eu-west-1:aaaa:task/aaaa, TaskStatus: (NONE->RUNNING) Containers: [aaaa (NONE->RUNNING),]
```

**Comment by richardpen** [comment] 2018-01-08 18:20
@vhartikainen Thanks for reporting this, based on the logs it looks like the agent was s
```
2018-01-03T13:28:17Z: Agent start`
2018-01-03T13:28:18Z: Agent connect to backend`
2018-01-03T13:31:20Z [INFO] Waiting for any previous stops: Agent start process the task
```
My suspect is that the agent received the task at `2018-01-03T13:31:20Z`, but since the task id and other information was redacted, I wasn't able to find the timestamps when the task was received by agent. In order to find out the cause here, can you provide the task id, account and the container instance id. You can send these information to me: penyin (at) amazon.com

Thanks

**Comment by antoine-galataud** [comment] 2018-01-09 08:43
Getting the same behavior with a simple `docker stop`. It then takes ~5 minutes for ecs agent to start the task again and related container. During that time ECS interface reports desired number > 0, but pending and running remains at 0 the whole time.
It seems to happen for a few days now, I can reproduce it almost every time. Facing this problem with ecs-agent 1.15.1 and 1.16.1, docker version 17.06.2-ce.

**Comment by richardpen** [comment] 2018-01-09 17:59
@antoine-galataud Can you reproduce this again and share the logs with us, so that we can understand what's happening in the agent?
Before you reproduce, can you enable the ecs-agent `debug` log by setting the environment variable `ECS_LOGLEVEL=debug` in `/etc/ecs/ecs.config` and restart the agent if you are using ECS Optimized AMI. Then you can collect the logs using [Amazon ECS Log Collector](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html). You can send it to my personal email: penyin (at) amazon.com.

Thanks.

**Comment by richardpen** [comment] 2018-01-11 18:37
@antoine-galataud Thanks for sending the logs. After taking a look at the logs, it looks like the agent start the task immediately after received the task. The delay exists in the backend, where it takes few minutes to reschedule another task for the service. I have let the backend know about this delay, will update if I get more information.

Thanks

**Comment by antoine-galataud** [comment] 2018-01-17 09:43
@richardpen thanks. Do you have any news from backend about that?

**Comment by aaithal** [comment] 2018-01-29 20:16
Hi @antoine-galataud,  we have an update for you here. The 15 minute delay here was a result of the ECS scheduler unable to find a candidate instance in 3 successive placement attempts. It was unsuccessful in finding a container instance, which had the requisite port available for the task. I think you can confirm this from the ["service events"](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-event-messages.html). I'm closing this issue for now. Please let us know if you have any follow up questions/comments.

**Closed by aaithal** 2018-01-29 20:16 UTC
Labels: kind/question, scope/ECS Service
