### ISSUE TITLE
Improve docker container <-> ECS container detection

### ISSUE THREAD

**Issue by euank** [aws/amazon-ecs-agent#166] opened 2015-08-12 19:37 UTC
Currently this is handled by persisting the mapping to a state file.

If that file is unable to be written or the agent crashes before that file is flushed to disk correctly, it is possible to end up in a state where a container started by the Agent is not recognized.

The agent also now applies a label to each container it runs with the Task ARN and container name within the task.
Those two pieces of information are sufficient to uniquely identify a container, and thus could be used as a fallback or in place of the above mentioned state file.

This would make the detection far more robust and, if used as the primary means of detection, greatly simplify what state needs to be persisted.

**Comment by kgorskowski** [comment] 2015-08-20 12:51
+1 
I occasionally run into a similar, maybe related problem.
When I did some testing and fast up- and downscaling of our services, the state of the running task count and the running containers was not consistent. For example I did a fast upscale from 1 to 10 tasks in the service and after a couple minutes back to 2 tasks I ended up with the ECS Dashboard stating 2 tasks but 3 containers running. 
t is not (yet) a breaking problem for us but may be of more relevance when we hit some ressource levels.

**Comment by euank** [comment] 2015-08-21 01:30
@kgorskowski If the the ECS Agent didn't crash, then this issue shouldn't be the culprit.

If it did crash and the "orphaned" task isn't present in the introspection api (`curl localhost:51678/v1/tasks; echo`), that is indicative of this issue.

One possibility here that occurs to me is that the console, by default, does not display 'desired stopped' tasks. If the container in question doesn't respond to sigterm, it takes 30 seconds to stop it which leads to a short-term disparity there.

If you can provide more information I'd be happy to help figure out what's going on here.

The output from the introspection API can tell you what tasks are running and what the ECS Agent thinks the state is. The `describe-task` output's information on known and desired status would be helpful as well. If that information doesn't match, then the Agent's logs would also help.

Best,
Euan

**Comment by kgorskowski** [comment] 2015-08-21 11:19
@euank Thanks for the helpful input, I very much appreciat that!
After I posted my issue I realized that there was the 1.40 Version of the Agent released which has a better mechanism to prevent such errors. At last thats how I understood it. 
So I now updated the Agent on all our instances and will do further testing. 
Thanks again!
Karsten

**Comment by abby-fuller** [comment] 2015-08-31 17:29
@euank we are seeing a similar issue, even with 1.4.  definitely a breaking issue for us, fwiw.  we've seen requests go to these orphaned/ghost containers, which causes issues.  is there any new info on this?

**Comment by euank** [comment] 2015-08-31 18:22
@abby-fuller Per my previous comment, can you provide a little more information about what you're seeing?

**Comment by abby-fuller** [comment] 2015-08-31 21:28
@euank:   we haven't been able to track down a root cause, so I have limited info, but basically, we can occasionally end up in a state where a service will have a running container that isn't tracked in ECS.  Meaning, the ECS dashboard will say that there are 3 containers running, but there are actually 4.  sounds pretty similar to what @kgorskowski reported above. I do know that the running containers that aren't reported by the ECS console _do_ show up with `docker ps` for us, but they have so far always been running the previous task revision.  For example, if we deploy task_foo:2, and the ECS console reports 3 running tasks, the 4th ghost task would be task_foo:1.  Nothing strange in the logs to indicate why this would be happening, unfortunately, at least that I've noticed.  It's happened a few times, across at least two of our ECS services.  

If there is more specific information that would help you out, let me know what I can do.

**Comment by abby-fuller** [comment] 2015-09-02 21:44
@euank :  can also verify that the agent appears as connected in the ECS console.

**Comment by euank** [comment] 2015-09-02 22:02
I think the next interesting thing to know is if the ECS Agent thinks they were stopped.
The output of `curl http://localhost:51678/v1/tasks` should show the tasks and what state the agent thinks they are in.
The agent's logs for around the time the tasks are 'stopped' could also help understand what happened better. I know you said you didn't see anything strange there, but I wouldn't mind looking as well if you're able to share those logs.

If none of that helps, the next step is to set `ECS_LOGLEVEL=debug` on the Agent and capture debug level logs when it happens.
Best,
Euan

**Comment by abby-fuller** [comment] 2015-09-03 20:02
@euank will try next time I see this. Will let you know what I find- happy to share logs.

**Comment by abby-fuller** [comment] 2015-10-15 18:41
hi @euank:  we seem to have possibly repro-ed this!  

Looking at the ECS console, we have three copies of a service running, that should only have 2 copies:

<img width="1138" alt="instance list" src="https://cloud.githubusercontent.com/assets/5341939/10523786/2b3efe5c-734a-11e5-94b7-c85b1710a803.png">

<img width="1165" alt="service detail" src="https://cloud.githubusercontent.com/assets/5341939/10523796/3cc44538-734a-11e5-9405-13d9e2122719.png">

deploy_bogan:13 has two copies running, which is correct.  However, one instance has a copy of deploy_bogan:1 running, which is definitely not correct.  


Output from `curl http://localhost:51678/v1/tasks`:

```
[ec2-user@IP ecs]$ curl http://localhost:51678/v1/tasks
{"Tasks":[{"Arn":"arn:aws:ecs:us-east-1:604238712147:task/716934d3-d027-4987-bf20-47ac6f36a034","DesiredStatus":"RUNNING","KnownStatus":"RUNNING","Family":"deploy_bogan","Version":"1","Containers":[{"DockerId":"86a4b06c0dcb2e28d391e78661c3dad62877125580fb363264bccfa1ccf698f4","DockerName":"ecs-deploy_bogan-1-deploybogan-a8a9b8d8928d97f51b00","Name":"deploy_bogan"}]}}]}[ec2-user@ip-10-0-0-37 ecs]
```

**Comment by samuelkarp** [comment] 2016-12-11 21:37
@abby-fuller As far as we're aware, this is no longer happening.  We fixed an issue that seems like it might have been related (tasks marked as `STOPPED` without actually being stopped) in [1.11.0](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.11.0).  I'm going to close this issue for now as we do not believe this is a current bug.

**Closed by samuelkarp** 2016-12-11 21:37 UTC
Labels: enhancement
