### ISSUE TITLE
Privileged container execution

### ISSUE THREAD

**Issue by bcwp** [aws/amazon-ecs-agent#167] opened 2015-08-13 06:48 UTC
Are there any plans to allow privileged container execution within ECS? This is a huge blocker for us, because we'd like to provision and mount a specific EBS volume when a container is started (with each container knowing what EBS volume belongs to it, so if it's moved to another host, the EBS vol follows it). This allows for persistent data across hosts, and for ex: a mysql DB container could be restarted on a different container instance without any downtime.

**Comment by samuelkarp** [comment] 2015-08-13 06:52
Thanks for the comments on your use case!  I'm closing this as a duplicate of #68, which we will update as more information becomes available.

**Closed by samuelkarp** 2015-08-13 06:52 UTC
