### ISSUE TITLE
Problems with daemon service running cadvisor

### ISSUE THREAD

**Issue by mohsinhijazee** [aws/amazon-ecs-agent#2242] opened 2019-10-20 15:23 UTC
When running `cadvisor:v0.33.0` as a daemon service, the `/metrics` endpoint hangs with constant increase in memory rise till the container dies. When same image is run manually on the same machine, it performs jus as expected. I have filed an issue on [cadvisor](https://github.com/google/cadvisor/issues/2328) side which has all the details but listing here as well in case anyone knows anything about it or facing something similar?

The issue files on the cadvisor side has details on the docker container that is being created by ECS agent. The AMI ID under question is `amzn2-ami-ecs-hvm-2.0.20191014-x86_64-ebs (ami-084ab95c0cbe247e5)`

**Comment by fenxiong** [comment] 2019-10-22 18:39
I looked at your container and tested with a [similar task def](https://gist.github.com/fenxiong/90a9407a069364ae9d249ece2e0c9817) on the same AMI, and did not have any problem curling `/metrics` endpoint. Looking at the [container inspect result of mine](https://gist.github.com/fenxiong/a52096434ee0143602e9fb1a95797434), the only thing different from yours is the log configuration (i did not use gelf). So I'd suggest try removing the log driver in your task definition and see if that's related?

**Comment by fenxiong** [comment] 2019-10-31 21:12
Closing this since i'm not sure whether there's anything we can do here. If you have a way to reliably reproduce, feel free to provide us the steps and reopen this issue though.

**Closed by fenxiong** 2019-10-31 21:12 UTC
Labels: more info needed
