### ISSUE TITLE
Flaky test/data race: TestPauseContaienrHappyPath

### ISSUE THREAD

**Issue by samuelkarp** [aws/amazon-ecs-agent#1029] opened 2017-10-23 20:08 UTC
### Summary
`TestPauseContaienrHappyPath` appears to have a data race sometimes.

### Description
Looks like a race between sending on a channel and closing that same channel.

### Expected Behavior
Tests pass.

### Observed Behavior
Tests sometimes fail.

### Environment Details
TravisCI

### Supporting Log Snippets
```
==================
WARNING: DATA RACE
Write at 0x00c4203f2540 by goroutine 183:
runtime.closechan()
/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/chan.go:303 +0x0
github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).cleanupTask()
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/task_manager.go:723 +0x8f5
github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).overseeTask()
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/task_manager.go:160 +0x4c7
github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).overseeTask()
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/task_manager.go:132 +0x945
github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).overseeTask()
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/task_manager.go:132 +0x945

Previous read at 0x00c4203f2540 by goroutine 175:
runtime.chansend()
/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/chan.go:122 +0x0
github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).CheckTaskState()
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/docker_task_engine.go:363 +0x4bf

Goroutine 183 (running) created at:
github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).startTask()
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/docker_task_engine.go:439 +0xda
github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).AddTask()
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/docker_task_engine.go:589 +0x2a8
github.com/aws/amazon-ecs-agent/agent/engine.TestPauseContaienrHappyPath()
/home/travis/gopath/src/github.com/aws/amazon-ecs-agent/agent/engine/docker_task_engine_test.go:1651 +0x1f2e
testing.tRunner()
/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610 +0xc9

Goroutine 175 (running) created at:
github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).waitSteady()
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/task_manager.go:224 +0x4bf
github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).overseeTask()
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/task_manager.go:124 +0x22f
github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).overseeTask()
github.com/aws/amazon-ecs-agent/agent/engine/_test/_obj_test/task_manager.go:132 +0x945
==================
```

**Comment by petderek** [comment] 2017-10-23 21:47
I'm unable to reproduce this. It looks like its failing in between tests though (the only time we close the channel).

**Comment by richardpen** [comment] 2017-10-23 23:29
Based on the logs above, it looks like the following race condition is happening:
In `CheckTaskState`(agent/engine/docker_task_engine.go), for some unknown reason, the [write](https://github.com/aws/amazon-ecs-agent/blob/master/agent/engine/docker_task_engine.go#L302) to the channel doesn't happen immediately until we try to close the channel. We have already has the logic to [clear](https://github.com/aws/amazon-ecs-agent/blob/master/agent/engine/task_manager.go#L638) this channel, which seems doesn't work in this case. In order to fix this data race we may need to add a waitgroup for `dockerMessage` channel, so that we know it was cleared and then we can close the channel. 

But I could be wrong, there also can be something wrong in the test code, but we need the log for the failed test. So I'd say we keep an eye on this and  try to reproduce this so that we can take another deep look with the logs. Any thoughts?

**Comment by aaithal** [comment] 2018-01-18 20:21
With the modifications in #1164, I've so far been unable to repro this, even with `-count 1000` parameter. Once #1164 gets merged, we can close this one.

**Comment by aaithal** [comment] 2018-01-18 22:00
closing this as #1164 is merged with dev

**Closed by aaithal** 2018-01-18 22:00 UTC
Labels: bug, scope/ECS Agent
