### ISSUE TITLE
ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION does not clean up containers in "created" state

### ISSUE THREAD

**Issue by jhovell** [aws/amazon-ecs-agent#721] opened 2017-03-03 19:51 UTC
Sometimes containers fail to fully start perhaps due to a bug or some transient condition. The containers are not stopped but rather in "created" state. These containers do not get reaped by the ECS Engine task cleanup. This can lead to problems as other containers may not be able to start due to insufficient resources or other resource conflicts.

Example on host that cleans up stopped containers after 10 minutes:

```
[ec2-user@ip-172-31-4-72 ~]$ docker ps -a
CONTAINER ID        IMAGE                                                                          COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                                      NAMES
e3cdf65a36da        redis                                                                          "docker-entrypoint.sh"   16 hours ago        Created                                                                                                                                                                                        redis
....
```

^^ not redis container that was not removed because it somehow got stuck in a "created" state and never successfully started.

**Comment by richardpen** [comment] 2017-03-28 20:56
@jhovell Thanks for reporting this to us, there may be an issue in the ecs-agent which we need to root cause and fix. We will try to reproduce this issue on our side. Before that, in any chance do you still have the related ecs-agent and docker logs that will help us a lot to find the cause. Or do you have a fixed path to reproduce this, like the configuration of ecs-agent, the workload and the instance type. If you have any of these information available, could you publish here or send to me: penyin (at) amazon.com.

thanks,
Richard

**Comment by aaithal** [comment] 2017-04-26 15:40
@jhovell We have a hypothesis for how a container can get to this state. If the ECS Agent times out waiting for container to be created and if the task is stopped and gets cleaned before docker daemon completes the container create operation, the container effectively gets orphaned from a cleanup perspective because ECS Agent thinks that it has already cleaned up the task. However, this seems like a rare and a very edge case. If you could provide more information about:

1. how badly this is affecting your workload and 
2. ECS Agent logs, 

we can confirm this hypothesis and work towards a fix for this. Increasing the create timeout, investigating why the container creating is taking such a long time are all possible mitigations here and getting more information would help us in deciding which is the best course of action here. Please let us know by sharing the relevant information. You can email to @richardpen or to me: aithal at amazon dot com.

Thanks,
Anirudh

**Comment by samuelkarp** [comment] 2017-05-18 21:10
@jhovell Are you able to share the information that @richardpen asked for?

**Comment by jhovell** [comment] 2017-05-18 22:43
@samuelkarp @richardpen @aaithal 

1. No, it's not affecting our production workload. This was discovered during container development when a container was configured in such a way that it could not start and would only get created. I am searching for some detail here as to how to reproduce this as I think getting the container stuck at created state was easily reproducible. It was a simple base redis:alpine image that was fed incorrect parameters somehow. I just tried to reproduce with a few ideas I had but cannot currently get a redis container to only 'create' and not 'start'

2. ECS Agent logs on this instance were not preserved since it was not a development machine. Sorry about this.

Other details in case they are useful
c4.2xlarge or m4.2xlarge instance type
task definition contained 2 different containers, redis and a container based on this https://github.com/awslabs/logstash-output-amazon_es/
Latest ECS agent as of when this issue was filed
ECS optimized AMI

**Comment by hltbra** [comment] 2017-11-27 20:44
I am experiencing the same problem, lots of "Created" containers that never ran successfully. I remember seeing a 4min timeout in the ecs-agent logs (docker API didn't respond when the agent tried to start the container).
At the time I didn't find a root cause for why docker was having issues running the containers, but the ecs-agent didn't stop trying to launch new containers and I ended up with 4096 containers that never got cleaned by the ecs-agent.

This happened recently but our logs (local disk) were rotated and I couldn't find what was causing the docker timeout. I will update this ticket with more information once I have it.

**Comment by richardpen** [comment] 2018-01-08 18:45
@hltbra Did you check the instance volume credits when the docker API was timed out? When the EBS volume credits were exhausted docker API will become very slow, so it's possible the Docker API timeout was caused by this. Please also share this information when you encountered the issue again.

Thanks.

**Comment by aaithal** [comment] 2018-01-26 01:02
@hltbra  I'm closing this issue for now. Please let us know if this issue occurs again by sending us the logs and the answer to @richardpen's  EBS question.

**Closed by aaithal** 2018-01-26 01:02 UTC
Labels: bug, more info needed, scope/ECS Agent

**Comment by hltbra** [comment] 2018-01-26 15:22
Thanks, @aaithal and @richardpen. The burst balance was exhausted when I was having issues! I forgot to update this ticket, sorry.

I am trying with @nadlerjessie a solution to use a variable storage size (gp2) based on the instance type. We know, for example, that m4.large can fit our containers with the default 22GB gp2 without a problem. On the other hand, m4.4xlarge with the same 22GB is a problem, so we'll try something like 66GB for that instance type. We are using Spot Fleets with a diversified group of EC2 instance types and will adjust the device mappings accordingly to how many of our containers each instance type can work with.

**Comment by aaithal** [comment] 2018-01-26 15:53
Thanks for getting back to us with that info! Glad to hear that you have resolved that particular issue.
