### ISSUE TITLE
Logging to Graylog

### ISSUE THREAD

**Issue by 2ndalpha** [aws/amazon-ecs-agent#238] opened 2015-10-28 08:52 UTC
I would like to send my logs to Graylog, in the task definition there is an option to set logDriver to "gelf".
Running the task from EC2 console fails with error:
Run tasks failed
Reasons : ATTRIBUTE

gelf logging driver was added to Docker v1.8, ecs agent currently supports Docker v1.7 (https://github.com/aws/amazon-ecs-agent/issues/221)
Is there any timeframe when Docker 1.8 support will be added?

**Comment by euank** [comment] 2015-10-29 22:08
Although our default AMI comes with Docker 1.7, you should be able to run the Agent under a newer version of Docker. In that case, it should register with the ability to use the `gelf` driver.

We've also heard other requests for updating the version of Docker we provide on our AMI and are tracking that as well.

Best,
Euan

**Comment by hridyeshpant** [comment] 2015-11-11 13:46
i am facing similar issue with fluentd ,and getting "was unable to place a task because the resources could not be found" ,and while running the task from AWS UI , i am getting 
Run tasks failed
Reasons : ATTRIBUTE
my task definition json file is below, could some one please point me ,what i am missing here ?
{
  "requiresAttributes": [
    {
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.fluentd"
    },
    {
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    }
  ],
  "taskDefinitionArn": "arn:aws:ecs:us-west-2:408096535527:task-definition/specimen-dw-docker-ecs-service:1741",
  "status": "ACTIVE",
  "revision": 1741,
  "containerDefinitions": [
    {
      "volumesFrom": [],
      "memory": 1024,
      "extraHosts": null,
      "dnsServers": null,
      "disableNetworking": null,
      "dnsSearchDomains": null,
      "portMappings": [
        {
          "hostPort": 10010,
          "containerPort": 8080,
          "protocol": "tcp"
        }
      ],
      "hostname": null,
      "essential": true,
      "entryPoint": null,
      "mountPoints": [],
      "name": "specimen-dw-docker-ecs-service",
      "ulimits": null,
      "dockerSecurityOptions": null,
      "environment": [
        {
          "name": "AWS_REGION",
          "value": "us-west-2"
        },
        {
          "name": "ECS_CLUSTER_NAME",
          "value": "int-test"
        },
        {
          "name": "ACTIVE_VERSION",
          "value": "bd2c73915dbdce4ea41efcdc6a82c9273312179d"
        },
        {
          "name": "EXPEDIA_DNS_ZONE",
          "value": "int.expedia.com"
        },
        {
          "name": "APP_NAME",
          "value": "specimen-dw-docker-ecs-service"
        },
        {
          "name": "JOB_NUMBER",
          "value": "732"
        },
        {
          "name": "EXPEDIA_ENVIRONMENT",
          "value": "int"
        },
        {
          "name": "ROLLBACK_VERSION",
          "value": ""
        },
        {
          "name": "ROLLBACK_REVISION",
          "value": ""
        }
      ],
      "links": null,
      "workingDirectory": null,
      "readonlyRootFilesystem": null,
      "image": "*****",
      "command": null,
      "user": null,
      "dockerLabels": null,
      "logConfiguration": {
        "logDriver": "fluentd",
        "options": null
      },
      "cpu": 512,
      "privileged": null
    }
  ],
  "volumes": [],
  "family": "specimen-dw-docker-ecs-service"
} 

we are using amzn-ami-2015.09.a-amazon-ecs-optimized and 
docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d/1.7.1
OS/Arch (server): linux/amd64

**Comment by samuelkarp** [comment] 2015-11-11 17:16
@hridyeshpant The `fluentd` logging driver was added in [Docker 1.8.0](https://github.com/docker/docker/blob/master/CHANGELOG.md#180-2015-08-11).  Since you're running Docker 1.7.1, the logging driver is not available.

**Comment by hridyeshpant** [comment] 2015-11-11 21:28
thanks @samuelkarp , can you please tell me which AWS ami should have  Docker 1.8.0 version , i ma using amzn-ami-2015.09.a-amazon-ecs-optimized ami?

**Comment by hridyeshpant** [comment] 2015-11-12 02:36
i installed docker 1.8.1 in ECS instances manually and restart ecs agent service, AWS ECS UI also showing docker version 1.8.1.
but still getting same issue when running the task from UI, not giving much details about the failure.
Run tasks failed
Reasons : ATTRIBUTE

**Comment by sfussenegger** [comment] 2015-11-12 11:20
I can confirm this issue. Just installed docker 1.9.0

```
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

I've added `awslogs` to the available logging drivers:

```bash
cat >> /etc/ecs/ecs.config <<'ECS_CONFIG'
ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","syslog","awslogs"]
ECS_CONFIG
```

output 

```
2015-11-12T11:05:41Z [INFO] Starting Agent: Amazon ECS Agent - v1.6.0 (34235e3)
2015-11-12T11:05:41Z [INFO] Loading configuration
2015-11-12T11:05:41Z [CRITICAL] Error loading config: Invalid logging drivers: awslogs
```

the output is actually copied from a CloudWatch stream, so I'm pretty confident the logging driver works ;)

**Comment by samuelkarp** [comment] 2015-11-12 17:39
@hridyeshpant Did you add `fluentd` to `ECS_AVAILABLE_LOGGING_DRIVERS` as per @euank's guidance above?

@sfussenegger The Agent does not currently support the `awslogs` logging driver.

**Comment by hridyeshpant** [comment] 2015-11-16 00:52
yes @samuelkarp  i am able to run docker command in system but while running via task definition, it is throwing "Reasons : ATTRIBUTE" error
below is my ecs.config data,
>>cat /etc/ecs/ecs.config
ECS_CLUSTER=int-test
ECS_ENGINE_AUTH_TYPE=dockercfg
ECS_AVAILABLE_LOGGING_DRIVERS=fluentd
ECS_LOGLEVEL=debug
ECS_ENGINE_AUTH_DATA={"***":{"auth":"***","email":"**"}}

**Comment by samuelkarp** [comment] 2015-11-16 03:08
@hridyeshpant The `ECS_AVAILABLE_LOGGING_DRIVERS` environment variable needs to be set as a JSON array.  You'll want to change it to be `ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","syslog","fluentd"]` or similar.  When you've set this properly (and with an up-to-date version of the AWS CLI) you can see the logging drivers as attributes when calling DescribeContainerInstances as follows:

```
"attributes": [
    {
        "name": "com.amazonaws.ecs.capability.logging-driver.fluentd"
    }
],
```

**Comment by hridyeshpant** [comment] 2015-11-17 01:12
@samuelkarp thanks , i will update and try this.

**Comment by samuelkarp** [comment] 2015-12-09 20:01
Closing for now, please let us know if you continue to have problems.

**Closed by samuelkarp** 2015-12-09 20:01 UTC

**Comment by hridyeshpant** [comment] 2015-12-17 13:31
@samuelkarp any idea when we have ECS AMI with latest version of docker, the current AMI have docker version 1.7.1 which is quite old.

**Comment by sfussenegger** [comment] 2015-12-17 13:46
@hridyeshpant as a workaround you could simply [replace the executable](https://github.com/molindo/molindo-amis/blob/master/ecs-base/build.sh#L5) or use [our AMIs](https://github.com/molindo/molindo-amis/tree/master/ecs-base)

**Comment by hridyeshpant** [comment] 2015-12-17 13:52
@sfussenegger i am afraid of using docker 1.9.1 until we have office release AMI with fix https://github.com/docker/docker/issues/18314

**Comment by samuelkarp** [comment] 2015-12-17 21:54
@hridyeshpant, we are currently investigating the performance problems with Docker 1.9.1 (docker/docker#18314 is the issue I reported upstream) and are looking at mitigations that would enable us to release the Amazon ECS-optimized AMI without significant performance impact.  While I cannot give you a specific timeline for an ECS-optimized AMI, we have definitely heard the demand for newer versions of Docker.  To that point, we have [released Docker 1.9.1 for the Amazon Linux AMI](https://forums.aws.amazon.com/ann.jspa?annID=3431), which you can choose to install on your instances if you so desire.  There are a few things you can do to mitigate the performance impact with Docker 1.9.1 that come with various trade-offs:

* Use `overlay` as the storage driver instead of `devicemapper`.  The `overlay` storage driver is not currently the default in Docker (see https://github.com/docker/docker/pull/12354 for some good general discussion; there are issues with unix sockets, opening files in different modes, and inode usage), but if none of the known issues are problematic for you it might be a good option.  Using `overlay` has resolved the performance issues when I've tried it, but the known issues prevent us from choosing it by default today.  You can do this by adding `-s overlay` to the `OPTIONS` line in `/etc/sysconfig/docker`, stopping the Docker daemon with `sudo service docker stop`, deleting the daemon storage with `sudo rm -rf /var/lib/docker` (warning: this will remove all existing containers and all cached images), and restarting Docker with `sudo service docker start`.  You can then verify the change by looking at the output of `docker info`.
* If you don't feel comfortable with `overlay`, you can instead set `devicemapper` to change the container size back to 10G.  In Docker 1.9, the default size is 100G, but Docker 1.7 has a default size of 10G.  The amount of time seems related to the container base size, so if you're able to go back to a size of 10G the performance differences seem minimal between Docker 1.7 and Docker 1.9.  You can do this by adding `--storage-opt dm.basesize=10G` to the `OPTIONS` line in `/etc/sysconfig/docker`, stopping the Docker daemon with `sudo service docker stop`, deleting the daemon storage with `sudo rm -rf /var/lib/docker` (warning: this will remove all existing containers and all cached images), and restarting Docker with `sudo service docker start`.  You can then verify the change by looking at the output of `docker info`.
* If you don't want to change the container base size, you can set `devicemapper` to change the block size from `64K` to `512K`.  Reducing the number of blocks that the devicemapper driver needs to manage seems to help performance at the cost of additional disk space, so instead of performance issues you may run out of disk space.  You can do this by adding `--storage-opt dm.blocksize=512K` to the `OPTIONS` line in `/etc/sysconfig/docker`, stopping the Docker daemon with `sudo service docker stop`, deleting the daemon storage with `sudo rm -rf /var/lib/docker` (warning: this will remove all existing containers and all cached images), and restarting Docker with `sudo service docker start`.  You can then verify the change by looking at the output of `docker info`.
* A different option is to set `devicemapper` to stop discarding blocks when containers are removed.  Since much of the concern around performance seems to be block-related operations (including discard), I've seen performance improve with this option.  While performance seems to improve and Docker is able to reuse the disk space, this has the effect of Docker-allocated space not being freed back for use by other programs.  Similar to the block size change, this can cause disk consumption concerns.  You can do this by adding `--storage-opt dm.blkdiscard=false` to the `OPTIONS` line in `/etc/sysconfig/docker`, stopping the Docker daemon with `sudo service docker stop`, deleting the daemon storage with `sudo rm -rf /var/lib/docker` (warning: this will remove all existing containers and all cached images), and restarting Docker with `sudo service docker start`.  You can then verify the change by looking at the output of `docker info`.
* Docker's [recommended](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configuring-docker-with-device-mapper) approach for configuring `devicemapper` is to use `direct-lvm` mode.  This mode uses a separate block device to create the devicemapper thin pool used for storage.  Performance does seem significantly better with this configuration, but you do need an additional block device available in order to use this mode.  There are [manual instructions](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production) for configuring this mode, but I've also found [docker-storage-setup](https://github.com/projectatomic/docker-storage-setup) to be somewhat easier.

I hope this information helps you make an informed decision.

**Comment by hridyeshpant** [comment] 2016-01-13 20:45
Thanks @samuelkarp .

**Comment by wr0ngway** [comment] 2016-01-20 00:39
@samuelkarp does this mean we can now use awslogs driver by setting ECS_AVAILABLE_LOGGING_DRIVERS in ecs.config and the equivalent logConfiguration in the task def?

**Comment by samuelkarp** [comment] 2016-01-20 00:43
No, `awslogs` is not supported as a log driver in task definitions today.  There's some discussion in https://github.com/aws/amazon-ecs-agent/pull/251 around what needs to be resolved before it can be made available.

**Comment by sfussenegger** [comment] 2016-01-20 09:03
@wr0ngway it's however possible to make `awslogs` the default. we use this in a non-production environment to customize the docker config:

    echo "OPTIONS=\"\${OPTIONS} --log-driver=awslogs --log-opt awslogs-region=${region} --log-opt awslogs-group=${group}\"" >> /etc/sysconfig/docker
    /etc/init.d/docker restart

(we use instance tags to pass in the group which is created using  a CloudFormation template)

I'm sure there is a really nice integrated logging solution coming up though, right @samuelkarp ? ;)

**Comment by wr0ngway** [comment] 2016-01-20 12:30
cool, thanks, I'll give that a shot

**Comment by ox0** [comment] 2016-03-20 19:17
I found and tested this work around does work for the purpose.
link:
https://github.com/aws/amazon-ecs-agent/issues/238

code:
echo "OPTIONS=\"\${OPTIONS} --log-driver=awslogs --log-opt awslogs-region=${region} --log-opt awslogs-group=${group}\"" >> /etc/sysconfig/docker
/etc/init.d/docker restart

Thanks to Stefan Fussenegger

Alex

**Comment by jhovell** [comment] 2016-04-15 22:26
@samuelkarp any plans for the agent to support awslogs? @ox0 :+1: actually tried this first, got it working, and then was really surprised there is no way to configure logging drivers at the container level via ECS. The only alternative I've seen documented by Amazon is really convoluted & requires every task definition to be aware of this special logging configuration... rather leaky abstraction and a lot of complex overhead (extra running containers, writing to disk...) vs. using the built in Docker driver.

https://blogs.aws.amazon.com/application-management/post/TxFRDMTMILAA8X/Send-ECS-Container-Logs-to-CloudWatch-Logs-for-Centralized-Monitoring

And of course the awslogs logging Driver from Docker is a little lacking as well as there is currently no way to use variables in your log group / log stream name, making it impossible to separate different container logs into different log groups to use appropriate log filters for sending to another service like Elasticsearch Service:

http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/CWL_ES_Stream.html

Somewhat relevant/related open Docker issue:

https://github.com/docker/docker/issues/17747

Seems like both these solutions are 98% of the way there, but fail to deliver for lack of a small enhancement (customized log group names or agent supporting awslogs driver). 

Oh, PS. when modifying task definitions in the ECS GUI, I accidentally used an incorrect awslogs driver option and got this error implying ECS is somehow aware of the awslogs driver since it validated that I needed to provide awslogs-group
![screen shot 2016-04-15 at 3 22 39 pm](https://cloud.githubusercontent.com/assets/1376570/14576476/3f4164bc-031e-11e6-87fd-b82cdfae545e.png)

**Comment by samuelkarp** [comment] 2016-04-16 00:07
@jhovell I replied to you on https://github.com/aws/amazon-ecs-agent/issues/379.

**Comment by fullstackctp** [comment] 2023-12-06 09:07
> @hridyeshpant Did you add `fluentd` to `ECS_AVAILABLE_LOGGING_DRIVERS` as per @euank's guidance above?
> 
> @sfussenegger The Agent does not currently support the `awslogs` logging driver.

where can we find ECS_AVAILABLE_LOGGING-DRIVER OPTION?
