### ISSUE TITLE
Amazon ECS agent Version: 1.46.0 is not working

### ISSUE THREAD

**Issue by kodeeshm** [aws/amazon-ecs-agent#2679] opened 2020-10-16 13:49 UTC
### Summary
Did you guys force Amazon ECS agent version 1.46.0 ?
We do not see official release information about 1.46.0 but our ECS clusters using windows agents started to look for 1.46.0 and fails. Eventually not getting attached to the cluster and causes all the services to go down.

### Expected Behavior
Amazon ECS Agent service to start automatically and attach to respective ECS cluster

### Observed Behavior
Amazon ECS Agent service fails to get started.

### Environment Details
AMI Name:
Windows_Server-2019-English-Core-ECS_Optimized-2020.10.14
Windows_Server-2019-English-Core-ECS_Optimized-2020.09.09

### Supporting Log Snippets
From the ecs-agent.log
level=error time=2020-10-16T12:51:18Z msg="Unable to determine valid domain join: <nil>" module=parse_windows.go
.
.
.
level=info time=2020-10-16T12:51:18Z msg="Unable to get Docker client for version 1.17: version detection using MinAPIVersion: unsupported version: 1.17" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:18Z msg="Unable to get Docker client for version 1.18: version detection using MinAPIVersion: unsupported version: 1.18" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:18Z msg="Unable to get Docker client for version 1.19: version detection using MinAPIVersion: unsupported version: 1.19" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:18Z msg="Unable to get Docker client for version 1.20: version detection using MinAPIVersion: unsupported version: 1.20" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:18Z msg="Unable to get Docker client for version 1.21: version detection using MinAPIVersion: unsupported version: 1.21" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:18Z msg="Unable to get Docker client for version 1.22: version detection using MinAPIVersion: unsupported version: 1.22" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:18Z msg="Unable to get Docker client for version 1.23: version detection using MinAPIVersion: unsupported version: 1.23" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:23Z msg="Loading configuration" module=agent.go
level=error time=2020-10-16T12:51:23Z msg="Unable to determine valid domain join: <nil>" module=parse_windows.go
level=info time=2020-10-16T12:51:23Z msg="Amazon ECS agent Version: 1.46.0, Commit: 863f2227" module=agent.go
level=info time=2020-10-16T12:51:23Z msg="Unable to get Docker client for version 1.17: version detection using MinAPIVersion: unsupported version: 1.17" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:23Z msg="Unable to get Docker client for version 1.18: version detection using MinAPIVersion: unsupported version: 1.18" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:23Z msg="Unable to get Docker client for version 1.19: version detection using MinAPIVersion: unsupported version: 1.19" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:23Z msg="Unable to get Docker client for version 1.20: version detection using MinAPIVersion: unsupported version: 1.20" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:23Z msg="Unable to get Docker client for version 1.21: version detection using MinAPIVersion: unsupported version: 1.21" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:23Z msg="Unable to get Docker client for version 1.22: version detection using MinAPIVersion: unsupported version: 1.22" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:23Z msg="Unable to get Docker client for version 1.23: version detection using MinAPIVersion: unsupported version: 1.23" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:53Z msg="Loading configuration" module=agent.go
level=error time=2020-10-16T12:51:53Z msg="Unable to determine valid domain join: <nil>" module=parse_windows.go
level=info time=2020-10-16T12:51:53Z msg="Amazon ECS agent Version: 1.46.0, Commit: 863f2227" module=agent.go
level=info time=2020-10-16T12:51:53Z msg="Unable to get Docker client for version 1.17: version detection using MinAPIVersion: unsupported version: 1.17" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:53Z msg="Unable to get Docker client for version 1.18: version detection using MinAPIVersion: unsupported version: 1.18" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:53Z msg="Unable to get Docker client for version 1.19: version detection using MinAPIVersion: unsupported version: 1.19" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:53Z msg="Unable to get Docker client for version 1.20: version detection using MinAPIVersion: unsupported version: 1.20" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:53Z msg="Unable to get Docker client for version 1.21: version detection using MinAPIVersion: unsupported version: 1.21" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:53Z msg="Unable to get Docker client for version 1.22: version detection using MinAPIVersion: unsupported version: 1.22" module=sdkclientfactory.go
level=info time=2020-10-16T12:51:53Z msg="Unable to get Docker client for version 1.23: version detection using MinAPIVersion: unsupported version: 1.23" module=sdkclientfactory.go
level=info time=2020-10-16T12:52:53Z msg="Loading configuration" module=agent.go

**Comment by kodeeshm** [comment] 2020-10-16 14:35
More information about error,
2020-10-16T14:07:27Z - [INFO]:Starting the AmazonECS service...
Start-Service : Failed to start service 'Amazon ECS (AmazonECS)'.
At C:\Program Files\WindowsPowerShell\Modules\ECSTools\ECSTools.psm1:667 char:5
+     Start-Service -Name $Script:ECSService
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand

**Comment by ellenthsu** [comment] 2020-10-16 15:43
Thanks for reporting this issue, we're looking into the root cause now

**Comment by ubhattacharjya** [comment] 2020-10-16 21:03
Hi kodeeshm@,

We have rolled back the latest ECS agent version for Windows AMIs to 1.45.0 in all regions.
I will close this issue. Kindly reopen if you face any more issues.

Apologies for your inconvenience.

**Closed** 2020-10-16 21:03 UTC

**Comment by kodeeshm** [comment] 2020-10-17 07:41
Thank you !
Can you please confirm if we are fine to go with following as usual ?

Initialize-ECSAgent -Cluster <ecs_cluster_name> -EnableTaskIAMRole -LoggingDrivers '["json-file","awslogs"]'

Even if this brings latest, it should go fine without any intervention. Please confirm, so that we can plan for an alternate like following, thanks !

Initialize-ECSAgent -Cluster <ecs_cluster_name> -Version 1.45.0 -EnableTaskIAMRole -LoggingDrivers '["json-file","awslogs"]'

**Comment by ubhattacharjya** [comment] 2020-10-19 20:16
Hi @kodeeshm ,

Initialize-ECSAgent -Cluster <ecs_cluster_name> -EnableTaskIAMRole -LoggingDrivers '["json-file","awslogs"]' - This will start the ECS agent version 1.45.0 on instances using Windows ECS Optimized AMIs.

Thanks,
Utsa

**Comment by kodeeshm** [comment] 2020-12-21 09:31
> Hi @kodeeshm ,
> 
> Initialize-ECSAgent -Cluster <ecs_cluster_name> -EnableTaskIAMRole -LoggingDrivers '["json-file","awslogs"]' - This will start the ECS agent version 1.45.0 on instances using Windows ECS Optimized AMIs.
> 
> Thanks,
> Utsa

Thank you !
