### ISSUE TITLE
ECS Agent loses connectivity right away and reboots host on docker stop

### ISSUE THREAD

**Issue by sathiyas** [aws/amazon-ecs-agent#138] opened 2015-07-19 04:35 UTC
I have multiple problems. I am behind corp proxy and also using private insecure registry. I am starting host docker with 'other_args="--insecure-registry option and am able to connect to my registry. I am passing proxy info to ECS Agent through --env during docker RUN command. If I don't pass proxy, the agent never came up, after proxy is set through --env, agent at least came up.

I could see the ECS Cluster in ECS console showing the newly launched instance. The agent started as connected = true.  Less than a min or so, Agent loses connectivity. 

When I issue docker stop, the host server crashes and reboots consistently.  

The proxy is right and I could curl form host using Proxy

My docker run command

docker run --name ecs-agent \
--detach=true \
--env http_proxy={url} \
--env https_proxy={url} \
--volume=/var/run/docker.sock:/var/run/docker.sock \
--volume=/var/log/ecs/:/log \
--publish=127.0.0.1:51678:51678 \
--volume=/var/lib/ecs/data:/data \
--env=ECS_LOGFILE=/log/ecs-agent.log \
--env=ECS_LOGLEVEL=info \
--env=ECS_DATADIR=/data \
--env=ECS_CLUSTER=chassis \
amazon/amazon-ecs-agent

logs below.

2015-07-19T04:31:35Z [INFO] Starting Agent: Amazon ECS Agent - v1.3.0 (097e4af)
2015-07-19T04:31:35Z [INFO] Loading configuration
2015-07-19T04:31:35Z [INFO] Checkpointing is enabled. Attempting to load state
2015-07-19T04:31:35Z [INFO] Loading state! module="statemanager"
2015-07-19T04:31:35Z [INFO] Registering Instance with ECS
2015-07-19T04:31:35Z [INFO] Registered! module="api client"
2015-07-19T04:31:35Z [INFO] Registration completed successfully. I am running as 'arn:aws:ecs:us-east-1:685250009713:container-instance/48970dc9-cdb2-4216-8808-dcb154360724' in cluster 'chassis'
2015-07-19T04:31:35Z [INFO] Saving state! module="statemanager"
2015-07-19T04:31:35Z [INFO] Beginning Polling for updates
2015-07-19T04:31:36Z [INFO] Creating poll dialer module="ws client" host="ecs-a-2.us-east-1.amazonaws.com"
2015-07-19T04:31:39Z [ERROR] Error connecting to ACS: dial tcp 54.239.20.16:443: i/o timeout module="acs handler"
2015-07-19T04:31:39Z [INFO] Error from acs; backing off module="acs handler" err="dial tcp 54.239.20.16:443: i/o timeout"
2015-07-19T04:31:40Z [INFO] Creating poll dialer module="ws client" host="ecs-a-2.us-east-1.amazonaws.com"
2015-07-19T04:31:43Z [ERROR] Error connecting to ACS: dial tcp 54.239.20.16:443: i/o timeout module="acs handler"
2015-07-19T04:31:43Z [INFO] Error from acs; backing off module="acs handler" err="dial tcp 54.239.20.16:443: i/o timeout"
2015-07-19T04:31:46Z [INFO] Creating poll dialer module="ws client" host="ecs-a-2.us-east-1.amazonaws.com"
2015-07-19T04:31:46Z [INFO] Saving state! module="statemanager"
2015-07-19T04:31:49Z [ERROR] Error connecting to ACS: dial tcp 54.239.20.16:443: i/o timeout module="acs handler"
2015-07-19T04:31:49Z [INFO] Error from acs; backing off module="acs handler" err="dial tcp 54.239.20.16:443: i/o timeout"
2015-07-19T04:31:54Z [INFO] Creating poll dialer module="ws client" host="ecs-a-2.us-east-1.amazonaws.com"
2015-07-19T04:31:57Z [ERROR] Error connecting to ACS: dial tcp 54.239.20.16:443: i/o timeout module="acs handler"
2015-07-19T04:31:57Z [INFO] Error from acs; backing off module="acs handler" err="dial tcp 54.239.20.16:443: i/o timeout"
2015-07-19T04:32:05Z [INFO] Creating poll dialer module="ws client" host="ecs-a-2.us-east-1.amazonaws.com"
2015-07-19T04:32:08Z [ERROR] Error connecting to ACS: dial tcp 54.239.20.16:443: i/o timeout module="acs handler"
2015-07-19T04:32:08Z [INFO] Error from acs; backing off module="acs handler" err="dial tcp 54.239.20.16:443: i/o timeout"
2015-07-19T04:32:25Z [INFO] Creating poll dialer module="ws client" host="ecs-a-2.us-east-1.amazonaws.com"
2015-07-19T04:32:28Z [ERROR] Error connecting to ACS: dial tcp 54.239.20.16:443: i/o timeout module="acs handler"
2015-07-19T04:32:28Z [INFO] Error from acs; backing off module="acs handler" err="dial tcp 54.239.20.16:443: i/o timeout"

**Comment by euank** [comment] 2015-07-19 22:10
I commented regarding the proxy not working in #23. The error pattern you're seeing there is just due to the ECS Agent not supporting proxying all necessary connections.

I'd be interested in hearing more about the host crashing bit. Are you using the ECS Optimized AMI? Does `docker stop` for a different container cause it, or just the ECS Agent?
It's possible syslog or dmesg could have relevant information.

**Comment by euank** [comment] 2015-07-31 21:07
I'm closing this as a duplicate of #23.

**Closed by euank** 2015-07-31 21:07 UTC
