### ISSUE TITLE
ECS agent spins up new containers when EC2 instance is in Terminating:Wait state

### ISSUE THREAD

**Issue by dblackdblack** [aws/amazon-ecs-agent#186] opened 2015-08-29 23:10 UTC
ECS continues to try to spin up replacement containers for containers that I'm killing off after my EC2 instance has entered Terminating:Wait state.  I set up lifecycle hooks (http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/adding-lifecycle-hooks.html) so that I can cleanly scale down my EC2 instances given that my containers take longer than 30 sec to stop.  It doesn't help matters if ECS keeps trying to spin up new containers on the same box that I'm trying to decommission.

Please honor the Terminating:Wait state and stop spinning up containers on EC2 instances that are in the process of being destroyed.

Thank you so very much :smile_cat:

**Comment by samuelkarp** [comment] 2015-12-31 19:21
Thanks for the details of your use case.  I'm closing this as a duplicate of #130.

**Closed by samuelkarp** 2015-12-31 19:21 UTC
Labels: feature request
