### ISSUE TITLE
ecs-agent container becomes unhealthy

### ISSUE THREAD

**Issue by yashshanker** [aws/amazon-ecs-agent#2802] opened 2021-01-29 21:23 UTC
### Summary
I have multiple ubuntu based ECS container instances and the `ecs-agent` becomes `unhealthy` on the ones running the tasks.

### Description
I have multiple ubuntu based ECS container instances and the `ecs-agent` becomes `unhealthy` on the ones running the tasks.

Becomes healthy again if I restart the `ecs-agent` container.

### Expected Behavior

1. Command:
```docker exec -it ecs-agent /agent --healthcheck```
Output:
```no output if execution succeeds```

2. Command : 
```curl -s http://localhost:51678/v1/metadata | python -mjson.tool```
Output:
```
{
"Cluster": "clusterName",
"ContainerInstanceArn": "arn:aws:ecs:ap-south-1:something:container-instance/something/something",
"Version": "Amazon ECS Agent - v1.50.0 (90ccb1d4)"
}
```
### Observed Behavior
1. Command:
```docker exec -it ecs-agent /agent --healthcheck```
Output:
```command times out```

2. Command : 
```curl -s http://localhost:51678/v1/metadata | python -mjson.tool```
Output:
```
level=error time=2021-01-29T20:28:52Z msg="health check [HEAD http://localhost:51678/v1/metadata] failed with error: Head \"http://localhost:51678/v1/metadata\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" module=healthcheck.go
```

### Environment Details

```docker info```
Output
```
Client:
 Debug Mode: false

Server:
 Containers: 19
  Running: 9
  Paused: 0
  Stopped: 10
 Images: 8
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: elastic/elastic-logging-plugin:7.9.3
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: amazon-ecs-volume-plugin local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1029-aws
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 15.35GiB
 Name: ip-10-55-13-144
 ID: PMT3:DCQG:MS5X:UMY6:IXDK:MWZF:3PSV:UQFL:CI4Q:USLO:PNDE:L55C
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
```df -h```
Output
```
Filesystem      Size  Used Avail Use% Mounted on
udev            7.7G     0  7.7G   0% /dev
tmpfs           1.6G  1.7M  1.6G   1% /run
/dev/nvme0n1p1   30G  7.5G   22G  26% /
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/loop0       29M   29M     0 100% /snap/amazon-ssm-agent/2012
/dev/loop1      2.0G  6.1M  1.8G   1% /tmp
/dev/loop2       98M   98M     0 100% /snap/core/10185
/dev/loop3       98M   98M     0 100% /snap/core/10583
/dev/loop4       56M   56M     0 100% /snap/core18/1944
/dev/loop5       33M   33M     0 100% /snap/amazon-ssm-agent/2996
tmpfs           1.6G     0  1.6G   0% /run/user/1000
```

### Supporting Log Snippets
```
level=error time=2021-01-29T20:13:54Z msg="health check [HEAD http://localhost:51678/v1/metadata] failed with error: Head \"http://localhost:51678/v1/metadata\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" module=healthcheck.go
```

**Comment by fierlion** [comment] 2021-01-30 00:08
Are you using https://github.com/aws/amazon-ecs-init/tree/master/packaging/ubuntu-trusty to oversee the ecs-agent?
Our support for Ubuntu has lapsed (you can see that the latest updates were ~4 years ago)

We recommend using Docker version 19.03.13ce.

Can you use the ecs-logs-collector on one of the affected container instance and send the logs to ecs-agent-external@amazon.com?  This would help us get a deeper picture of what might be happening.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html

**Comment by yashshanker** [comment] 2021-01-30 06:29
Hey @fierlion , I've used [https://docs.aws.amazon.com/AmazonECS/latest/developerguide/example_user_data_scripts.html](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/example_user_data_scripts.html) to create ECS compatible custom Ubuntu AMI.

I've sent the email with required attachments.

**Comment by fierlion** [comment] 2021-02-01 17:17
I received the logs @yashshanker.  Thank you.

**Comment by fierlion** [comment] 2021-02-02 01:10
https://github.com/aws/amazon-ecs-init/pull/390 <- we're working to add better support for Debian.

The ecs-agent errors that I'm seeing in your host are mostly related to the metadata endpoint `http://localhost:51678/v1/metadata`, and a general range of errors related to networking.

Your docker daemon logs have quite a few errors showing up.

I see your docker daemon has been running for a while.  Have you noticed any change in behavior on this particular host over time?  Has the ecs-agent become unhealthy regularly over the full lifetime of this host or are the issues more frequent lately?

In the meantime, is it possible for you to use one of the ECS-supported Amazon Linux Images or even better, the ECS Optimized AMI (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html) ?

**Comment by yashshanker** [comment] 2021-02-02 10:37
As i was also told by the aws support, it is going to unhealthy state because of failed healthcheck. There is actually no other error in the logs. And this happens at exactly once in every 24hours, and not triggered by any other error event except a timeout on healthcheck (metadata endpoint).

And we are not using ecs-init natively on debian. We are just using the ecs-agent docker image. 

There is actually no other problem that I face on the host except this. Containers run perfectly fine and there's never a resource crunch. 

My service in the containers only give errors while accessing the IAM profile endpoint to get access to other AWS services, that too only when the ecs-agent is in unhealthy state, and the container instance loses connection to the ECS cluster, which hinders deployments and auto-scaling of tasks.

I understand that if we don't find any solution, I'll have to go back to using ECS optimised AMIs, but I preferred Ubuntu and also this issue feels weird, because ecs-init doesn't run natively, but in a container. 

Unless its a problem with either of the below directories, in which case you can clear if the ecs-init binary has some inherent dependency on these host directories.

```
/host/sbin 
/lib 
/lib64 
/usr/lib 
/usr/lib64 
/host/proc 
/sys/fs/cgroup
```

**Comment by mtroianovskyi-g** [comment] 2021-02-03 11:11
Hi @yashshanker, it looks like I also observe a similar or the same issue with Ubuntu + ECS agent v.1.50.0.
In our case, I observed that the `/agent` process with unhealthy status is leaking file descriptors.
```
sudo lsof -p $(pidof '/agent')
```
shows thousands of entries with `sock` and `protocol: TCPv6`.

This could be just the effect of the repeated failed healthchecks.

**Comment by sparrc** [comment] 2021-02-03 17:45
@mtroianovskyi-g could you please provide us with the output of `sudo lsof -p $(pidof '/agent')`, or run the ecs logs collector (https://github.com/aws/amazon-ecs-logs-collector)?

You can email this to us at ecs-agent-external at amazon dot com

**Comment by fierlion** [comment] 2021-02-04 20:33
We check for open file leaks as part of our release process and I don't see any changes in the output for those tests over the last several releases. (I'm not saying this isn't an issue, as our checks use Amazon Linux.)
However, I also don't see evidence of a high number of open files in the debug logs shared by @yashshanker

Several engineers are trying to reproduce this timeout issue from our end but we haven't been able to.  If you have any insight into how you're setting up the instance, or performing the update to agent 1.50, this might help us better track down steps that are leading to the issue.

**Comment by fierlion** [comment] 2021-02-04 23:08
one other question, possibly related.  Can you tell us which version of containerd you're using?
https://github.com/containerd/containerd/issues/4509

**Comment by yashshanker** [comment] 2021-02-09 05:46
@fierlion I'm going to share the AMI with you guys, as tech support also requested. I think that may help you get more from debugging.

**Comment by nilroy** [comment] 2021-02-11 12:06
@fierlion We have been seeing same issue with the ecs-agent docker container v1.50 on our debian 10 ec2 instances. The biggest problem is once ecs-agent gets unhealthy the instance does not work anymore in the cluster. The running container/task keep running but we can't run any deployment. We had never had any such issue before. We have been running ECS for multiple years now and encountered this with v1.50. We had to rollback to ecs-agent docker container  version 1.49 and the issue is gone. So there has to be something related to v1.50.

**Comment by tristanheaven** [comment] 2021-02-11 12:22
I think I've seen the same issue on ECS-optimized Amazon Linux 2 AMI `20210121` and `20210202`.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-ami-versions.html

**Comment by shubham2892** [comment] 2021-02-11 20:14
@tristanheaven Do you have any insight into how can we reproduce the issue on our end?

**Comment by mssokal** [comment] 2021-02-11 22:28
Hi,

Can you confirm if this is what you see in the agent logs?
level=error time=2021-02-09T00:32:31Z msg="health check [HEAD http://localhost:51678/v1/metadata] failed with error: Head \"http://localhost:51678/v1/metadata\<http://localhost:51678/v1/metadata/>": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" module=healthcheck.go

Can you please also check the value on ECS_CHECKPOINT ?

I am currently investigating this issue and appears to be independent of AMI. The issue I am investigating occurs when “ECS_CHECKPOINT=false”, often when there is a deployment going on.

**Comment by sonuGlobality** [comment] 2021-02-12 15:42
today we got the same issue. The curl `http://localhost:51678/v1/metadata` wasn't responding from the host as well.
so, i stop/start the container to resolve the issue.

Any clue why this container stop responding and marked unhealthy in `docker ps` result

```

./ecs-agent.log:22402:level=error time=2021-02-12T15:13:50Z msg="health check [HEAD http://localhost:51678/v1/metadata] failed with error: Head \"http://localhost:51678/v1/metadata\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" module=healthcheck.go
./ecs-agent.log:22403:level=error time=2021-02-12T15:14:46Z msg="health check [HEAD http://localhost:51678/v1/metadata] failed with error: Head \"http://localhost:51678/v1/metadata\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" module=healthcheck.go

```

**Comment by shubham2892** [comment] 2021-02-15 04:56
@sonuGlobality Have you set either of these flags -- `ECS_CHECKPOINT` or `ECS_DATADIR` ?

Any chances you have logs from the failing instance? How frequently this issue is happening for you? What version of Agent are you using?

**Comment by sparrc** [comment] 2021-02-17 23:01
We have been able to reproduce this on agent version 1.50.0 and 1.50.1. We are still trying to find the root cause, but as of now it seems like there are two possible mitigations:
1. downgrade to agent version 1.49.0.
2. If downgrading is not an option, we have found that setting the ECS_CHECKPOINT=true in your ecs config may reduce the likelihood of encountering the issue.

**Comment by sparrc** [comment] 2021-02-19 18:36
this issue has been fixed with PR https://github.com/aws/amazon-ecs-agent/pull/2811, we are currently working on releasing agent version 1.50.2 with this bugfix. We will also be following up with a more permanent fix by replacing our logging library (seelog) with something less locky.

**Comment by sparrc** [comment] 2021-02-23 18:13
1.50.2 is now available and we have confirmed that we are no longer able to reproduce this bug. Please feel free to reopen this issue if you are still seeing the issue after upgrading to agent version 1.50.2.

**Closed by sparrc** 2021-02-23 18:13 UTC
