### ISSUE TITLE
Allow arbitrary `docker run` command flags to be specified

### ISSUE THREAD

**Issue by rthrfrd** [aws/amazon-ecs-agent#128] opened 2015-06-30 17:56 UTC
For example, I've been attempting to container-ize an HDFS cluster. The way nodes are resolved means I need to specify `--net=host` for cluster discovery to work _(there are other ways to get it working too but all require some other flag combination, such as --cap-add, which similarly aren't available)_.

What are the reasons for not being able to specify arbitrary flags? Like some kind of 'advanced' option that is only available when editing the JSON directly perhaps? Without it ECS cannot be used to manage such nodes, which is a shame.

**Comment by Munchery-ReeseLevine** [comment] 2015-06-30 19:02
This is almost exactly the same issue that I opened up a couple hours ago. The idea of making it only editable in the JSON is interesting, but I think having all the options fully documented and available in the task builder might be better. That way people who are just starting to use ECS won't have to hunt around the source code to figure out where they can put command flags, like we had to do :smile:

**Comment by euank** [comment] 2015-07-01 17:49
I agree with @Munchery-ReeseLevine that this is a duplicate of #127.  Closing so we can consolidate discussion there.. Feel free to reopen or add comments there if you think it doesn't capture what you're asking.

**Closed by euank** 2015-07-01 17:49 UTC
