### ISSUE TITLE
ECS Instances stuck with "Agent Disconnected"

### ISSUE THREAD

**Issue by ryzr** [aws/amazon-ecs-agent#4270] opened 2024-08-06 13:52 UTC
### Summary
ECS Instances stuck with "Agent Disconnected". ecs-agent not running.

### Description
Upon checking /var/log/ecs/ecs-init.log, I found that the service was failing and not attempting to auto-restart. Please see logs below.

This issue happened repeatedly for us 100% of the time for every new instance added to the cluster. Simply running `sudo service start ecs` fixed the issue immediately.

Might be worth noting that this AMI is created with Image Builder.

### Expected Behavior
I guess two things -> the "Error connecting to docker" error is new for us. But additionally, would have expected the service to auto-restart.

### Observed Behavior
ECS service exited and did not restart. Seems that it may have exited with code 0?

### Environment Details
Amazon Linux 2023.5.20240730
Linux 6.1.92-99.174.amzn2023.aarch64
arm64
Docker 25.0.5

### Supporting Log Snippets
```
sudo systemctl status ecs
○ ecs.service - Amazon Elastic Container Service - container agent
     Loaded: loaded (/usr/lib/systemd/system/ecs.service; enabled; preset: disabled)
     Active: inactive (dead) since Tue 2024-08-06 13:28:10 UTC; 12min ago
   Duration: 54.440s
       Docs: https://aws.amazon.com/documentation/ecs/
   Main PID: 2326 (code=exited, status=0/SUCCESS)
        CPU: 90ms
```

ecs-init.log
```
level=info time=2024-08-06T13:26:46Z msg="pre-start"
level=info time=2024-08-06T13:26:46Z msg="Successfully created docker client with API version 1.25"
level=info time=2024-08-06T13:26:46Z msg="pre-start: enabling loopback routing"
level=info time=2024-08-06T13:26:46Z msg="pre-start: disabling ipv6 router advertisements"
level=info time=2024-08-06T13:26:46Z msg="pre-start: creating credentials proxy route"
level=info time=2024-08-06T13:26:46Z msg="pre-start: checking ecs agent container image loaded presence"
level=info time=2024-08-06T13:26:46Z msg="pre-start: ecs agent container image loaded presence: true"
level=info time=2024-08-06T13:26:46Z msg="start"
level=info time=2024-08-06T13:26:46Z msg="Successfully created docker client with API version 1.25"
level=info time=2024-08-06T13:26:46Z msg="Container name: /ecs-agent"
level=info time=2024-08-06T13:26:46Z msg="Removing existing agent container ID: 6c4cae2b50810c1592a84c4cc59ba995cd55ab57037ab51fcb5d6722c036be7b"
level=info time=2024-08-06T13:26:46Z msg="Starting Amazon Elastic Container Service Agent"
level=info time=2024-08-06T13:28:04Z msg="Agent exited with code 0"
level=info time=2024-08-06T13:28:04Z msg="stop"
level=info time=2024-08-06T13:28:09Z msg="Error connecting to docker, backing off for 1.024734102s, error: Get \"http://unix.sock/v1.25/version\": read unix @->/run/docker.sock: read: connection reset by peer"
level=info time=2024-08-06T13:28:10Z msg="Successfully created docker client with API version 1.25"
level=info time=2024-08-06T13:28:10Z msg="Stopping Amazon Elastic Container Service Agent"
level=info time=2024-08-06T13:28:10Z msg="Container name: redacted"
level=info time=2024-08-06T13:28:10Z msg="Container name: redacted"
level=info time=2024-08-06T13:28:10Z msg="Container name: redacted"
level=info time=2024-08-06T13:28:10Z msg="Container name: redacted"
level=info time=2024-08-06T13:28:10Z msg="Container name: redacted"
level=info time=2024-08-06T13:28:10Z msg="Container name: redacted"
level=info time=2024-08-06T13:28:10Z msg="Container name: redacted"
level=info time=2024-08-06T13:28:10Z msg="Container name: /ecs-agent"
level=info time=2024-08-06T13:28:10Z msg="Agent is already stopped"
level=info time=2024-08-06T13:28:10Z msg="post-stop"
level=info time=2024-08-06T13:28:10Z msg="Cleaning up the credentials endpoint setup for Amazon Elastic Container Service Agent"
```

FYI will jump on a chat with AWS Support in the morning, just wanted to leave this here overnight in case it gets any commentary.

**Comment by juangc-wavyssa** [comment] 2024-08-08 15:13
Same issue here, for all of our 49 ECS, ECS Instances stuck with "Agent Disconnected". We found that the service was failing and not attempting to auto-restart.

**Comment by danehlim** [comment] 2024-08-09 23:30
Thank you for opening this issue and providing details. Our team is aware of this issue and currently in the process of addressing it as part of https://github.com/aws/amazon-ecs-agent/pull/4233.

**Comment by danehlim** [comment] 2024-08-09 23:32
Thank you for opening this issue and providing details. Our team is aware of this issue and currently in the process of addressing it as part of https://github.com/aws/amazon-ecs-agent/pull/4277.

**Comment by lukemulcahy** [comment] 2024-08-15 11:34
Had a similar issue last few days. ecs-agent stops and is not restarted until manually intervention - starting ecs-agent or restarting ec2-instance. 

We updated our all our ecs-agent to latest version last week. ec2-instances were never restarted. No issues with ecs clusters last week. 

Then yesterday at approx. 03:37UTC half of our ec2-instances' ecs-agents stopped and never restarted until we manually intervened. 

Again today (approx same time) 2 more ec2-instances had a similar failure. 

Interesting the first set of boxes that were restarted had no issues last night. I suspect there might be something related to the update that requires a restart (of ecs-agent). 

There are a few boxes that haven't experienced any issues - so maybe tomorrow night they will also need a restart....

**Comment by atreyd** [comment] 2024-08-16 17:12
Hi All, 
We are also facing the similar issues with ec2 instance getting stuck with "Agent Disconnected" state. The instances neither gets removed nor reconnected automatically and this cause service to go down.  Surprisingly it's happening more frequently in eu-west-1 region.  Multiple clusters had the same problem and left us with many hosts in "Agent Disconnected" state. 

This exists for almost 2 weeks since I opened a case with AWS support, but this still exists.

**Comment by lukemulcahy** [comment] 2024-08-17 18:04
Posting this response from AWS Support here for anyone else who has this issue. ***Either upgrade to 1.86.1 or downgrade to <=1.84***


==========
Overview:
==========
The issue is been observed in ECS, where Agent fails to restart. This is caused by an issue where Agent fails to detect that Docker is restarting and shuts down gracefully and is observed Agents versions between 1.85 and 1.86.

==========
Root cause
==========
At a high level, the behavior change results in the following workflow:
1. Docker service and ECS service are both running
2. Docker service is restarted
3. Restart is NOT propagated to ECS service since there is no configuration set that accomplishes this (such as Requires=)
4. ECS service continues running its workflows and successfully exits cleanly with exit code 0
5. Since Restart=on-failure is set for ECS service and it exited with code 0, ECS service is not restarted and never comes back up

==========
Mitigation
==========
This issue can be mitigated by running "systemctl restart ecs" on the instance whenever Docker is upgraded/downgraded. Alternatively, you can downgrade to use ecs-init version 1.84.0 or upgrade to ecs-init-version 1.86.1 (in release process).

=============
Fix for the issue: 
=============
The issue has been fixed in PR and is being released as a part of the ongoing Agent release 1.86.1

**Comment by atreyd** [comment] 2024-08-19 12:45
We updated the ecs-agent version to 1.86.1 and 1.86.2 on different ec2 instances and tried to test this change.
 
What I did: 
 - Manually restarted docker service on EC2 instance. 
What was the outcome:
- Docker service was started automatically. 
- ECS was not able to come up automatically by itself.

**Comment by danehlim** [comment] 2024-08-19 17:46
Hi @atreyd, ECS service needs to be updated in this case. Updating ECS Agent on its own will not address the issue since the fix is implemented at the systemd service level. Have you tried upgrading to the latest [ECS-Optimized AMI](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html)? Alternatively, push to package management repos (such as yum) of ecs-init version 1.86.1 is still pending but once that is completed you can also run `sudo yum update ecs-init` to get the necessary ECS service changes.

**Closed** 2024-08-19 17:51 UTC
