### ISSUE TITLE
ecs-agent v1.29.0 hangs up with docker version 18.09.2 during rolling deployment

### ISSUE THREAD

**Issue by arunjayanth** [aws/amazon-ecs-agent#2104] opened 2019-07-01 07:36 UTC
### Summary
ECS Agent is hanging after a successful rolling deployment of a ECS Service Task ,causing other tasks in Pending State

### Description
We have a ECS Cluster with 8 services running, each running with one task exactly. When we do a rolling deployment of one service ( using Dynamic Port Mapping) , the ECS Agent starts a new task ( as expected) , attaches it to the Target Group and starts deregistering the old task and stopping it. Even though the ECS Agent Event log says the old task is stopped , the task was left behind running in the EC2 box . Target Group had only the new task attached to it. Once this happens, any new task deployment goes into Pending State and does not get deployed. When we restart ecs-agent , this problem goes away and occurs again when a new deployment is done.

### WorkAround
The only Work Around we were able to make from this is reducing the docker-ce version to 18.06.1 where it works as expected

### Expected Behavior
ECS agent should stop the old task inside the EC2 box and complete any new task deployments

### Observed Behavior
ECS agent hangs up at each deployment

### Environment Details
These are just a snippet of environment details. More details are provided with AWS Support Case 6201991381
**Docker Version**
Client: Docker Engine - Community
 Version:           19.03.0-rc3
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.5
 Git commit:        27fcb77
 Built:             Thu Jun 20 02:02:37 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**ecs agent details**
ecs agent version = 1.29.0

**OS version details**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### Supporting Log Snippets
We cannot provide logs here . A support case was raised with AWS and ecs agent collector logs are provided over there  . Case Number: 6201991381

**Comment by sharanyad** [comment] 2019-07-08 21:40
@arunjayanth 
Have you configured `ECS_CONTAINER_STOP_TIMEOUT` to a large value in your ecs config file?

**Comment by arunjayanth** [comment] 2019-07-09 15:27
Hi @sharanyad  , No we have not specified that attribute in ecs config file , so whatever is the default, it should be pick for both 18.09 and the 18.06 (WorkAround we did)

**Comment by fenxiong** [comment] 2019-10-09 23:55
@arunjayanth From the logs you sent before, it looks like the docker daemon starts hanging when the agent tries to stop the container in your task (even though you can still run `docker ps` on the host, it doesn't necessarily mean Docker is able to respond to other things). I'm not able to reproduce the hanging with same versions of agent (1.29.0) and docker (18.09.2, on centos 7) and a task definition similar to yours other than the container image, so i guess the issue has something to do with your application or the AMI. Does this happen consistently for your task on Docker 18.09? If so can you enable debug log for Docker (https://success.docker.com/article/how-do-i-enable-debug-logging-of-the-docker-daemon), reproduce the issue and collect the logs (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html) and send them to fenxiong AT amazon.com? Also, for debug purpose it would be useful to do the following things on the instance when you observe that the agent is not able to stop a container:
* Try manually stopping the container on the instance with `docker stop` to see whether Docker can respond to that;
* Run `curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine?debug=2` to collect a trace of the docker daemon

**Comment by fenxiong** [comment] 2019-10-18 17:54
Closing this now since this needs more info in order for us to troubleshoot. Feel free to reopen if you have a chance to reproduce and send us the logs.

**Closed by fenxiong** 2019-10-18 17:54 UTC
Labels: more info needed
