### ISSUE TITLE
Specifying "host" to running ecs-launched containers

### ISSUE THREAD

**Issue by ledjon** [aws/amazon-ecs-agent#112] opened 2015-06-16 15:51 UTC
When manually starting a container ("docker run") you can do --host=myhostname which sets the hostname of running container.

For various licensing reasons a piece of software we have requires the hostname  to be "bi-01" yet when I deploy via ecs, I cannot provide a hostname in the configuration.

Am I missing something?

**Comment by euank** [comment] 2015-06-16 18:08
You're not missing anything; I'll take this as a feature request.
Thanks for the suggestion and information about your use-case.

**Comment by tj** [comment] 2015-06-16 18:15
We could also use access to $HOSTNAME for flags, for example nsqd needs to expose the address of the host it lives on. nsq is arguably not really designed for this sort of thing but we're heavy users and stuck using `docker run` until then

**Comment by apeiniger** [comment] 2015-06-19 06:24
We have the same usecase as tj. Would be great to be able to use the $HOSTNAME variable of the host and pass it to the docker containers. Especially helpful when logging from inside the container, as it's then easier to identify the right host instance when the logs are in some central location (CloudWatch Logs, Loggly, ...)

**Comment by mthenw** [comment] 2015-06-19 09:17
+1 for 
> Would be great to be able to use the $HOSTNAME variable of the host and pass it to the docker containers.

**Comment by nexus49** [comment] 2015-07-17 04:04
+1 for this feature

**Comment by cedrics** [comment] 2015-08-07 15:32
+1 we are running ECS on instances managed by OpsWorks and they give those instances really nice host names that I would really like to reuse :smile_cat:

**Comment by tdensmore** [comment] 2015-08-18 13:06
+1.

**Comment by alexey-ernest** [comment] 2015-08-24 15:33
+1

**Comment by alexey-ernest** [comment] 2015-08-25 14:55
Hi @tj I've faced the same problem with nsqd and -broadcast-address flag. The workaround I've found is to dynamically detect public ip address of the container's host and use it as a broadcast address. Look at my solution https://github.com/clickberry/nsqd-ecs. It works well for ECS services, so you can easily scale up number of nsqd instances and all will retrieve it's public ip and registers in nsqlookupd.

**Comment by mdedetrich** [comment] 2015-09-30 04:48
+1

This is actually required to for running things like Akka, which require an explicit hostname/port to be provided if you are running behind a NAT/docker container, i.e. see

http://doc.akka.io/docs/akka/snapshot/additional/faq.html
http://serverfault.com/q/695393

**Comment by mattcallanan** [comment] 2015-10-02 00:13
+1 
To be able to publish host's hostname together with container id to centralised logging.

**Comment by samuelkarp** [comment] 2015-10-06 22:59
Hostname is now available in ECS using the 1.5.0 version of the Agent.  You should now be able to specify hostname for a container in your task definitions in the ECS console.  With respect to retrieving the underlying host's hostname, I'm closing this issue in favor of #3.

**Closed by samuelkarp** 2015-10-06 22:59 UTC
Labels: enhancement

**Comment by hridyeshpant** [comment] 2015-10-08 01:47
how we defined dynamic hostname in task definition , as we don't know which container is going to run in which ECS instances. we have ECS cluster with 5 instances and container can run in any instances.

**Comment by apeiniger** [comment] 2015-10-08 06:32
Would be cool if you could give us a quick example of how this would look like in the JSON of the task definition when using this with 1.5.0.

**Comment by samuelkarp** [comment] 2015-10-08 07:08
@apeiniger, It looks like `"hostname": "thisismyhostname"` inside the container definition.  Details of all the task definition parameters are available in our [documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_network).

@hridyeshpant, dynamic hostnames are not currently available.  I'm really interested in hearing more about what dynamism you'd like for hostname; can you either open a new issue here or a thread on our [forum](https://forums.aws.amazon.com/forum.jspa?forumID=187)?

**Comment by hridyeshpant** [comment] 2015-10-08 12:05
@samuelkarp we are using splunkforwarder as ECS docker container  but the issue is, inside the  splunkforwarder container the host name is the container id  and then splunkforwarder  communicate to splunk deployment server but the issue is  the splunk deployment server is configured to look at the host name to determine which output app it should give to the client. because the host name is container id not actual host EC2 instance. splunk deployment server is not able to communicate. 
we can not hardcode host name in task definition as we are running  ECS cluster with multiple instances , and we dont know which instance will be used . So it will be good we can have actual hostname environment value inside the container.

**Comment by tmornini** [comment] 2016-02-18 00:44
@mdedetrich said:

> This is actually required to for running things like Akka

:+1:

This is exactly my situation getting Apache Spark to run on ECS.

**Comment by netknight** [comment] 2016-04-12 07:42
ExtraHosts is lacking functionality, because I frequently use it with TaskDefinition, but when I started using CloudFormation I should step on my neck to pass external hostnames to dockerized container. :(

**Comment by bcodesido** [comment] 2016-07-09 16:18
I have a distributed system running on ECS with the same docker configuration but every container has his own internal config. It will be grate to have diferent hostname in every container to download the configuration depending who is doing it.

**Comment by bronislav** [comment] 2016-08-19 14:00
I'm also interesting in the dynamic hostnames. Right now we can either use container_id as hostname (omit hostname in the container configuration) or specify static hostname.

And this brings mess in the monitoring. We filter CPU by hostname and it could be 150% (5 containers using 30% CPU each). I know that this could be fixed tweaking monitoring. But newrelic don't allow this.

**Comment by maiconbaumx** [comment] 2018-06-23 23:36
+1 For dynamic hostname! I'm setting up Apache Flink on ECS and, as part of TaskManagers configuration, I need to provide a hostname that can be resolvable in a cross-instance style. I mean, the JobManager running in one container on instance X can access the TaskManager running in one container on instance Y. The only way that I found is defining the hostname of the container equal to hostname of the container instance.. However, I can run several container instances and the taskmanager's containers can run in any of this instances.  Would be great to have a way of setting hostname in containerDefinition to something like $HOSTNAME environment variable in Container Instances. =)
