### ISSUE TITLE
Amazon Linux keeps OOM containers alive

### ISSUE THREAD

**Issue by dhulihan** [aws/amazon-ecs-agent#472] opened 2016-08-03 21:33 UTC
I recently had a memory leak in one of my containers, which consumed all available memory up to the container's `--memory` limit. I expected this container to be killed by OOM Killer immediately, but to my surprise, the container stayed alive, reporting 100% memory usage indefinitely. 

You can reproduce this behavior by running a container that quickly consumes memory:

```bash
docker run -d --memory=256m --memory-swap=256m valentinomiazzo/memory-eater ; docker stats $(docker ps -l -q)
```

You can see ~ 100% memory consumption in `docker stats`

![screen shot 2016-08-03 at 3 11 42 pm](https://cloud.githubusercontent.com/assets/519728/17382458/279e312a-598e-11e6-9202-cbbe7f663c01.png)

This container will remain for a long period of time (hours), when it should be OOM killed immediately.

When using ecs-agent 1.11.0 and docker 1.12.0 on Ubuntu 14.04, the container is OOM Killed almost immediately (the expected behavior):

![screen shot 2016-08-03 at 3 26 09 pm](https://cloud.githubusercontent.com/assets/519728/17382561/c3f7718a-598e-11e6-830b-ce0a73237a3c.png)

![screen shot 2016-08-03 at 3 27 58 pm](https://cloud.githubusercontent.com/assets/519728/17382595/e72a7a12-598e-11e6-893d-121c2e655cba.png)

This behavior does not seem related to a particular docker version (tested with 1.9.1 & 1.11.2) or ecs-agent version (tested 1.9.0 & 1.11.0). AMIs tested: ami-a28476c2, ami-241bd844.

**Comment by richardpen** [comment] 2016-08-05 22:44
@dhulihan Since the kernel version of latest Amazon Linux Ami is different from ubuntu 14.04, there may be some change in the kernel:
```
Ubuntu 14.04
#uname -r
4.2.0-27-generic

Amazon Linux Ami
#uname -r
4.4.14-24.50.amzn1.x86_64
```

When the container runs out of memory, the OOM killer will select the best process to kill, and the command/api call that tries to acquire memory will fail when memory is used up. But the container can continue to run. See [here](http://unix.stackexchange.com/questions/153585/how-oom-killer-decides-which-process-to-kill-first) and [cgroup oom killer](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt) for references.
I tested with the following task definition, the agent will receive OOM event, and the process ``stress`` fails due to memory being used up, but the container is still running the following command.
```
{
    "taskDefinition": {
        "status": "ACTIVE",
        "family": "oom",
        "volumes": [],
        "taskDefinitionArn": "arn:aws:ecs:us-west-2:807827109477:task-definition/oom:1",
        "containerDefinitions": [
            {
                "environment": [],
                "name": "OOM",
                "mountPoints": [],
                "image": "ubuntu",
                "cpu": 10,
                "portMappings": [],
                "command": [
                    "sh",
                    "-c",
                    "apt-get update; apt-get install stress; stress -m 1 --vm-bytes 800m --vm-keep --backoff 60s ; while [ true  ]; do echo `date +%T`; sleep 1s; done;"
                ],
                "memory": 100,
                "essential": true,
                "volumesFrom": []
            }
        ],
        "revision": 1
    }
}
```

So if in your process that the error caused by api/command call to acquire memory doesn't crash the root process, then the container can still be running.

**Comment by samuelkarp** [comment] 2016-08-24 23:43
@dhulihan I'm going to close this for now.  The OOM killer behavior is dependent on a number of factors, including `/proc/sys/vm/overcommit_memory`, kernel configuration (like whether swap accounting is enabled), and the choices it makes in selecting processes to kill.  In some cases, there may not be an OOM kill even though you've exhausted the memory up to the limit; you may instead just experience OOM errors to the process attempting to allocate memory (e.g., [`malloc`](http://man7.org/linux/man-pages/man3/free.3.html) could receive `NULL`).  In other cases (like with overcommit enabled), the kernel may have handed out an address to memory that is not actually free and may kill the process.  https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt goes into a lot more detail on how the OOM killer works and ways to tune it.

In what you describe, it looks like your application may be receiving an OOM error (`NULL`) when trying to allocate memory when running on the Amazon Linux AMI and handling it, while it might be receiving an allocation on Ubuntu that doesn't actually exist (overcommit) and getting killed as a result.

**Closed by samuelkarp** 2016-08-24 23:43 UTC
Labels: more info needed

**Comment by dhulihan** [comment] 2016-08-25 08:00
@samuelkarp @richardpen Thanks for providing more insight into the behavior of OOM killer. I'll work on getting it to behave as desired in Amazon Linux. :smile:

**Comment by samuelkarp** [comment] 2016-08-25 17:41
Glad we could help!  If you're interested in just sticking with Ubuntu, you can [follow these instructions](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html) to get the ECS agent running on Ubuntu.

**Comment by balintzs** [comment] 2017-05-01 15:02
@dhulihan I am currently facing the same problem on Amazon Linux. Have you managed to get it working since your last comment?

**Comment by dm03514** [comment] 2017-05-04 21:03
@balintzs Experiencing the same thing here, anything?

**Comment by dhulihan** [comment] 2017-05-05 03:28
@balintzs As a temporary measure, I wrapped our service process in [supervisord/memmon](http://superlance.readthedocs.io/en/latest/memmon.html), which restarted the process it when it crossed a user-defined memory threshold (90%). This worked pretty well until the leak was fixed.

**Comment by xeroeugene** [comment] 2020-01-17 04:11
@allisaurus @samuelkarp  
I am experiencing the same problem (OOM is not killing the process) witch a container with a memory leak, that has no task memory limit, but only container memory limit set. (both soft and hard) on Amazon Linux optimized for ECS. 

Could you please tell me, as I am straggling to find the documentation on this, whether the OOM killer would be responsible to kill the OOM process when there is NO container defined hard limit, but Task memory limit is set (e.g container has boundaries set by task memory limit) or if that would be a ECS agent task to monitor and to kill?
