### ISSUE TITLE
/proc/self/cgroup naming convention changed from default "docker" to "ecs"

### ISSUE THREAD

**Issue by sidewaysgravity** [aws/amazon-ecs-agent#1119] opened 2017-11-30 08:41 UTC
### Summary
The default prefix for a docker container is "docker" followed by the image name / sha. Several libraries determine the container id by parsing /proc/self/cgroup and expect "docker/container_id". This is one of the libraries that I use that after updating to the latest docker agent, my proxy no longer could get configured since it relies on determining the container id using the default values for docker. https://github.com/jwilder/docker-gen/blob/master/context.go#L172

I could not see any specific reason for why the new "ecs/task-arn" prefix was introduced in this commit f09f0f56f21696cc and would like to have it set back to the default.

### Expected Behavior
9:perf_event:/docker/container-sha
8:memory:/docker/container-sha
7:hugetlb:/docker/container-sha
6:freezer:/docker/container-sha
5:devices:/docker/container-sha
4:cpuset:/docker/container-sha
3:cpuacct:/docker/container-sha
2:cpu:/docker/container-sha
1:blkio:/docker/container-sha

### Observed Behavior
9:perf_event:/ecs/task-arn/container-sha
8:memory:/ecs/task-arn/container-sha
7:hugetlb:/ecs/task-arn/container-sha
6:freezer:/ecs/task-arn/container-sha
5:devices:/ecs/task-arn/container-sha
4:cpuset:/ecs/task-arn/container-sha
3:cpuacct:/ecs/task-arn/container-sha
2:cpu:/ecs/task-arn/container-sha
1:blkio:/ecs/task-arn/container-sha

### Environment Details
ecs agent 1.16.0

**Comment by samuelkarp** [comment] 2017-11-30 08:58
Hi @sidewaysgravity, thanks for opening this issue.

The cgroup prefix was changed to include the task ARN so that containers in the same task have a common cgroup prefix and cgroup limits can be set for a task together (cgroups are hierarchical in nature, and this enables limits to be set in a higher path and have it apply to all of the cgroups under that common root).  This is used in the new [task size](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_size) parameters in the task definition.  The prefix ahead of the task ARN was changed from `docker` to `ecs` to avoid colliding with containers that were started outside of ECS.

> Several libraries determine the container id by parsing /proc/self/cgroup and expect "docker/container_id".

I would generally recommend against this approach.  Having the container ID in the cgroup path (at all) and having `docker` as the cgroup path prefix is an implementation detail of Docker rather than something defined in a concrete interface.  This is similar to how (by default) Docker will set the hostname of a container to be the container ID, but again that's just an implementation detail and not part of the formal interface.

Container introspection in Docker is still a bit of an open question.  You can find a discussion about that in https://github.com/moby/moby/pull/26331.

We recently added a supported interface in ECS for discovering information about your task from within a container.  This will be a stable interface and is not an implementation detail.  You can find documentation of the container metadata feature [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-metadata.html).

**Comment by sidewaysgravity** [comment] 2017-11-30 19:11
@samuelkarp Thanks for the quick reply and links. Hopefully the docker introspection can get a resolution sooner than later. I have opened up an issue on docker-gen (https://github.com/jwilder/docker-gen/issues/263) to discuss a possible solution on their end.

**Comment by danielgrant** [comment] 2017-12-11 17:23
Just throwing my two cents in here, but we have just encountered an issue as a result of the change referenced by @sidewaysgravity above.

We are running Jenkins inside a Docker container on an ECS cluster and this change is preventing our build jobs from running any Docker builds. Specifically, this line in an essential plugin is now rendered defunct:

https://github.com/jenkinsci/docker-workflow-plugin/blob/master/src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java#L311

Because of this change, Jenkins now believes that it's no longer running inside a container, and that in turn alters the behaviour of how the job is launched which ultimately causes it to fail.

I take your point @samuelkarp that whilst the output from `/proc/self/cgroup` is an implementation detail rather than part of a concrete interface, a search of techniques to detect whether an application is running in a Docker container and to fetch a running containers ID from within that container shows that this technique is by far the most commonly used.

I think it would be useful to re-open this issue and continue the discussion around this change, I worry that it's been implemented without full consideration given to the consequences of it on existing containers that depend on the (_fairly standard_) output of `/proc/self/cgroup`, especially since there currently doesn't appear to be any other equally clean / ubiquitous ways of doing the same thing.

**Comment by sidewaysgravity** [comment] 2017-12-13 03:58
@danielgrant I closed the issue but I can open it back up to continue the discussion. I agree to your point that the `/proc/self/cgroup` does seem to be the most consistent way to determine if you are running inside a container.

**Comment by petderek** [comment] 2017-12-13 21:03
@sidewaysgravity @danielgrant Thanks for providing those examples! 

If you aren't using the task size (task-level cpu and memory limits), you can disable the `ecs` hierarchy by setting `ECS_ENABLE_TASK_CPU_MEM_LIMIT=false`. That should cause docker to revert to using the `docker` hierarchy.

**Comment by danielgrant** [comment] 2017-12-14 09:56
@petderek thanks for the tip, I've set `ECS_ENABLE_TASK_CPU_MEM_LIMIT` to `false` as per your suggestion and I can confirm that this does indeed revert the `/proc/self/cgroup` output to use the "normal" Docker output.

This workaround should suffice for now for the use case I highlighted above, but obviously this is going to continue to cause problems for people who might want the "normal" Docker `/proc/self/cgroup` output *and* the new task size parameters.

**Comment by petderek** [comment] 2017-12-14 17:37
> ...this is going to continue to cause problems for people who might want the "normal" Docker `/proc/self/cgroup` output _and_ the new task size parameters.

@danielgrant Precisely -- and that won't have a clear cut solution because the task size feature requires using the custom cgroup hierarchy. We will need to look at the solutions that @samuelkarp pointed out in that scenario.

**Comment by sidewaysgravity** [comment] 2017-12-15 20:09
Thanks @petderek, that worked for me as well.

**Comment by z00m1n** [comment] 2018-01-14 17:57
@petderek : Could you kindly elaborate on setting `ECS_ENABLE_TASK_CPU_MEM_LIMIT=false` ? Where exactly do I need to set that ?

**Comment by adnxn** [comment] 2019-10-15 19:31
closing this issue since we currently do not have plans to change the custom paths for cgroups when using task limits feature.

the workaround for this would be to explicitly disable the feature with `ECS_ENABLE_TASK_CPU_MEM_LIMIT=false` in `ecs.config` and restart the ecs agent.

**Closed by adnxn** 2019-10-15 19:31 UTC
Labels: kind/bug, os/linux, scope/ECS Agent, workaround available

**Comment by MartinLoeper** [comment] 2020-11-17 18:57
I probably ran into this issue now.   
Our scenario is as follows: We are using the DataDog Tracer Library for JavaScript [1] which relies on the container-info package [2][3] which is fairly popular nowadays.

The container-info package reads `/proc/${pid}/cgroup` and parses the lines using the following regexes: [4]

```js
const uuidSource = '[0-9a-f]{8}[-_][0-9a-f]{4}[-_][0-9a-f]{4}[-_][0-9a-f]{4}[-_][0-9a-f]{12}'
const containerSource = '[0-9a-f]{64}'
```

I noticed that our container running on AWS Fargate reports the following path: **/ecs/7f57e3e838b74301abd12f863c7c093a/7f57e3e838b74301abd12f863c7c093a-3653333083**.

Apparently, Fargate uses a path which matches the following regex: **[0-9a-f]{32}-[0-9]{10}**

Q: Is this something Fargate-specific or was the cgroup entry changed for all containers running on ECS??

[1] https://github.com/DataDog/dd-trace-js   
[2] https://www.npmjs.com/package/container-info
[3] https://github.com/Qard/container-info/
[4] https://github.com/Qard/container-info/blob/master/index.js#L5

@sidewaysgravity @samuelkarp
