### ISSUE TITLE
ECS sometimes takes 10 minutes to notice termination of Docker container

### ISSUE THREAD

**Issue by mlafeldt** [aws/amazon-ecs-agent#584] opened 2016-11-03 16:42 UTC
One thing that we've been observing for a couple of months now, is that tasks started via ECS sometimes take **exactly 10 minutes** to finish even though the underlying Docker container has finished in a matter of seconds.

Since we're using ECS to run periodic jobs, we could see this problem hundreds of times, although it appears to be totally random.

For example:

![44a2ab80-75ee-11e6-9347-d3f0fac1d55a](https://cloud.githubusercontent.com/assets/158074/19975077/e4237536-a1ea-11e6-8e75-6881631c2817.png)

Another more recent example:

<img width="495" alt="9b5301b6-a071-11e6-8709-42afa27a4a89" src="https://cloud.githubusercontent.com/assets/158074/19976208/1e740d6e-a1ef-11e6-96e2-4a265ef7fc2b.png">

---

Today I took the time to dig a little bit deeper into this problem.

Here are the logs of a recent task, `task-138d5907-ac34-4253-959f-e9fac2c158bb` where the issue occured.

https://gist.github.com/mlafeldt/4fde605a489ad82e2f626b8a01c729c1

As one can see, there's a gap between 08:18:07 and 08:28:01 where ecs-agent hasn't logged anything containing the string `task-138d5907-ac34-4253-959f-e9fac2c158bb`.

Digging still deeper, I searched for all `TaskEngine` events:

https://gist.github.com/mlafeldt/65fd20eadac78a46278ecb505401f464

Here's the mentioned gap of 10 minutes:

```
Nov 02 08:18:02 ip-10-8-4-78.eu-west-1.compute.internal ecs-agent:  2016-11-02T07:18:01Z [DEBUG] Waiting for event for task module="TaskEngine" task="task-138d5907-ac34-4253-959f-e9fac2c158bb:1 arn:aws:ecs:eu-west-1:062052581233:task/5be234e8-a5ea-41b1-8a43-552f3603f79e, Status: (RUNNING->RUNNING) Containers: [task-138d5907-ac34-4253-959f-e9fac2c158bb--task (RUNNING->RUNNING),]"
Nov 02 08:28:01 ip-10-8-4-78.eu-west-1.compute.internal ecs-agent:  2016-11-02T07:28:01Z [DEBUG] No longer waiting module="TaskEngine" task="task-138d5907-ac34-4253-959f-e9fac2c158bb:1 arn:aws:ecs:eu-west-1:062052581233:task/5be234e8-a5ea-41b1-8a43-552f3603f79e, Status: (RUNNING->RUNNING) Containers: [task-138d5907-ac34-4253-959f-e9fac2c158bb--task (RUNNING->RUNNING),]"
```

The message `No longer waiting` is printed here:

https://github.com/aws/amazon-ecs-agent/blob/aebcbca3b67e85b89063eedefa065d31ec5c646e/agent/engine/task_manager.go#L326

This led me to the code that times out after **10 minutes**:

https://github.com/aws/amazon-ecs-agent/blob/aebcbca3b67e85b89063eedefa065d31ec5c646e/agent/engine/task_manager.go#L132-L137

My best guess is that there's something going wrong with the way ecs-agent polls Docker for state changes.

We're running ecs-agent 1.13.0 and Docker 1.10.3.

**Comment by richardpen** [comment] 2016-11-03 18:49
@mlafeldt Thanks for your deep debugging this issue, the agent recognize the container state change in two ways:
* Subscribe to the docker event stream, and ecs agent will update the state of container/task after received container change event from docker event stream. 
* Ecs agent also reconciliation with docker every 10 mins by actively checking the state of the container.

The cause of the issue is that ecs agent didn't receive container change event from the docker event stream, so only after 10 minutes will agent recognize the container's state by actively checking the state of all containers belongs to one task. 

And I searched the logs you provided, seems ecs agent didn't receive any event from docker event stream, that's the wired place and where we should dig into. In order to help us find the root cause here, could you send us the logs when the agent start if they are still existed in your disk. As the agent will subscribe to the docker event stream as soon as it start, we are interested in whether agent successfully subscribed to docker event stream. Or can you restart the agent by running `sudo stop ecs` and `sudo start ecs` see if this error still existed and provide us the logs.

Please public here or send it directly to me at: penyin (at) amazon.com
Thanks,
Peng

**Comment by mlafeldt** [comment] 2016-11-03 19:56
Thanks. Sent you an email with the logs of ecs-agent starting up.

**Comment by richardpen** [comment] 2016-11-03 21:21
@mlafeldt Thanks for your information, from the logs I see that for some reason ecs agent didn't receive any event from docker event stream, and there is no suspicious log in agent logs. We will try to reproduce in our side, will let you know when we have an update.

**Comment by richardpen** [comment] 2016-11-04 17:01
@mlafeldt I think that may be the problem with docker 1.10.3, as I saw in docker [1.11.0](https://github.com/docker/docker/releases/tag/v1.11.0) there is a [fix](https://github.com/docker/docker/pull/21692/files) related to docker events.

Also I could reproduce the issue with docker 1.10.3 within half an hour with the following scripts:
```
#!/bin/bash

docker stop ecs-agent
docker rm ecs-agent

while [ true ];
do

	docker run --name ecs-agent --detach=true --restart=on-failure:10 -d --volume=/var/run/docker.sock:/var/run/docker.sock --volume=/var/log/ecs:/log --volume=/var/lib/ecs/data:/data --net=host --env-file=/etc/ecs/ecs.config --env=ECS_LOGFILE=/log/ecs-agent.log --env=ECS_DATADIR=/data/ --env=ECS_CLUSTER=default --env=ECS_LOGLEVEL=debug --env=ECS_ENABLE_TASK_IAM_ROLE=true --env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true amazon/amazon-ecs-agent:latest

	sleep 2s
	cid=$(docker run -d ubuntu bash sleep 10s)
	sleep 2s

	ecslog=$(docker logs ecs-agent | grep "Handling a docker event")
	if [ "${ecslog}" = "" ]; then
		echo "No docker events received"
		exit
	else
		echo "Recevied docker events"
		docker stop ecs-agent
		docker rm ecs-agent
	fi
	docker stop ${cid}
	docker rm ${cid}
	sleep 10s
done
```
But got no luck to reproduce with docker 1.11.2 using the ami listed [here](https://coreos.com/os/docs/latest/booting-on-ec2.html), could you update the docker to 1.11.2, I think that will solve the problem.

Thanks,
Peng

**Comment by mlafeldt** [comment] 2016-11-07 09:37
Thanks for the update. Unfortunately, we cannot update Docker yet because updating CoreOS is blocked by #576.

**Comment by richardpen** [comment] 2016-11-09 00:27
@mlafeldt Since update to docker 1.11 solve this issue, I'm closing this issue now, please track #576 for the new agent release, thanks.

**Closed by richardpen** 2016-11-09 00:27 UTC
