### ISSUE TITLE
500 error while logoff

### ISSUE THREAD

**Issue by mpahima** [aws/amazon-ecs-agent#2083] opened 2019-06-13 13:39 UTC
### Summary

when im trying to logoff from ecs console i get 500 error

### Environment Details

https://console.aws.amazon.com/ecs/home?region=us-east-1

### Supporting Log Snippets

https://drive.google.com/file/d/1nWxgT989i5q1LOrDPuu4KJKyjojWV6v8/view?usp=sharing

**Comment by yunhee-l** [comment] 2019-06-13 16:29
Thank you for reporting the issue.
I have not been able to reproduce this, but have notified our console team to investigate.

**Comment by fenxiong** [comment] 2019-10-02 17:08
Closing since this should be fixed already. If you still get the error let us know.

**Closed by fenxiong** 2019-10-02 17:08 UTC
Labels: scope/Dependency

**Comment by rafaljanicki** [comment] 2020-09-24 08:50
Hey, I get that constantly since I remember. Regardless of an AWS account used, a browser used (currently Opera, previously Chrome) or an operating system (currently OS X, previously Windows). I see a 500 error like this:

![Zrzut ekranu 2020-09-24 o 10 50 43](https://user-images.githubusercontent.com/7746477/94123220-cccdc700-fe53-11ea-9a8c-15e0446b68a1.png)

**Comment by ivoros** [comment] 2021-02-22 15:34
Yes, it's still an issue after all these years. Ususally comes when inside an ECS cluster and you hit logout from there. On all browser, all OSes.
