### ISSUE TITLE
Config to use memory by percentage per container

### ISSUE THREAD

**Issue by chenliu0831** [aws/amazon-ecs-agent#399] opened 2016-05-10 15:13 UTC
Is it possible to config instance resource by percentage? We were using some hardcoded value but it seems it could change (e.g. in latest AMI the available memory for `c4.2xlarge` changed from 15043 -> 15042 M)..

**Comment by bfil** [comment] 2016-05-13 14:02
+1

@chenliu0831 how did you come up with those numbers? I'm trying to figure out how much memory I can configure depending on the instance size to be able to let my single container use as close as possible to the total available memory, but it seems rather random?

**Comment by chenliu0831** [comment] 2016-05-13 15:01
@bfil I got it from the AWS ECS console. If you already created a cluster and with instances registered to it, it'll shows up in the `ECS instances` tab. From there there are some other tabs like `available memory`, and cpu etc. I was just using hardcoded value and they seems to be unchanged for months. Well this time they changed by 1M :).

**Comment by bfil** [comment] 2016-05-13 15:15
@chenliu0831 another thing to consider is that, for example, when using `docker run --memory 256m`, Docker actually sets the value of `memory.memsw.limit_in_bytes` to 512MB (twice the value), according to the following article:

https://goldmann.pl/blog/2014/09/11/resource-management-in-docker/#_example_managing_the_memory_shares_of_a_container

So actually using 100% of the available memory should not be needed at all, but half of it should do. It would be great to hear from some experts around the docker memory shares management that this would be a viable approach though.

**Comment by chenliu0831** [comment] 2016-05-13 15:20
@bfil Hmm interesting. See one of my previous question [here](https://github.com/aws/amazon-ecs-agent/issues/382). Is it possible the 2X thing involve the swap memory (which makes the number virtual memory size)?

**Comment by samuelkarp** [comment] 2016-05-18 22:46
It is not possible to do this with ECS today.  ECS task definitions take a fixed number of MiB to allocate for memory.

@chenliu0831 I'm not sure what caused the memory reporting to change on the instance you launched.  The agent [reads available memory using the Go runtime](https://github.com/aws/amazon-ecs-agent/blob/v1.9.0/agent/api/api_client.go#L124-L126) and nothing has changed in that code with the new AMI.  It's possible that there is some other change affecting memory reporting to the Go runtime.

Since you're asking about allocating all the available memory, it sounds like this is a duplicate of https://github.com/aws/amazon-ecs-agent/issues/155.  Are you asking for something different from what is requested in that issue?

**Comment by bfil** [comment] 2016-05-19 07:56
@chenliu0831 it depends how much you would allocate, let's say that in a micro instance with 995 MB you put the setting as 512 MB. Docker will create a cgroup with 1024 MB in it, that means that the docker process would grow up to 1024 MB when necessary, so it might use around 30MB of swap, which shouldn't be a huge concern.

@samuelkarp that issue is definitely related, even though the title is phrased differently

**Comment by chenliu0831** [comment] 2016-05-19 21:03
@samuelkarp Yeah I think it's mostly the same as that issue. I saw

> There is some discussion in #124 about memory limits and we're internally tracking the feature request of percentage / proportional memory limits.

in the second thread of that issue. I guess we can close this in favor of that issue. I can double check if the available memory change in the new AMI is consistent. 

@bfil Got it. Seems an interesting way to set the memory size. So the ECS memory field in the task definition is not strict at all?

**Comment by samuelkarp** [comment] 2016-05-19 21:07
@chenliu0831 @bfil Memory constraints for Docker are [documented here](https://docs.docker.com/engine/reference/run/#user-memory-constraints).  ECS sets the memory limit (`-m` flag) without specifying a swap limit, so by default the total virtual memory size is double that of the memory setting.  On an instance with swap, the container will be able to use swap up to the limit of total virtual memory.  On an instance without swap, the memory setting is still a hard constraint.

**Comment by bfil** [comment] 2016-05-20 09:00
@samuelkarp yeah forgot that most of the machines on aws haven't got swap, thanks for the clarification.

**Comment by chenliu0831** [comment] 2016-05-20 15:27
@samuelkarp Confirmed the `c4.2xlarge` instance available memory is smaller by 1MB. Not directly related to this issue. Feel free to close this. Thanks for the explanation.

**Closed** 2016-05-20 17:35 UTC
Labels: feature request
