### ISSUE TITLE
ecs-agent wasn't able to establish connectivity

### ISSUE THREAD

**Issue by sesh-kebab** [aws/amazon-ecs-agent#1074] opened 2017-11-13 22:36 UTC
### Summary
On a new ec2-instance that joined a ecs cluster, tasks started on that container instance were stuck in a pending state for more than 2 hours.

### Expected Behavior
Expect the ecs-agent to re-establish connectivity or the container instance to be terminated if the ecs-agent is in a bad state.

### Observed Behavior
The container instance was running with the pending tasks for approximately 2-3 hours. I had to terminate the instance and bring up a new instance to take its place.

### Description

Upon checking the ecs-agent logs on the ec2 instance, following it the output:
```
2017-11-13T15:56:43Z [INFO] Loading configuration
2017-11-13T15:56:43Z [INFO] Unable to get Docker client for version 1.25: version detection check: failed to ping with Docker version: 1.25: API error (400): {"message":"client is newer than server (client API version: 1.25, server API version: 1.24)"}

2017-11-13T15:56:43Z [INFO] Unable to get Docker client for version 1.26: version detection check: failed to ping with Docker version: 1.26: API error (400): {"message":"client is newer than server (client API version: 1.26, server API version: 1.24)"}

2017-11-13T15:56:43Z [INFO] Unable to get Docker client for version 1.27: version detection check: failed to ping with Docker version: 1.27: API error (400): {"message":"client is newer than server (client API version: 1.27, server API version: 1.24)"}

2017-11-13T15:56:43Z [INFO] Unable to get Docker client for version 1.28: version detection check: failed to ping with Docker version: 1.28: API error (400): {"message":"client is newer than server (client API version: 1.28, server API version: 1.24)"}

2017-11-13T15:56:43Z [INFO] Unable to get Docker client for version 1.29: version detection check: failed to ping with Docker version: 1.29: API error (400): {"message":"client is newer than server (client API version: 1.29, server API version: 1.24)"}

2017-11-13T15:56:43Z [INFO] Loading state! module="statemanager"
2017-11-13T15:56:43Z [INFO] Event stream ContainerChange start listening...
2017-11-13T15:56:43Z [INFO] Registering Instance with ECS
2017-11-13T15:56:43Z [INFO] Registered container instance with cluster!
2017-11-13T15:56:43Z [INFO] Registration completed successfully. I am running as 'arn:aws:ecs:us-west-2:xxx:container-instance/e4309855-2128-47bf-a3a4-5560d61f21e1' in cluster 'yyy'
2017-11-13T15:56:43Z [INFO] Saving state! module="statemanager"
2017-11-13T15:56:43Z [INFO] Beginning Polling for updates
2017-11-13T15:56:43Z [INFO] Initializing stats engine
2017-11-13T15:56:43Z [INFO] Event stream DeregisterContainerInstance start listening...
2017-11-13T15:56:43Z [INFO] NO_PROXY set:169.254.169.254,169.254.170.2,/var/run/docker.sock
2017-11-13T15:56:43Z [INFO] Connected to ACS endpoint
2017-11-13T15:56:43Z [WARN] Error creating a websocket client: websocket: bad handshake
2017-11-13T15:56:43Z [ERROR] Error connecting to TCS: websocket client: unable to dial ecs-t-1.us-west-2.amazonaws.com response: {"AccessDeniedException":"Forbidden"}: websocket: bad handshake
2017-11-13T15:56:43Z [INFO] Error from tcs; backing off: websocket client: unable to dial ecs-t-1.us-west-2.amazonaws.com response: {"AccessDeniedException":"Forbidden"}: websocket: bad handshake
2017-11-13T15:56:45Z [WARN] Error creating a websocket client: websocket: bad handshake
2017-11-13T15:56:45Z [ERROR] Error connecting to TCS: websocket client: unable to dial ecs-t-1.us-west-2.amazonaws.com response: {"AccessDeniedException":"Forbidden"}: websocket: bad handshake
2017-11-13T15:56:45Z [INFO] Error from tcs; backing off: websocket client: unable to dial ecs-t-1.us-west-2.amazonaws.com response: {"AccessDeniedException":"Forbidden"}: websocket: bad handshake
2017-11-13T15:56:47Z [WARN] Error creating a websocket client: websocket: bad handshake
2017-11-13T15:56:47Z [ERROR] Error connecting to TCS: websocket client: unable to dial ecs-t-1.us-west-2.amazonaws.com response: {"AccessDeniedException":"Forbidden"}: websocket: bad handshake
2017-11-13T15:56:47Z [INFO] Error from tcs; backing off: websocket client: unable to dial ecs-t-1.us-west-2.amazonaws.com response: {"AccessDeniedException":"Forbidden"}: websocket: bad handshake
2017-11-13T15:56:51Z [WARN] Error creating a websocket client: websocket: bad handshake
2017-11-13T15:56:51Z [ERROR] Error connecting to TCS: websocket client: unable to dial ecs-t-1.us-west-2.amazonaws.com response: {"AccessDeniedException":"Forbidden"}: websocket: bad handshake
2017-11-13T15:56:51Z [INFO] Error from tcs; backing off: websocket client: unable to dial ecs-t-1.us-west-2.amazonaws.com response: {"AccessDeniedException":"Forbidden"}: websocket: bad handshake
2017-11-13T15:56:53Z [INFO] Saving state! module="statemanager"

```

The websocket errors continued for the entire duration the ecs-agent was up. 

## Questions: 
-  can we expect the ecs-agent to usually self-heal and recover from connectivity issues? If so why wouldn't have worked in this case?
-  can we expect the container instance to be shutdown if the ecs-agent is in a bad state such as this? Or is this essentially a deadlock situation?

**Comment by adnxn** [comment] 2017-11-22 00:28
> Can we expect the ecs-agent to usually self-heal and recover from connectivity issues?

The agent should operate normally with TCS connectivity issues as described above. The logs show that agent on your instance has established connection to the ACS, `2017-11-13T15:56:43Z [INFO] Connected to ACS endpoint`, and that is where the agent receives run task messages from the ECS service. The TCS error message is `"AccessDeniedException":"Forbidden"`, and I suspect that ` "ecs:StartTelemetrySession"` is missing from the IAM policy that is attached to your ECS instance. Note that we have managed policies for ECS instances and are documented [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance_IAM_role.html).

> If so why wouldn't have worked in this case?

I do not think the tasks are stuck in a pending state because of TCS connectivity issues.

> Can we expect the container instance to be shutdown if the ecs-agent is in a bad state such as this?

Currently the container instance will not be shutdown if the ecs-agent is in a bad state such as this.

> Or is this essentially a deadlock situation?

This situation is best resoloved by getting on the instance and restarting the agent with `sudo stop ecs` followed by a `sudo start ecs`

Since this is not expected behaviour for the agent, lets get some more information about your instance. Are you using the [Amazon ECS-Optimized AMI](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html)? Which version of the agent are you currently running? You can check by using the [instrospection endpoint](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-introspection.html) on the instance with `curl http://localhost:51678/v1/metadata`.

The next time your instance is in this state, you can also capture logs using our [log collection tool](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html) and email them to me directly at adnkha at amazon dot com. If you end up sending the logs to my email, please update this issue so I don't miss them. Thanks!

**Comment by adnxn** [comment] 2017-12-07 19:19
@sesh-kebab Looks like you've added the required permissions here https://github.com/quintilesims/layer0/pull/434. Closing this issue. I suspect you can close https://github.com/quintilesims/layer0/issues/429 as well! =]

**Closed by adnxn** 2017-12-07 19:19 UTC
Labels: more info needed

**Comment by sesh-kebab** [comment] 2017-12-07 19:31
Thanks @adnxn
