### ISSUE TITLE
Support Dockerfile HEALTHCHECK of agent

### ISSUE THREAD

**Issue by jhmartin** [aws/amazon-ecs-agent#800] opened 2017-05-11 15:33 UTC
Docker 1.12 and newer supports a HEALTHCHECK directive that allows the docker daemon to detect the health of an application inside a container. Please consider adding one to the agent Dockerfile.

Docs: https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by samuelkarp** [comment] 2017-05-11 17:41
Hi @jhmartin, thanks for reaching out.  This issue is a duplicate of https://github.com/aws/amazon-ecs-agent/issues/534, and discussion is happening there.  If you have any comments to add to the discussion, please add it on https://github.com/aws/amazon-ecs-agent/issues/534.  Thanks!

**Comment by jhmartin** [comment] 2017-05-11 17:56
@samuelkarp It is different. #534 suggests allowing the ecs-agent to use the HEALTHCHECK output to detect the state of containers managed by ECS. This issue is for the ECS agent *itself* to specify a HEALTHCHECK.

**Comment by samuelkarp** [comment] 2017-05-11 17:58
Ah, I think I missed that in your description.  My apologies for the premature close.

The agent's Dockerfile is [here](https://github.com/aws/amazon-ecs-agent/blob/dev/scripts/dockerfiles/Dockerfile.release) if you're interested in making a contribution.

**Comment by adnxn** [comment] 2018-03-09 02:23
@jhmartin, We've added task def support for the [health check command](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_healthcheck) and associated configuration parameters for the container. This parameter maps to HealthCheck in the Create a container section of the Docker Remote API and the HEALTHCHECK parameter of docker run.

**Comment by cyastella** [comment] 2019-11-15 19:23
closing issue since a new set of amis have been released and can be tracked [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-ami-versions.html)

**Closed** 2019-11-15 19:24 UTC
Labels: contributions welcome, kind/enhancement, pending release, scope/ECS Agent
