### ISSUE TITLE
ws client errors

### ISSUE THREAD

**Issue by ChrisRut** [aws/amazon-ecs-agent#438] opened 2016-06-28 21:15 UTC
This is a bit of a continuation of #281 ...
We appear to still be running into "[ERROR]" events in our ecs-agent.log files.
In the past 24hrs we have run into the following 28 events:

```
2016-06-28T18:47:12Z [ERROR] Error getting message from ws backend module="ws client" err="read tcp 54.239.19.128:443: connection reset by peer"
2016-06-28T09:19:26Z [ERROR] Error connecting to ACS: ServerException: Internal Server Error
2016-06-28T06:31:46Z [ERROR] Error getting message from ws backend module="ws client" err="read tcp 54.239.18.202:443: connection reset by peer"
2016-06-28T05:43:28Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:43:04Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:42:38Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:42:14Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:42:11Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:42:09Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:42:06Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:42:06Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:41:33Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:41:29Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:41:17Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:40:58Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:40:57Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:40:35Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:40:11Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:39:47Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:39:36Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:39:19Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:38:38Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:38:35Z [ERROR] Error getting message from ws backend module="ws client" err="websocket: close 1008 InvalidContent : Unexpected text frame received"
2016-06-28T05:38:12Z [ERROR] Error connecting to ACS: ServerException: Internal Server Error
2016-06-28T03:55:21Z [ERROR] Error getting message from ws backend module="ws client" err="read tcp 54.239.19.128:443: connection reset by peer"
2016-06-28T03:29:12Z [ERROR] Error getting message from ws backend module="ws client" err="read tcp 54.239.19.128:443: connection reset by peer"
2016-06-28T03:04:40Z [ERROR] Error getting message from ws backend module="ws client" err="read tcp 54.239.19.128:443: connection reset by peer"
2016-06-27T22:03:38Z [ERROR] Error getting message from ws backend module="ws client" err="read tcp 54.239.18.202:443: connection reset by peer"
```

If these errors are benign can we change the log_level to not be ERROR and instead use WARN or something else?

We are currently running the ECS optimized AMI 2016.03.b (ami-a1fa1acc).

**Comment by richardpen** [comment] 2016-06-29 18:24
The 1008 error code and "Internal Server Error" indicates an issue in the ECS backend while processing the payload message. If you'd like to help us investigate why the errors happened, could you provide me the following information:
* AWS account
* AWS region
* Cluster name
* Container Instance that got these error

If you're not comfortable posting this publicly, you can email me at penyin (at) amazon dot com.

**Comment by ChrisRut** [comment] 2016-06-29 22:13
@richardpen sent you an email with everything you've requested, please let me know if you need anything else. Thanks.

**Comment by kiranmeduri** [comment] 2016-07-08 15:24
Thank you for your patience, we have identified the issues on our service side. There are two bugs which result in these transient but impacting issues

1. Agent connects to ecs-a-2.us-east-1.amazonaws.com to get tasks needed to be started or stopped. This endpoint has a subtle bug which rejects the connection from agent with **Error connecting to ACS: ServerException: Internal Server Error**. This is a transient and recoverable bug which should not be a issue other than some additional latency in task launches and annoying logs

2. Agent also connects to ecs-t-2.us-east-1.amazonaws.com (Telemetry) to publish metrics of running tasks. We identified a bug on our end which causes the backend to treat published metrics as invalid and rejects them with an error **websocket: close 1008 InvalidContent : Unexpected text frame received**. This can be an issue if the rejection happens for more than a minute where the metric data point is lost. We are actively looking into resolving this issue.

Thanks for reporting. 

-kiran

**Comment by mlafeldt** [comment] 2016-09-13 08:09
@kiranmeduri We're also seeing a lot of these error today:

```
Sep 13 08:02:33 ip-10-8-3-74.eu-west-1.compute.internal ecs-agent[1772]: 2016-09-13T08:02:33Z [INFO] Creating poll dialer, host: ecs-t-2.eu-west-1.amazonaws.com
Sep 13 08:02:33 ip-10-8-3-74.eu-west-1.compute.internal ecs-agent[1772]: 2016-09-13T08:02:33Z [ERROR] Error getting message from ws backend: websocket: close 1008 InvalidContent : Unexpected text frame received
Sep 13 08:02:33 ip-10-8-3-74.eu-west-1.compute.internal ecs-agent[1772]: 2016-09-13T08:02:33Z [INFO] Error from tcs; backing offerrwebsocket: close 1008 InvalidContent : Unexpected text frame received
```

```
core@ip-10-8-3-74 ~ $ journalctl -u ecs-agent | grep -c 'Error from tcs'
92
```

So it seems you haven't fixed this issue on the server side yet?

Actually, we only came across this error because our monitoring has reported this very EC2 instance to be disconnected from ECS - a problem which comes up every few weeks or so. In any case, what's strange is that our monitoring alerted us 3 times, at 3:33, at 6:33, and at 9:33 CET. I guess there must be something going wrong on the server side?

**Comment by calvinfo** [comment] 2016-09-16 04:41
We're also seeing these on our side. 

```
2016-09-16T04:38:08Z [ERROR] Error getting message from ws backend: websocket: close 1008 InvalidContent : Unexpected text frame received
```

It's creating a bit of a problem because our agents disconnect and old containers don't get killed.

**Comment by aaithal** [comment] 2016-09-16 15:55
@mlafeldt @calvinfo can you please provide the following information to help us debug the issue (and to confirm if its similar to @ChrisRut's issue)?

* Container Instance Arn
* Cluster Arn/Name
* ECS Agent version 
* AMI ID
* [ECS Agent Logs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/troubleshooting.html#logs)

Please email them to aithal at amazon dot com or feel free to share it via an AWS Support case.

Thanks,
Anirudh

**Comment by mlafeldt** [comment] 2016-09-16 17:03
I'm going to provide you with more details the next time this happens. As I said, it only happens occasionally and we either terminate the EC2 instance or restart ecs-agent to fix the issue. (Due to auto scaling and rolling cluster updates the affected machines are long gone by now.)

**Comment by aaithal** [comment] 2016-09-16 17:20
@mlafeldt Thanks! We're also trying to reproduce this on our end and will let you know when we have an update.

**Comment by calvinfo** [comment] 2016-09-16 17:59
Okay, we'll try and keep on logged next time it happens!

**Comment by samuelkarp** [comment] 2017-03-31 22:16
Hey all,  my apologies for leaving this open for so long.  We believe that we've addressed the root causes we've found behind the errors reported here.  I'm going to close this issue; if you see any further occurrences of ws client errors please open a new issue and we can dig into those.  Thanks!

**Closed by samuelkarp** 2017-03-31 22:16 UTC
