### ISSUE TITLE
taskmetadata-validator fails to get stats

### ISSUE THREAD

**Issue by jicowan** [aws/amazon-ecs-agent#1426] opened 2018-07-01 13:15 UTC
### Summary

The sample Go application fails to get Docker stats from the task metadata endpoint.  

### Description

The following events are logged to CloudWatch: 
`Container health metadata unexpected, got: { <nil> %!s(int=0) }`
Increasing the time the application waits before calling the endpoint to 10s had no effect. 

### Expected Behavior
Return Docker stats

### Observed Behavior
Although stats failed, the taskmetadata-validator was able to get the following task metadata for the task.
```
Received data: %s {"DockerId":"9f41d561115cc6951d55bafb75cc18b39d0ec4911359bdc9752c09469f38ebae","Name":"taskmetadata","DockerName":"ecs-taskmetadata-4-taskmetadata-aa9bf7e681d3f1b61f00","Image":"[redacted].dkr.ecr.us-west-2.amazonaws.com/taskvalidator:latest","ImageID":"sha256:add5e42ec1e683508c68f34962c662ff6fe5d3237c60a3b6afe44d4726d1e1a6","Labels":{"com.amazonaws.ecs.cluster":"arn:aws:ecs:us-west-2:[redacted]:cluster/Datadog","com.amazonaws.ecs.container-name":"taskmetadata","com.amazonaws.ecs.task-arn":"arn:aws:ecs:us-west-2:[redacted]:task/f50d40f6-84f0-40fa-b802-da148c1dcc51","com.amazonaws.ecs.task-definition-family":"taskmetadata","com.amazonaws.ecs.task-definition-version":"4"},"DesiredStatus":"RUNNING","KnownStatus":"RUNNING","Limits":{"CPU":0,"Memory":0},"CreatedAt":"2018-07-01T13:05:24.585343385Z","StartedAt":"2018-07-01T13:05:25.132441212Z","Type":"NORMAL","Networks":[{"NetworkMode":"awsvpc","IPv4Addresses":["172.0.0.17"]}]} 
```

**Comment by richardpen** [comment] 2018-07-02 17:41
@jicowan Thanks for reporting this to us, there are two bugs here:
> Container health metadata unexpected, got: { <nil> %!s(int=0) }

This error was caused by the fact that the container doesn't define the Docker Health Check, but the code was assuming the container should have a healthy status. This is because the code was used in our functional test to test the container health check functionality. We will modify the code to not surface the error if container health check wasn't defined.

> Return Docker stats

The code currently doesn't print out the stats as in this [line](https://github.com/aws/amazon-ecs-agent/blob/2bf4348a0ff89e23be4e82a6c5ff28edf777092c/misc/taskmetadata-validator/taskmetadata-validator.go#L237). We will need to get the response and print it out the stats response, or you can do it yourself for testing by changing the line to:
```
stats, err = taskStats(client)
if err != nil{
    fmt.Fprintf(os.Stderr, "Unable to get task stats: %v", err)
    os.Exit(1)
}
fmt.Println("Received container stats: %s", stats)
```

We will work on the code change to fix this, please keep tracking of this issue for any updates.

Thanks,
Peng

**Comment by jicowan** [comment] 2018-07-02 20:53
@richardpen taskStats returns Docker.stats which is some kind of map/json document.  When I try adding the stats variable, I get an variable undefined error.  If I try to declare the variable as a map, e.g. var stats map[string]string I get an error saying, cannot assign map[string]*docker.Stats to stats (type map[string]string) in multiple assignment.

**Comment by richardpen** [comment] 2018-07-02 20:58
@jicowan An easier way to do is add the print in this [line](https://github.com/aws/amazon-ecs-agent/blob/2bf4348a0ff89e23be4e82a6c5ff28edf777092c/misc/taskmetadata-validator/taskmetadata-validator.go#L134):
```
fmt.Println("Received container stats: %s", string(body))
```

**Comment by jicowan** [comment] 2018-07-02 21:48
@richardpen I am not that proficient at go. How will it know what "body" is?

This is what I currently have: 
```
        _, err = taskStats(client)
        if err != nil {
                fmt.Fprintf(os.Stderr, "Unable to get task stats: %v", err)
                os.Exit(1)
        }
        fmt.Println("Received container stats %s", string(body))
```

**Comment by richardpen** [comment] 2018-07-02 21:53
@jicowan Sorry for the confusion, I'm referring to line 134 in the last comments. So instead of making the change above, you can add this at line 134: `fmt.Println("Received container stats %s", string(body))`. The `body` is the response returned by the agent.

**Comment by sharanyad** [comment] 2018-07-03 23:18
Closing this issue as https://github.com/aws/amazon-ecs-agent/pull/1431 fixes it.

**Closed by sharanyad** 2018-07-03 23:18 UTC
Labels: kind/bug
