### ISSUE TITLE
Agent Refuse to start containers with None logging driver

### ISSUE THREAD

**Issue by Alonreznik** [aws/amazon-ecs-agent#1056] opened 2017-11-08 13:17 UTC
Hi!
Followed up also here:
https://forums.aws.amazon.com/thread.jspa?threadID=267098&tstart=0
We're trying to make a deployment by running old task definition, with logging driver of None. The agents refuses to place them due to ".. is missing an attribute required by your task". When we change the log driver to syslog, it works fine.
Please fix.

**Comment by nmeyerhans** [comment] 2017-11-08 18:15
Hi @Alonreznik. Thanks for this report. I'm looking into it.

**Comment by lanoxx** [comment] 2017-11-08 19:37
I am affected by this since today. Every time i try to change the network mode to bridge and save, then it is automatically reset to "None".

**Comment by nmeyerhans** [comment] 2017-11-08 19:42
Hi @lanoxx. In order to keep track of things, please create a new issue. This one is for tracking an apparent regression regarding logging drivers. If there's a problem with network modes, I'd very much like to keep track of that separately.

**Comment by nmeyerhans** [comment] 2017-11-08 23:56
@Alonreznik, I'm a little confused about the actual symptoms, and I want to make sure I'm actually looking at the right things. You mention in the opening of this issue that you've got issues with the 'none' logging driver. However, forums thread that you linked to is related to network modes.

The network mode issue has been resolved within the ECS service, and I've noted as much on the forum. Are you still having logging-driver issues? If so, can you please share some more details of how you're configuring and running agent, as well as how your configuring the logging drivers in your task definition?

**Comment by furlanrapha** [comment] 2017-11-10 16:09
@lanoxx I have faced this error on AWS, after a Hard Reload (`CTRL + F5` / `Cmd + R`) i was able to select `Bridge` mode and save it.

But I saw that some required attr. was added on the TD making it unable to be started on the cluster service:
`com.amazonaws.ecs.capability.logging-driver.none`
`com.amazonaws.ecs.capability.docker-remote-api.1.18`

![image](https://user-images.githubusercontent.com/650119/32667014-8770f326-c620-11e7-8918-03d85e51bdf1.png)
^ this at the bottom of the TD detail page

Before this issue, I didn't had those attr. on my TD revisions.

**Comment by ofirnk** [comment] 2017-11-13 12:40
@nmeyerhans assuming I faced the same issue, this is what happened to me:

1. We had `task definitions` that were set 1-2+ weeks ago. These had the following requirements:
![image](https://user-images.githubusercontent.com/8449713/32725818-3df0fb68-c87f-11e7-9aff-abae1402d8be.png)
1. When clicking `create new revision` to update those task definitions, I reached `edit container` and saw this:
![image](https://user-images.githubusercontent.com/8449713/32725913-aa445ff8-c87f-11e7-9cbf-bc74b2af8f67.png)
note: *I'm not sure what was set here before and if this section existed at all*. I know that we didn't set it.
1. After creating the new revision, the requirements section changed to this:
![image](https://user-images.githubusercontent.com/8449713/32725966-d7ddb9a0-c87f-11e7-9079-baec2340db0d.png)
note the added `logging-driver` attribute

==> Result is that I got this `... is missing an attribute required by your task` error .

### Workaround:  I set `logging-drive` to `syslog`

**Comment by furlanrapha** [comment] 2017-11-13 13:18
Hey @ofiliz, our workaround over here was to set the Logging config. on the JSON as null at the moment we are creating a new revision.

Like this:
```
    ...
    "logConfiguration": null,
    ...
```

**Comment by nmeyerhans** [comment] 2017-11-14 17:27
We've identified a problem with the ECS service, outside the agent itself, that lead to this situation. The issue has been resolved and "none" should work as a log driver again. You don't need to modify your agent in order to receive the fix.

**Closed by nmeyerhans** 2017-11-14 17:27 UTC
