### ISSUE TITLE
Flaky functional test on arm : TestOOMTask

### ISSUE THREAD

**Issue by ubhattacharjya** [aws/amazon-ecs-agent#1962] opened 2019-03-25 19:53 UTC
### Summary
Flaky functional test on arm : TestOOMTask

### Expected Behavior
The test should pass

### Observed Behavior
The test is failing with following output:

```
=== RUN   TestOOMTask
--- FAIL: TestOOMTask (24.49s)
	utils_unix.go:130: Created directory /tmp/tmp.Qu9Fbjm3kY/ecs_integ_testdata325870754 to store test data in
	utils_unix.go:146: Launching agent with image: amazon/amazon-ecs-agent:latest
	utils_unix.go:233: Agent started as docker container: 768361ecb3cc22ee9e364c9c5f7c55e3ce2e3681324aa9571fb52cdfb6779b2c
	utils.go:175: Found agent metadata: {Cluster:ecs-functional-tests ContainerInstanceArn:0x44203315c0 Version:Amazon ECS Agent - v1.26.0 (dbfa7407)}
	utils.go:196: Task definition: ecsftest-oom-task-e897d4b6ad863ae5bc006f667ba6545c:1
	utils.go:216: Started task: arn:aws:ecs:us-west-2:508403128001:task/17dc2279-fe6e-4937-990b-9d2f146cc0e3
	functionaltests_unix_test.go:124: 
			Error Trace:	functionaltests_unix_test.go:124
			Error:      	Received unexpected error:
			            	Expected error reason
			            	github.com/aws/amazon-ecs-agent/agent/functional_tests/util.(*TestTask).ExpectErrorType
			            		/opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/functional_tests/util/utils.go:583
			            	github.com/aws/amazon-ecs-agent/agent/functional_tests/tests.TestOOMTask
			            		/opt/amazon-ecs-agent/go/src/github.com/aws/amazon-ecs-agent/agent/functional_tests/tests/functionaltests_unix_test.go:123
			            	testing.tRunner
			            		/usr/local/go/src/testing/testing.go:746
			            	runtime.goexit
			            		/usr/local/go/src/runtime/asm_arm64.s:931
			Test:       	TestOOMTask


### Supporting Log Snippets
<!--
Please have a look at https://github.com/awslabs/ecs-logs-collector
for the data we typically require for investigation

Please note that GitHub issues are public, remove sensitive data from logs before posting.
If you are not comfortable posting your logs here, please let us know and we
can provide an alternate method.
-->

**Comment by fenxiong** [comment] 2019-04-11 17:54
this is caused by a recent change in our CI tool and has been fixed. closing

**Closed by fenxiong** 2019-04-11 17:54 UTC
Labels: kind/testing
