### ISSUE TITLE
Draining instances should deregister their available MEM/CPU.

### ISSUE THREAD

**Issue by maartenvanderhoef** [aws/amazon-ecs-agent#718] opened 2017-02-28 11:42 UTC
An ECS Instance in draining state should deregister the available memory and cpu to the cluster. In an autoscaling scenario this would then cause the CPUReservation and MemoryReservation to cross the alarm causing fresh nodes to be added automatically.

**Comment by liwenwu-amazon** [comment] 2017-03-22 22:01
Hi,

ECS already deregisters the reservation metrics for a draining instance. However, the instance status updates server-side once every 10-15 minutes. This means that the instance's available cpu and mem will still be marked as available for up to 15 minutes.

I understand that it would be better for this process to be more timely. Could you describe your use case?

**Comment by aaithal** [comment] 2017-04-14 22:50
Hi @maartenvanderhoef Thank you for reporting this issue. An instance which is in `DRAINING` state does get discounted from `CPUReservation` and `MemoryReservation`. However, this does not take into effect immediately and does take some time for the reconciliation to happen in metrics. Could you please answer the following questions to help us better address this issue?

1. Are you seeing DRAINING instances always accounting for these metrics and never being discounted for this calculation?
2. If not, is the delay in reconciliation causing you issues and is that the actual issue that you're concerned about? 

Thanks,
Anirudh

**Comment by samuelkarp** [comment] 2017-05-16 23:15
@maartenvanderhoef We haven't heard from you in a while, so I'm going to close this issue.  If you get a chance to respond to @aaithal's questions we'd be happy to reopen it.

**Closed by samuelkarp** 2017-05-16 23:15 UTC
Labels: more info needed, scope/ECS Service

**Comment by dmulter** [comment] 2017-11-07 19:31
I have the same issue. My use case is the following:

- Create an ASG for version 1.0.0 with scale-in/out based on memory reservation.
- Things running fine for a while.
- Deploy a new ASG version 1.0.1 with same scaling.
- Mark tasks on old ASG as draining.
- Wait for all old tasks to migrate to new ASG.
- PROBLEM description below...
- Cleanup all ASG 1.0.0 resources

So you can see the problem is that the new ASG won't scale-out to allow the old tasks to migrate to the new ASG. The old ASG memory is caused the scale-out limit to never be reached.
