### ISSUE TITLE
Missing metrics after network issue

### ISSUE THREAD

**Issue by rvandegrift** [aws/amazon-ecs-agent#532] opened 2016-09-16 15:57 UTC
I've had a few network problems break connectivity between ECS agent and AWS.  After the network recovers, ecs-agent mostly comes back okay.  But no metrics appear until I manually restart ecs-agent.  After a restart, cluster and service metrics return immediately.

Any possibility that this state could be detected and fixed without manual intervention?

**Comment by aaithal** [comment] 2016-09-16 16:02
@rvandegrift We have fail-safe's in the ECS Agent which should reconnect it with our metrics backend during such events. Could you please let us know which version of the ECS Agent is running on your instance. It'd also be great if you could share the ECS Agent log when this happened as well. You can email it to aithal at amazon dot com as it'd contain your resource ARNs. 

Thanks,
Anirudh

**Comment by rvandegrift** [comment] 2016-09-16 17:26
ECS agent is 1.12.1.  How long should that recovery take?  I checked the console just a few minutes after network recovery.  All of the container instances were registered, but no new metrics.  Every 10-20 mins in the logs I see: `Creating poll dialer, host: ecs-a-2.us-east-1.amazonaws.com`.  Maybe I just needed to wait a while longer?

I just emailed the logs, thanks for taking a look.

**Comment by richardpen** [comment] 2016-09-28 23:21
@rvandegrift Thanks for reporting. We have found the cause of this problem, please see the PR #545 to track update and release.

**Comment by richardpen** [comment] 2016-11-17 23:00
@rvandegrift We released [v1.13.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.13.1) today which should fix the problem. I'm closing this for now, feel free to reopen it if you run into this issue in the future.

**Closed by richardpen** 2016-11-17 23:00 UTC
Labels: bug, pending release
