### ISSUE TITLE
Extra powerful CPU effort reported

### ISSUE THREAD

**Issue by workybee** [aws/amazon-ecs-agent#378] opened 2016-04-15 21:33 UTC
Our cloudwatch dashboard for the cluster metrics associated with our 4 instance cluster occassionally shows CPUUtilization of 10,236,791,673% (or other extremely  high values I doubt are valid).

![extracpu_anyone_2016-04-14](https://cloud.githubusercontent.com/assets/13958914/14575444/b2004f8e-0316-11e6-83d2-33bba229d839.png)

We have also been having some other issues with docker commands being slow (see #377), wondering if they might be related?

**Comment by aaithal** [comment] 2016-04-22 23:06
@workybee Thanks for reporting this issue. We have been able to correlate this on our end as well and it seems like a bug in the ECS Agent. We will let you know if we need more details or when we have an update on this issue.

**Comment by workybee** [comment] 2016-05-03 17:56
Looks like the "fix" will prevent the bad reporting, but any idea why the toContainerStats is failing in first place? I see various instances in my 4 node cluster hitting 100% cpu at times, suspect a correlation with things being thrown off, but not sure.

**Comment by aaithal** [comment] 2016-05-03 17:59
>Looks like the "fix" will prevent the bad reporting, but any idea why the toContainerStats is failing in first place?

We sometimes see empty container stats from `libcontainer.GetStats()`, which impacted the computation in this particular case. 

> I see various instances in my 4 node cluster hitting 100% cpu at times, suspect a correlation with things being thrown off, but not sure.

Are you also seeing that instances' CPU utilization is not 100% when this happens?

**Comment by workybee** [comment] 2016-05-03 18:09
Not sure, and hard to tell from the cloudwatch graphs as when it gets a wild value all nearby stats get squashed to near zero. In general seems like one instance tends to get loaded hard than the other 3 for decent periods of time, but the load does seem to migrate occasionally.
I have seen discrepancies between cluster-wide CPU usage and AMI CPU usage stats, which in my world should be "the same" but I figure that is a side effect of the sampling time differences.

**Comment by workybee** [comment] 2016-05-03 18:27
You got me motivated to look harder ;-)
Found a way to see things a bit clearer, and indeed most cases seem to show non-100% CPU where the aggregate CPU is off the charts. Could be side effect of averaging? Don't have a recent enough case to see it un-averaged. Cloudwatch dashboard screenshot attached.
![extrapowerfullcpu_2016-05-02t1500](https://cloud.githubusercontent.com/assets/13958914/14993769/4a06fe1e-1121-11e6-9d7c-76987f348e04.png)

**Comment by aaithal** [comment] 2016-05-03 18:32
@workybee Thanks for adding those :)

>indeed most cases seem to show non-100% CPU where the aggregate CPU is off the charts. Could be side effect of averaging?

It does seem like that is a side-effect of the issue in question. That should be resolved once the fix goes out.

What I wanted to know with my earlier question was, if you were seeing a case where ECS Cluster metric reports that the CPU utilization in the cluster is 100%. But, if you look at individual instances' CPU utilization (from EC2 metrics), they don't add up.

**Comment by workybee** [comment] 2016-05-03 19:04
I'll try and catch an occurrence before averaging sets in.
Using EC2 metrics directly (instead of the dashboard) was able to generate this screenshot that might not be averaged:
![extrapowerfullcpu_2016-05-02t1600p1800](https://cloud.githubusercontent.com/assets/13958914/14994806/8858d7dc-1126-11e6-98c9-29896d4d4910.png)

I think it shows only one instance being near 100% CPU, and they definitely don't add up to the 1,573,935,043% that the aggregate metric shows (sorry, couldn't figure out how to capture that popup in my screenshot). The aggregate metric was 23% and 33% the 5 minutes before and after this spike respectively.

**Comment by aaithal** [comment] 2016-05-03 19:13
>I think it shows only one instance being near 100% CPU, and they definitely don't add up to the 1,573,935,043%

Right, and that should be resolved with the [fix we submitted](https://github.com/aws/amazon-ecs-agent/issues/391).

**Comment by workybee** [comment] 2016-05-03 19:22
Yes, I think I can see how the fix will at least mask this error from surfacing, but does it address the root cause? (And would it matter or is this purely about metrics and wouldn't effect my containers on the instances? Haven't seen issue #377 in the last week since upgrading to 2016.03.a but seemed potentially related, and deeper than just the metrics.)

**Comment by aaithal** [comment] 2016-05-03 19:31
As I mentioned earlier, the root cause is ECS Agent's stats engine getting empty container stats from [`libcontainer.GetStats()`](https://github.com/aws/amazon-ecs-agent/blob/master/agent/stats/container.go#L103). We submit a metric message to our backend approximately every 20 seconds. Each such message is computed by aggregating 40 * 500 millisecond [samples](https://github.com/aws/amazon-ecs-agent/blob/master/agent/stats/container.go#L83). Dropping a faulty sample only means that, on rare occasions when we get an empty stats object from libcontainer, the sample count deteriorates by count of 1. That is, instead of 40 samples contributing to a metric, 39 samples contribute to it. So, it doesn't lead to miscalculation of metrics, only to a reduction in the sample count while computing the metric. I hope this addresses your concern about any effect it has on the metric computed for your cluster/container instances.

**Comment by workybee** [comment] 2016-05-03 22:04
Yes, this addresses any concerns I had about metrics nicely, thank you.
Leaves me with a (very small) concern about why libcontianer.GetStats() is occasionally failing.
Looking at that code seems like it could be network exhaustion error, which if it stays rare is of very little concern.
Any way to get a sense of how frequently it might be happening? Maybe should keep the old mega-percent-CPUUsage behaviro as a proxy for this. ;-)
I've had a few containers hang "forever" (hours, when they should take minutes to finish in worst case) and am wondering if they could be hitting some network glitch as well?

**Comment by aaithal** [comment] 2016-05-03 22:23
In my test setup, where I have a 3 instance cluster, I have seen it happen 4 times in 14 days (sample count of 14 * 24 * 60 * 60 * 2 * 3 = 7257600), which means it has happened once every 1814400 samples  (equivalent 1 instance, 21 days worth of samples). I am not sure why libcontainer returns empty stats in this scenario. Another thing to note is that the ECS Agent does not use the `docker stats` interface and moving to that interface would get rid of that altogether. 

>Looking at that code seems like it could be network exhaustion error,
>I've had a few containers hang "forever" (hours, when they should take minutes to finish in worst case) and am wondering if they could be hitting some network glitch as well?

I am not sure what's going on there. But, feel free to open a new issue for that, hopefully with docker and ECS Agent logs.

**Comment by workybee** [comment] 2016-05-03 22:24
Will do if I can make it into something at all cohesive. Thanks for all your help and the detailed explanations.

**Comment by samuelkarp** [comment] 2016-05-06 21:43
@workybee Thanks for reporting this bug.  We've resolved this with the [1.9.0 release](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.9.0).

**Closed by samuelkarp** 2016-05-06 21:43 UTC
Labels: bug

**Comment by workybee** [comment] 2016-05-06 22:11
Thanks for the fix. Already deployed and seems to be working fine (though problems were rare, so I'm being trusting ;-)
