### ISSUE TITLE
ecs-agent spamming log messages about OOM

### ISSUE THREAD

**Issue by Luzifer** [aws/amazon-ecs-agent#448] opened 2016-07-13 09:55 UTC
**Observed state**
- Downloaded log archives from PaperTrail where the logs are streamed to
- Analysed logs locally to find how many messages were generated
- Found 45674 messages within 6.5h (=23400s) from one machine stating a process in container X died from OOM

``` bash
# zgrep "7fb0ade6e5e85cd8b47a9daf9261055aae30c93b044a6367a1db9bed0da37ca1 died due to" 2016-07-1* | grep ecs-agent | sort | head -n1 | awk -F $'\t' '{ print $3 " - " $9 " - " $10 }'
2016-07-12T23:25:08Z - ecs-agent - 2016-07-12T23:25:08Z [INFO] process within container 7fb0ade6e5e85cd8b47a9daf9261055aae30c93b044a6367a1db9bed0da37ca1 died due to OOM

# zgrep "7fb0ade6e5e85cd8b47a9daf9261055aae30c93b044a6367a1db9bed0da37ca1 died due to" 2016-07-1* | grep ecs-agent | sort | tail -n1 | awk -F $'\t' '{ print $3 " - " $9 " - " $10 }'
2016-07-13T05:59:44Z - ecs-agent - 2016-07-13T05:59:44Z [INFO] process within container 7fb0ade6e5e85cd8b47a9daf9261055aae30c93b044a6367a1db9bed0da37ca1 died due to OOM

# zgrep "7fb0ade6e5e85cd8b47a9daf9261055aae30c93b044a6367a1db9bed0da37ca1 died due to" 2016-07-1* | grep ecs-agent | wc -l
45674
```

**Expected state**

ecs-agent sends this information to the log once when the process dies but does not spam the log with an amount of ~50k messages until the container is removed from the system

**Comment by aaithal** [comment] 2016-07-21 19:01
@Luzifer thanks for reporting this issue. We've tried the following combinations, but haven't been able to reproduce this issue:

#### Task Definition with a single container; container OOMs
```
{
  "taskDefinitionArn": "arn:aws:ecs:us-west-2:123456789012:task-definition/mem-stress-backoff:1",
  "status": "ACTIVE",
  "revision": 1,
  "containerDefinitions": [
    {
      "memory": 800,
      "essential": true,
      "entryPoint": [
        "bash",
        "-c"
      ],
      "name": "stress",
      "image": "ubuntu",
      "command": [
        "apt-get update; apt-get install stress; stress -m 1 --vm-bytes 800m --vm-keep --backoff 60s;"
      ],
      "cpu": 100,
    }
  ],
  "family": "mem-stress-backoff"
}
```

#### Task Definition with 2 containers; non-essential container OOMs
```
{
  "taskDefinitionArn": "arn:aws:ecs:us-west-2:123456789012:task-definition/mem-stress-backoff:4",
  "status": "ACTIVE",
  "revision": 4,
  "containerDefinitions": [
    {
      "memory": 800,
      "entryPoint": [
        "bash",
        "-c"
      ],
      "name": "stress",
      "image": "ubuntu",
      "command": [
        "apt-get update; apt-get install stress; sleep 30; stress -m 1 --vm-bytes 800m --vm-keep --backoff 60s;"
      ],
      "cpu": 100,
    },
    {
      "memory": 10,
      "essential": true,
      "entryPoint": [
        "bash",
        "-c"
      ],
      "name": "sleep",
      "image": "ubuntu",
      "command": [
        "sleep 1200"
      ],
      "cpu": 10,
    }
  ],
  "family": "mem-stress-backoff"
}
```

#### Logs

Essential container is still running, non-essential container has OOM'd
```bash
$ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                      PORTS                        NAMES
61cd238c8d50        ubuntu                         "bash -c 'apt-get upd"   16 minutes ago      Exited (1) 15 minutes ago                                ecs-mem-stress-backoff-4-stress-ae87d1eafee68f939b01
8cca91de468d        ubuntu                         "bash -c 'sleep 1200'"   16 minutes ago      Up 16 minutes                                            ecs-mem-stress-backoff-4-sleep-dcfec8f9d1eb87d97b00
efc7c441e08e        amazon/amazon-ecs-agent:make   "/agent"                 16 minutes ago      Up 16 minutes               127.0.0.1:51678->51678/tcp   ecs-agent

$ docker logs ecs-agent | grep "due to"
2016-07-21T18:31:41Z [INFO] process within container 61cd238c8d50da35bd24c95435b6395e099f03767e207403739e9552badfb152 died due to OOM
```

Both containers have stopped, but not yet cleaned up
```bash
$ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                          PORTS                        NAMES
61cd238c8d50        ubuntu                         "bash -c 'apt-get upd"   30 minutes ago      Exited (1) 29 minutes ago                                    ecs-mem-stress-backoff-4-stress-ae87d1eafee68f939b01
8cca91de468d        ubuntu                         "bash -c 'sleep 1200'"   30 minutes ago      Exited (0) 20 minutes ago                                ecs-mem-stress-backoff-4-sleep-dcfec8f9d1eb87d97b00
efc7c441e08e        amazon/amazon-ecs-agent:make   "/agent"                 30 minutes ago      Up 30 minutes                   127.0.0.1:51678->51678/tcp   ecs-agent

$ docker logs ecs-agent | grep "due to"
2016-07-21T18:31:41Z [INFO] process within container 61cd238c8d50da35bd24c95435b6395e099f03767e207403739e9552badfb152 died due to OOM
```

Note that we still see one log line related to a container dying of OOM. Could you please provide the ECS Agent version that you were using, the task definition ARN/snippet (I'm interested in how many containers were there, how long was the task running for etc) and the task arn as well?

You can email them to aithal at amazon dot com if you do not want to share these on github.

Thanks,
Anirudh

**Comment by Tomdarkness** [comment] 2016-07-30 03:25
We've had a similar problem where the log is spammed with the same message, although not to such an extent as mentioned above.

@aaithal I don't think your test case will reproduce the issue. The OOM occurs in our containers when the initial process spawns child processes that start using too much memory which are then killed - not that the initial process in the docker container is killed. The container itself keeps running.

**Comment by richardpen** [comment] 2016-08-03 21:29
@Tomdarkness @Luzifer I was able to reproduce by using the task definition below:
```
{
    "taskDefinition": {
        "status": "ACTIVE",
        "family": "memory-over-commit",
        "volumes": [],
        "taskDefinitionArn": "arn:aws:ecs:us-west-2:123456789012:task-definition/memory-over-commit:1",
        "containerDefinitions": [
            {
                "environment": [],
                "name": "Show_time",
                "mountPoints": [],
                "image": "ubuntu",
                "cpu": 10,
                "portMappings": [],
                "command": [
                    "sh",
                    "-c",
                    "apt-get update; apt-get install stress; while [ true ]; do echo `date +%T`; stress -m 1 --vm-bytes 800m --vm-keep --backoff 60s & sleep 1s; done;"
                ],
                "memory": 100,
                "essential": true,
                "volumesFrom": []
            }
        ],
        "revision": 1
    }
}
```
The OOM message is generated each time the command is running `stress -m 1 --vm-bytes 800m --vm-keep --backoff 60s &`. But using the task definition below, only one OOM message will be logged.
```
{
    "taskDefinition": {
        "status": "ACTIVE",
        "family": "memory-over-commit",
        "volumes": [],
        "taskDefinitionArn": "arn:aws:ecs:us-west-2:123456789012:task-definition/memory-over-commit:1",
        "containerDefinitions": [
            {
                "environment": [],
                "name": "Show_time",
                "mountPoints": [],
                "image": "ubuntu",
                "cpu": 10,
                "portMappings": [],
                "command": [
                    "sh",
                    "-c",
                    "apt-get update; apt-get install stress; stress -m 1 --vm-bytes 800m --vm-keep --backoff 60s & while [ true ]; do echo `date +%T`;  sleep 1s; done;"
                ],
                "memory": 100,
                "essential": true,
                "volumesFrom": []
            }
        ],
        "revision": 1
    }
}
```
I think the spamming OOM message in your log is caused by the initial process keeps recreating child process when child process runs OOM and is killed.
The agent will log the message every time it received the OOM from docker, so the solutions we have to fix this are:
* Don't log the OOM message.
* Change the log level for OOM event to Debug instead of Info.

Please let me know your opinion.

**Comment by samuelkarp** [comment] 2016-12-15 00:37
@Luzifer @Tomdarkness Is this still a problem for you?

**Comment by Luzifer** [comment] 2016-12-15 01:15
@seiffert Could you please check this once and get back to Samuel?

**Comment by Tomdarkness** [comment] 2016-12-15 19:57
We don't see this in our logs anymore, but it's because we fixed the issue in our docker images that was causing the child processes to consume excessive memory and hit OOM. Not sure if the log messages still occur if you have a child process cause the container to hit OOM.

**Comment by samuelkarp** [comment] 2016-12-15 21:50
@Tomdarkness The log messages likely still occur in that situation since we haven't changed how the agent behaves.  I'm just trying to get a feel for what the impact is of this right now to assess priority.

**Comment by Luzifer** [comment] 2017-01-02 13:55
@samuelkarp just did a search for that behaviour in our logs and did found repetitions of that error but only with count 2-6, not >40k… So currently no issue for us…

**Comment by samuelkarp** [comment] 2017-03-31 22:18
@Luzifer Thanks for confirming.  I'm going to close this issue for now, but we can take a look again if anyone else runs into it.

**Closed by samuelkarp** 2017-03-31 22:18 UTC
